Add Kavita extension
tachiyomiorg/tachiyomi-extensions pull request #10241
Opened 2021-12-26 22:07 UTC by ThePromidius

### Description:
Supports all services provided by kavita API.
Expected to add two-way tracking in the future
Minimum Kavita version: v0.4.9.24
 
Closes #9332 

### Checklist:
- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

Disclaimer:
I still don't control github very well so apologies if anything is wrong. Tips and comments are welcomed.

2021-12-26 22:18 UTC, alessandrojean requested changes

2021-12-26 22:18 UTC, alessandrojean commented on src/all/kavita/build.gradle
> +    extVersionCode = 6
Extension versions should start in 1 if they are new.

```suggestion
    extVersionCode = 1
```

2021-12-26 22:18 UTC, alessandrojean commented on src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/Kavita.kt
> +            .toRequestBody("application/json; charset=utf-8".toMediaTypeOrNull())
Can probably just hardcode the string and remove the usage of `org.json` stuff.

```suggestion
        val body = "{}".toRequestBody("application/json; charset=utf-8".toMediaTypeOrNull())
```

2021-12-26 22:41 UTC, alessandrojean approved these changes

2021-12-26 23:13 UTC, jopejoe1 commented
Please uses these icons to be more consistent with other extensions.
[ic_launcher(6).zip](https://github.com/tachiyomiorg/tachiyomi-extensions/files/7777699/ic_launcher.6.zip)

2021-12-26 23:17 UTC, ThePromidius commented
> Please uses these icons to be more consistent with other extensions. [ic_launcher(6).zip](https://github.com/tachiyomiorg/tachiyomi-extensions/files/7777699/ic_launcher.6.zip)

Much appreciated. TBH i had problems finding some good icons.

2021-12-26 23:33 UTC, ThePromidius commented
Marked as draft till there is a stable build version of kavita that supports the extension.

2022-01-18 02:44 UTC, ThePromidius commented
> Please uses these icons to be more consistent with other extensions. [ic_launcher(6).zip](https://github.com/tachiyomiorg/tachiyomi-extensions/files/7777699/ic_launcher.6.zip)

Would it be possible to have those icons but changing the black border with the same green the circle is made of?
Would that still be consistent with the rest?

2022-01-18 03:56 UTC, jopejoe1 commented
> > Please uses these icons to be more consistent with other extensions. [ic_launcher(6).zip](https://github.com/tachiyomiorg/tachiyomi-extensions/files/7777699/ic_launcher.6.zip)
> 
> Would it be possible to have those icons but changing the black border with the same green the circle is made of? Would that still be consistent with the other extensions?

Yes that would still be consistent
[ic_launcher(7).zip](https://github.com/tachiyomiorg/tachiyomi-extensions/files/7886071/ic_launcher.7.zip)

2022-01-18 23:04 UTC, ThePromidius commented
Kavita v0.5.0 (stable) is ready. PR ready for revision.

2022-01-21 15:55 UTC, alessandrojean approved these changes
The URL checking is just a suggestion, don't need to be followed. The other things looks fine to me :+1:.

2022-01-22 16:38 UTC, majora2007 commented
Any chance we can get this merged in? I see we have approval from a member of Tachiyomi.

2022-01-24 10:23 UTC, merged

2022-01-24 10:25 UTC, edgehub-cloud commented
Bllesed

2022-01-24 23:23 UTC, ThePromidius commented on src/all/kavita/src/eu/kanade/tachiyomi/extension/all/kavita/Kavita.kt
>          if (!baseUrlSetup.startsWith("http")) {
thanks will do