Add Madara Source: Reader's Point
tachiyomiorg/tachiyomi-extensions pull request #10443
Opened 2022-01-13 10:34 UTC by Shota5749

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

2022-01-13 23:36 UTC, Shota5749 commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> +        SingleLang("Reader's Point", "https://readers-point.space/", "en"),
Added

2022-01-14 04:42 UTC, jopejoe1 requested changes

2022-01-14 04:42 UTC, jopejoe1 commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> +        SingleLang("Reader's Point", "https://readers-point.space", "en", className = "Reader's Point"),
Remove the space and `'` in class name as it only supports letters & digits

2022-01-14 04:55 UTC, Shota5749 commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> +        SingleLang("Reader's Point", "https://readers-point.space", "en", className = "Reader's Point"),
Edited

2022-01-20 10:00 UTC, CarlosEsco commented
Still has build issues

2022-01-22 17:21 UTC, alessandrojean commented
Would be better to use [this tool] to generate the icons to keep the consistency with the others.

About the build errors, I don't see anything wrong in the code, maybe it's just some random failure (as already happened before).

A build rerun could help.

[this tool]: https://as280093.github.io/AndroidAssetStudio/icons-launcher.html#foreground.type=clipart&foreground.clipart=android&foreground.space.trim=1&foreground.space.pad=0.25&foreColor=rgba(96%2C%20125%2C%20139%2C%200)&backColor=rgb(68%2C%20138%2C%20255)&crop=0&backgroundShape=square&effects=none&name=ic_launcher

2022-01-24 11:46 UTC, jopejoe1 commented
Removing the `'` from the source name should fix the build errors.

2022-01-24 11:51 UTC, Riztard commented
> Removing the `'` from the source name should fix the build errors.

on their website their name didnt use `'` too 
or maybe need `\`

2022-01-29 11:29 UTC, closed without merging