re-manga: Fix latest, chapter parsing
tachiyomiorg/tachiyomi-extensions pull request #10630
Opened 2022-01-30 23:12 UTC by vetleledaal

Closes #10061 

minor refactor, improve caching for popular and latest

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2022-01-30 23:33 UTC, alessandrojean requested changes

2022-01-30 23:33 UTC, alessandrojean commented on src/ar/remanga/src/eu/kanade/tachiyomi/extension/ar/remanga/REManga.kt
> +        return SimpleDateFormat("MMM d, yyy", Locale("ar")).parse(date)?.time ?: 0L
Better to create the date formatter object as a constant, otherwise it will be recreated every chapter.

2022-01-31 00:28 UTC, vetleledaal commented on src/ar/remanga/src/eu/kanade/tachiyomi/extension/ar/remanga/REManga.kt
> +        return SimpleDateFormat("MMM d, yyy", Locale("ar")).parse(date)?.time ?: 0L
I'm not too familiar with Kotlin/Android/Tachiyomi development. Which one would be the most preferable in this case? 

```kotlin
private val dateFormat = SimpleDateFormat(/**/)

private val dateFormat by lazy {
    SimpleDateFormat(/**/)
}

companion object {
    private val DATE_FORMATTER = SimpleDateFormat(/**/)
}

companion object {
    private val DATE_FORMATTER by lazy {
        SimpleDateFormat(/**/)
    }
}
```

2022-01-31 00:31 UTC, alessandrojean commented on src/ar/remanga/src/eu/kanade/tachiyomi/extension/ar/remanga/REManga.kt
> +        return SimpleDateFormat("MMM d, yyy", Locale("ar")).parse(date)?.time ?: 0L
All are accepted and valid solutions, but the ones that uses `by lazy` are the best because the formatter will only be generated in the first time it's accessed.

2022-01-31 12:10 UTC, merged