Add Shadow Mangas
tachiyomiorg/tachiyomi-extensions pull request #11149
Opened 2022-03-16 21:00 UTC by DTecheira

Closes #8203 #9007

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2022-03-16 21:19 UTC, DTecheira commented
What would I be missing?

2022-03-16 22:02 UTC, alessandrojean requested changes

2022-03-16 22:02 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt
> +        SingleLang("Shadow Mangas", "https://shadowmangas.com", "es", overrideVersionCode = 1),
If it's the first version, you can omit the `overrideVersionCode`.

```suggestion
        SingleLang("Shadow Mangas", "https://shadowmangas.com", "es"),
```

2022-03-17 00:47 UTC, vetleledaal commented
CI appears to have failed on something unrelated, you can push a new commit to retry

2022-03-18 00:48 UTC, arkon commented
@mergifyio rebase

2022-03-18 02:56 UTC, merged