Fix date and chapter name from ReaperScans EN
tachiyomiorg/tachiyomi-extensions pull request #11150
Opened 2022-03-16 21:11 UTC by SilverBeamx

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

This PR aims to fix chapter names and dates in the ReaperScan En extension, which are currently broken and set to null.

2022-03-16 22:05 UTC, alessandrojean commented
Since you removed the `chapterFromElement` override from the base `ReaperScans` class (which is used by the other languages of the website), you need to check if the chapter parsing them are still working too.

2022-03-16 22:12 UTC, SilverBeamx commented
Yes, i moved the generic one, that was wrong, into the EN version, because the BR version already has its custom implementation, and it isn't needed elsewhere. As i mentioned on Discord, should i ovverride the BR versionId to the old version because i didn't touch that part, or just bumping the overrall versionCode is fine?

2022-03-16 22:29 UTC, alessandrojean commented
Bumping the `overrideVersionCode` in `MadaraGenerator` the way you did is right 👍🏻 .

2022-03-17 00:42 UTC, jopejoe1 requested changes

2022-03-17 00:42 UTC, jopejoe1 commented on multisrc/overrides/madara/reaperscans/src/ReaperScansFactory.kt
> -    override val versionId = 2
The versionId override should not be removed as it would change the extension id

2022-03-17 01:30 UTC, alessandrojean commented on multisrc/overrides/madara/reaperscans/src/ReaperScansFactory.kt
> -    override val versionId = 2
Good catch!

2022-03-17 08:52 UTC, SilverBeamx commented on multisrc/overrides/madara/reaperscans/src/ReaperScansFactory.kt
> -    override val versionId = 2
Yea, this is what i was asking previously. I probably explained myself poorly. Should be fixed now!

2022-03-18 00:48 UTC, arkon commented
@mergifyio rebase

2022-03-18 03:00 UTC, merged