Add Haoman6
tachiyomiorg/tachiyomi-extensions pull request #11381
Opened 2022-04-08 12:16 UTC by anenasa

Closes  #11158

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2022-04-08 14:16 UTC, alessandrojean commented
Please create a valid icon without a transparent background. Use [this tool](https://as280093.github.io/AndroidAssetStudio/icons-launcher.html#foreground.type=clipart&foreground.clipart=android&foreground.space.trim=1&foreground.space.pad=0.25&foreColor=rgba(96%2C%20125%2C%20139%2C%200)&backColor=rgb(68%2C%20138%2C%20255)&crop=0&backgroundShape=square&effects=none&name=ic_launcher) for creating it.

2022-04-08 18:39 UTC, alessandrojean requested changes

2022-04-08 18:39 UTC, alessandrojean commented on src/zh/haoman6/src/eu/kanade/tachiyomi/extension/zh/haoman6/Haoman6.kt
> +    }
```suggestion
    override fun pageListParse(document: Document): List<Page> {
        return document.select("div.rd-article__pic > img.lazy-read")
            .mapIndexed { i, el -> Page(i, "", el.attr("abs:echo-pc") }
    }
```

2022-04-09 06:40 UTC, anenasa commented
Fixed both.

2022-04-09 13:40 UTC, alessandrojean approved these changes

2022-04-09 13:43 UTC, merged