[skip ci] Build only changed languages for individual sources in PRs
tachiyomiorg/tachiyomi-extensions pull request #11417
Opened 2022-04-10 16:36 UTC by scb261

Made it mostly for myself and didn't hope to actually finish it. Probably needs some cleanup, since it's my first time doing this. You can test changes by PRing to the `pr_individual` branch in my repo.

Example of a successful build - https://github.com/scb261/tachiyomi-extensions/pull/3
Example with build error - https://github.com/scb261/tachiyomi-extensions/pull/4

As for multisrc, I'm thinking about generating only changed themes and then building all languages, but this would require changes in a gradle task and main generator.

2022-04-10 17:06 UTC, scb261 commented
Converting to draft for now, since it doesn't consider if something like gradle file was changed outside of src directory

2022-04-10 17:57 UTC, scb261 commented
Should be fine now, example - https://github.com/scb261/tachiyomi-extensions/pull/6

2022-04-10 18:17 UTC, FourTOne5 requested changes

2022-04-10 18:17 UTC, FourTOne5 commented on .github/workflows/build_pull_request.yml
> +          is_root_cganged=0
`cganged` xD

2022-04-10 18:17 UTC, FourTOne5 commented on .github/workflows/build_pull_request.yml
> +              is_root_cganged=1
`cganged`?

2022-04-10 18:17 UTC, FourTOne5 commented on .github/workflows/build_pull_request.yml
> +          if [ $is_root_cganged -eq 1 ] ; then
(⊙_◎)

2022-04-10 18:20 UTC, scb261 commented on .github/workflows/build_pull_request.yml
> +          is_root_cganged=0
thanks, fixed

2022-07-16 18:57 UTC, arkon commented
Considering we don't do it by languages anymore, it may be worth just doing it so that it's:

- If only `src/` files changed: build individual
- If only `multisrc/` files changed: build multisrc
- If anything outside of those changed, build everything

So more or less what you have, but without the individual language bit?

2022-07-17 09:57 UTC, scb261 commented
Superseded by #12608

2022-07-17 09:57 UTC, closed without merging