fix: manga-gohan changed their url
tachiyomiorg/tachiyomi-extensions pull request #11462
Opened 2022-04-14 14:07 UTC by alekc

Closes https://github.com/tachiyomiorg/tachiyomi-extensions/issues/11430

Manga Gohan changed their url to https://gokumanga.com/

Checklist:

- [X ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [X] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [X] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [X] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio

2022-04-14 14:55 UTC, alessandrojean requested changes

2022-04-14 14:55 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> +        SingleLang("Manga Gohan", "https://gokumanga.com/", "ja", overrideVersionCode = 2),
```suggestion
        SingleLang("Manga Gohan", "https://gokumanga.com/", "ja", overrideVersionCode = 1),
```

Should be `1` because the first value if not provided is `0`.

2022-04-14 15:01 UTC, alekc commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> +        SingleLang("Manga Gohan", "https://gokumanga.com/", "ja", overrideVersionCode = 2),
done, and force pushed.

2022-04-15 14:42 UTC, merged

2022-04-16 14:02 UTC, kaonkaon commented
Thank you so much!!