[RU]UniComics
tachiyomiorg/tachiyomi-extensions pull request #11695
Opened 2022-05-02 08:30 UTC by e-shl

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

2022-05-02 19:12 UTC, alessandrojean requested changes

2022-05-02 19:12 UTC, alessandrojean commented on src/ru/unicomics/src/eu/kanade/tachiyomi/extension/ru/unicomics/UniComics.kt
> +        }
```suggestion
        pages += (1..dataStrArray[1].toInt()).toList()
```

2022-05-02 19:12 UTC, alessandrojean commented on src/ru/unicomics/src/eu/kanade/tachiyomi/extension/ru/unicomics/UniComics.kt
> +            }
```suggestion
            if (it.contains(" №")) {
                chapter.name = it.substringAfterLast(" ")
                chapter.chapter_number = it.substringAfter(" №").toFloatOrNull() ?: -1f
            }
```

2022-05-02 19:12 UTC, alessandrojean commented on src/ru/unicomics/src/eu/kanade/tachiyomi/extension/ru/unicomics/UniComics.kt
> +        return pages
```suggestion
        val dataStrArray = document.toString()
            .substringAfter("new Paginator(")
            .substringBefore(");</script>")
            .split(", ")

        return (1..dataStrArray[1].toInt()).mapIndexed { i, page ->
            Page(i, document.location() + "/$page")
        }
```

2022-05-03 03:24 UTC, e-shl commented on src/ru/unicomics/src/eu/kanade/tachiyomi/extension/ru/unicomics/UniComics.kt
> +    override fun popularMangaParse(response: Response): MangasPage {
Without it, page switching/nextpage only works in j2k

2022-05-03 03:32 UTC, alessandrojean commented on src/ru/unicomics/src/eu/kanade/tachiyomi/extension/ru/unicomics/UniComics.kt
> +    override fun popularMangaParse(response: Response): MangasPage {
Ah, I understand what you're doing now. Can keep the function, no problem.

2022-05-03 03:34 UTC, alessandrojean approved these changes

2022-05-03 16:18 UTC, merged