Add baimangu source
tachiyomiorg/tachiyomi-extensions pull request #11702
Opened 2022-05-02 18:36 UTC by lmk1988

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

Related to #11690

2022-05-02 19:22 UTC, alessandrojean requested changes

2022-05-02 19:22 UTC, alessandrojean commented on src/zh/baimangu/src/eu/kanade/tachiyomi/extension/zh/baimangu/Baimangu.kt
> +    override val id = 4481082429645987824
Was this previously available before...?

2022-05-02 19:22 UTC, alessandrojean commented on src/zh/baimangu/src/eu/kanade/tachiyomi/extension/zh/baimangu/Baimangu.kt
> +        return manga
```suggestion
        return SManga.create().apply {
            title = element.select("dd.fed-deta-content a:first-child").first().text()
            thumbnail_url = picElement.attr("data-original")
            setUrlWithoutDomain(picElement.attr("href"))
        }
```

2022-05-02 19:22 UTC, alessandrojean commented on src/zh/baimangu/src/eu/kanade/tachiyomi/extension/zh/baimangu/Baimangu.kt
> +            status = SManga.UNKNOWN
Can just remove the lines then, no need to manually assign to `UNKNOWN` since it already defaults to that.

2022-05-02 19:22 UTC, alessandrojean commented on src/zh/baimangu/src/eu/kanade/tachiyomi/extension/zh/baimangu/Baimangu.kt
> +    }
```suggestion
    override fun chapterFromElement(element: Element): SChapter = SChapter.create().apply {
        name = element.text().trim()
        setUrlWithoutDomain(element.attr("href"))
    }
```

2022-05-02 19:22 UTC, alessandrojean commented on src/zh/baimangu/src/eu/kanade/tachiyomi/extension/zh/baimangu/Baimangu.kt
> +        throw Error("Unable to match for OScript")
No need to iterate through all scripts, just directly find the one with Jsoup's `:containsData` selector.

```suggestion
        val theScript = document.selectFirst("script:containsData(oScript.src)")?.data()
            ?: throw Exception("Unable to find the OScript")
            
        val pattern = Pattern.compile("src(\\s*)=(\\s*)\"(.+)\";")
        val matcher = pattern.matcher(data)
        
        if (matcher.find()) {
            return matcher.group(3) ?: throw Exception("Unable to extract OScript")
        }

        throw Error("Unable to find a match for OScript")
```

Please check if it's still working after changing it.

2022-05-03 06:04 UTC, lmk1988 commented on src/zh/baimangu/src/eu/kanade/tachiyomi/extension/zh/baimangu/Baimangu.kt
> +    override val id = 4481082429645987824
Always thought needed a `id`. Will remove it

2022-05-03 06:05 UTC, lmk1988 commented on src/zh/baimangu/src/eu/kanade/tachiyomi/extension/zh/baimangu/Baimangu.kt
> +        throw Error("Unable to match for OScript")
Nice, didn't know we can do `script:containsData`

2022-05-03 16:18 UTC, merged

2022-05-03 17:15 UTC, zhongfly commented
The order of chapters needs to be reversed, currently older chapters are considered newest, and newest chapters are considered first.

2022-05-03 17:17 UTC, alessandrojean commented
@zhongfly Please open an issue about it so someone can take a look and fix it.