Added support for Strip-Utopija
tachiyomiorg/tachiyomi-extensions pull request #11777
Opened 2022-05-07 15:36 UTC by ZerocksX

https://github.com/tachiyomiorg/tachiyomi-extensions/issues/3384

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2022-05-07 15:53 UTC, alessandrojean requested changes
Also use [this tool](https://as280093.github.io/AndroidAssetStudio/icons-launcher.html#foreground.type=clipart&foreground.clipart=android&foreground.space.trim=1&foreground.space.pad=0.25&foreColor=rgba(96%2C%20125%2C%20139%2C%200)&backColor=rgb(68%2C%20138%2C%20255)&crop=0&backgroundShape=square&effects=none&name=ic_launcher) as recommended by the CONTRIBUTING.md guide to generate the icons. They need to follow the same pattern of the other extensions, and not just a logo in a transparent background.

2022-05-07 15:53 UTC, alessandrojean commented on src/all/striputopija/build.gradle
> +    pkgNameSuffix = 'all.striputopija'
Why under the `all` package if the language inside the class is `en`? Move stuff to the `en` folder.

2022-05-07 15:53 UTC, alessandrojean commented on src/all/striputopija/src/eu/kanade/tachiyomi/extension/all/striputopija/StripUtopija.kt
> +    }
Why not using the `headersBuilder()`, `headers` and the already provided `GET` and `POST` methods by the extensions' lib?

2022-05-07 15:53 UTC, alessandrojean commented on src/all/striputopija/src/eu/kanade/tachiyomi/extension/all/striputopija/StripUtopija.kt
> +class StripUtopija : HttpSource() {
You're doing a lot of unnecessary code. Would be a lot better to take a look and make the class extends `ParsedHttpSource` instead. More details in the [`CONTRIBUTING.md`](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/CONTRIBUTING.md) guide.

2022-06-05 21:33 UTC, arkon commented
@ZerocksX Do you intend on updating this PR?

2022-06-06 04:33 UTC, ZerocksX commented
I started working on it a bit. I don't have time for it right now.

On Sun, Jun 5, 2022, 23:33 arkon ***@***.***> wrote:

> @ZerocksX <https://github.com/ZerocksX> Do you intend on updating this PR?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/tachiyomiorg/tachiyomi-extensions/pull/11777#issuecomment-1146887324>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AG632XNXUF4RQDQGBTHRGV3VNUMLPANCNFSM5VKSB3YA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-07-17 14:22 UTC, arkon commented
Closing for now, feel free to reopen if you revisit it.

2022-07-17 14:22 UTC, closed without merging