Mangceh migrated to mareceh
tachiyomiorg/tachiyomi-extensions pull request #11779
Opened 2022-05-07 17:55 UTC by TheKingTermux

* Removed Mangceh from Madara MultiSrc
* Added Mareceh to WPMangaStream MultiSrc

Closed #10784 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

2022-05-08 01:15 UTC, alessandrojean reviewed
Also remove the old override.

`multisrc/overrides/madara/mangceh/src/Mangceh.kt`

2022-05-08 01:15 UTC, alessandrojean commented on multisrc/overrides/wpmangastream/mareceh/src/Mareceh.kt
> +class Mareceh : WPMangaStream("Mareceh", "https://mareceh.com", "id") {
Potentially the URL paths have changed and the old URLs are unsupported. If it's the case, please also bump the `versionId`.

```suggestion
class Mareceh : WPMangaStream("Mareceh", "https://mareceh.com", "id") {

    override val versionId = 2

```

2022-05-08 01:45 UTC, TheKingTermux commented
> 

Roger that

2022-05-09 20:38 UTC, alessandrojean commented
Can you please use [this tool](https://as280093.github.io/AndroidAssetStudio/icons-launcher.html) to generate the icons? So they follow the same pattern of the other extensions.

2022-05-09 20:40 UTC, alessandrojean requested changes

2022-05-09 20:40 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt
> +        SingleLang("Mareceh", "https://mareceh.com", "id", isNsfw = true, overrideVersionCode = 1),
```suggestion
        SingleLang("Mareceh", "https://mareceh.com", "id", isNsfw = true, overrideVersionCode = 10),
```

Needs to be `10` because the old one was `23` (Madara's `baseVersionCode = 20` + Mangceh's `overrideVersionCode 
 = 3`), and since WpMangaStream's `baseVersionCode = 14`, `baseVersionCode + overrideVersionCode` should be `24` to it be an update and new version.

2022-05-09 21:42 UTC, TheKingTermux commented
> Can you please use [this tool](https://as280093.github.io/AndroidAssetStudio/icons-launcher.html) to generate the icons? So they follow the same pattern of the other extensions.

Okay
Im working on it

2022-05-09 22:47 UTC, alessandrojean requested changes

2022-05-09 22:47 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt
> +        SingleLang("Mareceh", "https://mareceh.com", "id", isNsfw = true, overrideVersionCode = 10),
Sorry about noticing it just now, but since the source changed its name, you need to keep the old package name, otherwise users will not receive any update to the existing extension. The `id` change in this case doesn't matter since the URLs are incompatible anyway.

```suggestion
        SingleLang("Mareceh", "https://mareceh.com", "id", isNsfw = true, pkgName = "mangceh", overrideVersionCode = 10),
```

After changing it, move the overrides from the `multisrc/overrides/wpmangastream/mareceh` folder to `multisrc/overrides/wpmangastream/mangceh`.

After this last change, the PR will be good and can be merged 👍🏻

2022-05-09 22:47 UTC, alessandrojean commented on multisrc/overrides/wpmangastream/mareceh/src/Mareceh.kt
> +package eu.kanade.tachiyomi.extension.id.mareceh
Remember to change the package inside the class too.

```suggestion
package eu.kanade.tachiyomi.extension.id.mangceh
```

2022-05-09 22:47 UTC, alessandrojean commented on multisrc/overrides/wpmangastream/mareceh/src/Mareceh.kt
> +class Mareceh : WPMangaStream("Mareceh", "https://mareceh.com", "id") {
Just a note: The class name should be let as it is now, i.e. can be kept as `Mareceh`. It's _only the package name_ that need to be the same as the old one.

2022-05-09 22:57 UTC, TheKingTermux commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStreamGenerator.kt
> +        SingleLang("Mareceh", "https://mareceh.com", "id", isNsfw = true, overrideVersionCode = 10),
Ohh i see
Thanks for the updated 👍🏻
And I finally understood a new lesson from you.

2022-05-09 23:16 UTC, TheKingTermux commented on multisrc/overrides/wpmangastream/mareceh/src/Mareceh.kt
> +class Mareceh : WPMangaStream("Mareceh", "https://mareceh.com", "id") {
Roger that

2022-05-09 23:16 UTC, TheKingTermux commented on multisrc/overrides/wpmangastream/mareceh/src/Mareceh.kt
> +package eu.kanade.tachiyomi.extension.id.mareceh
Roger

2022-05-09 23:34 UTC, alessandrojean commented
Forgot to remove the `multisrc/overrides/wpmangastream/mareceh` folder as it is not used anymore (it has icons inside, delete them too).

2022-05-09 23:36 UTC, TheKingTermux commented
> Forgot to remove the `multisrc/overrides/wpmangastream/mareceh` folder as it is not used anymore (it has icons inside, delete them too).

Sorry i forgot it deleting them 😅

2022-05-09 23:43 UTC, alessandrojean approved these changes

2022-05-10 17:08 UTC, alessandrojean approved these changes

2022-05-11 18:52 UTC, merged