Add MangaReader Extension
tachiyomiorg/tachiyomi-extensions pull request #11811
Opened 2022-05-10 12:53 UTC by Skittyblock

This builds on #9325 and unscrambles the images.
Let me know if I should change anything; this is my first time working with Kotlin.

Replaces #9325 
Closes #9112
---

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2022-05-10 16:45 UTC, vetleledaal commented
Seems to shuffle all chapters regardless if they're shuffled in the first place:
https://mangareader.to/read/spy-x-family-86/en/chapter-62.2 (not shuffled)
<img src="https://user-images.githubusercontent.com/13540478/167680043-1de9d8fa-0101-4c94-abe6-f8e292f5350b.png" width="300px" />


Can confirm unshuffling works for shuffled chapters:
https://mangareader.to/read/undead-unluck-7025/en/chapter-1 (shuffled)
<img src="https://user-images.githubusercontent.com/13540478/167679891-ddc9f331-e6e9-4b6f-b7be-f8a614971655.png" width="300px" />

2022-05-10 17:10 UTC, alessandrojean commented
About the icons, please use [this tool](https://as280093.github.io/AndroidAssetStudio/icons-launcher.html) to generate, so it can have the same pattern as the other extensions. The current one has a higher border radius value.

2022-05-10 17:16 UTC, alessandrojean requested changes
Rest seems good :+1:

2022-05-10 17:16 UTC, alessandrojean commented on src/all/mangareaderto/src/eu/kanade/tachiyomi/extension/all/mangareaderto/MangaReader.kt
> +            GET("$baseUrl/search?keyword=$query&page=$page", headers)
It would be better to build the URL by using a dedicated class such as `HttpUrl` or `Uri`, since the user can type special characters and break the URL in the way it is now (simple concatenation).

```suggestion
            Uri.parse("$baseUrl/search").buildUpon().run {
                appendQueryParameter("keyword", query)
                appendQueryParameter("page", page.toString())
                
                GET(toString(), headers)
            }
```

2022-05-10 17:16 UTC, alessandrojean commented on src/all/mangareaderto/src/eu/kanade/tachiyomi/extension/all/mangareaderto/MangaReader.kt
> +            chapter_number = element.attr("data-number").toFloat()
```suggestion
            chapter_number = element.attr("data-number").toFloatOrNull() ?: -1f
```

2022-05-11 22:58 UTC, alessandrojean approved these changes

2022-05-11 23:34 UTC, merged