MangaSwat - Fixes #10318
tachiyomiorg/tachiyomi-extensions pull request #12113
Opened 2022-06-07 14:09 UTC by Saud-97

Fixes #10318

Solution was made by [@midou221](https://github.com/midou221)
https://github.com/tachiyomiorg/tachiyomi-extensions/issues/10318#issuecomment-1146591057

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2022-06-07 15:29 UTC, alessandrojean commented
Please ident using space characters instead of tabulation.

2022-06-07 21:25 UTC, alessandrojean requested changes

2022-06-08 04:31 UTC, Saud-97 commented on multisrc/overrides/wpmangastream/mangaswat/src/MangaSwat.kt
> +        for (element in elementsScript) {
Done

2022-06-08 05:02 UTC, alessandrojean approved these changes

2022-06-09 16:47 UTC, merged