feat: Add intent filter for mangasee
tachiyomiorg/tachiyomi-extensions pull request #12727
Opened 2022-07-25 10:04 UTC by suhan-paradkar

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

2022-07-25 19:05 UTC, alessandrojean requested changes
It seems you haven't added the `id:` handling on the base class, so it will not work.

Marking it as draft for now.

2022-07-25 19:05 UTC, alessandrojean commented on multisrc/overrides/nepnep/mangasee/src/MangaseeUrlActivity.kt
> +class IMHentaiUrlActivity : Activity() {
```suggestion
class MangaseeUrlActivity : Activity() {
```

2022-07-26 02:13 UTC, suhan-paradkar commented on multisrc/overrides/nepnep/mangasee/src/MangaseeUrlActivity.kt
> +class IMHentaiUrlActivity : Activity() {
Done!!

2022-07-26 02:15 UTC, suhan-paradkar commented
> It seems you haven't added the `id:` handling on the base class, so it will not work.
> 
> Marking it as draft for now.

Well..  I added it to the base class (I mean in the overrides)....

2022-07-26 02:29 UTC, alessandrojean requested changes

2022-07-26 02:29 UTC, alessandrojean commented on multisrc/overrides/nepnep/mangasee/src/MangaSee.kt
> +    }
Probably added a `}` as a mistake, so I fixed it. Check if it still works as expected.

```suggestion
override fun fetchSearchManga(page: Int, query: String, filters: FilterList): Observable<MangasPage> {
        if (query.startsWith("id:")) {
            val id = query.substringAfter("id:")
            return client.newCall(GET("$baseUrl/manga/$id/"))
                .asObservableSuccess() 
                .map { response ->
                    val manga = mangaDetailsParse(response) 
                    manga.url = "/manga/$id/" 
                    MangasPage(listOf(manga), false)
                }
        }
        
        return super.fetchSearchManga(page, query, filters)
    }
```

2022-07-26 16:44 UTC, alessandrojean approved these changes

2022-07-27 17:11 UTC, alessandrojean commented on multisrc/overrides/nepnep/mangasee/src/MangaSee.kt
> +override fun fetchSearchManga(page: Int, query: String, filters: FilterList): Observable<MangasPage> {
```suggestion
    override fun fetchSearchManga(page: Int, query: String, filters: FilterList): Observable<MangasPage> {
```

2022-07-27 17:17 UTC, alessandrojean commented
You need to fix some linting issues related to trailing spaces, otherwise the build will keep failing.

As a reference, they're listed below:

```
MangaseeUrlActivity.kt:2:1: Lint error > [no-trailing-spaces] Trailing space(s)
MangaseeUrlActivity.kt:9:1: Lint error > [no-trailing-spaces] Trailing space(s)
MangaseeUrlActivity.kt:25:1: Lint error > [no-trailing-spaces] Trailing space(s)
MangaseeUrlActivity.kt:34:1: Lint error > [no-trailing-spaces] Trailing space(s)
MangaseeUrlActivity.kt:39:1: Lint error > [no-trailing-spaces] Trailing space(s)
MangaseeUrlActivity.kt:40:1: Lint error > [no-consecutive-blank-lines] Needless blank line(s)
MangaSee.kt:23:39: Lint error > [no-trailing-spaces] Trailing space(s)
MangaSee.kt:25:60: Lint error > [no-trailing-spaces] Trailing space(s)
MangaSee.kt:26:46: Lint error > [no-trailing-spaces] Trailing space(s)
MangaSee.kt:30:1: Lint error > [no-trailing-spaces] Trailing space(s)
```

2022-08-02 03:15 UTC, stevenyomi commented
Just select `NepNepGenerator` config and run it once. It will format the code correctly.

![](https://user-images.githubusercontent.com/95685115/182284193-dd7bb398-ba73-4d11-989d-b6b2864606d7.png)

2022-08-02 12:35 UTC, suhan-paradkar commented
I guess it must pass CI by now......  I had it run through ktlint...

2022-08-06 21:29 UTC, merged