[RU]GroupLe pagination shift fix
tachiyomiorg/tachiyomi-extensions pull request #12836
Opened 2022-08-01 16:29 UTC by e-shl

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

2022-08-01 17:26 UTC, e-shl commented
What to "run"? I didn't touch him.

2022-08-02 03:07 UTC, stevenyomi requested changes

2022-08-02 03:07 UTC, stevenyomi commented on .run/GroupLeGenerator.run.xml
> -<component name="ProjectRunConfigurationManager">
You should not delete this file.

2022-08-02 09:28 UTC, stevenyomi requested changes

2022-08-02 09:28 UTC, stevenyomi commented on multisrc/overrides/grouple/selfmanga/src/SelfManga.kt
> +        val url = = super.searchMangaRequest(page, query, filters).url.newBuilder()
```suggestion
        val url = super.searchMangaRequest(page, query, filters).url.newBuilder()
```
This is causing lint error.

2022-08-02 09:33 UTC, stevenyomi commented on multisrc/overrides/grouple/selfmanga/src/SelfManga.kt
> +        val url = = super.searchMangaRequest(page, query, filters).url.newBuilder()
> Have tested the modifications by compiling and running the extension through Android Studio

Please make sure you did what you claimed to have done.

2022-08-05 13:20 UTC, merged