Add LittleGarden
tachiyomiorg/tachiyomi-extensions pull request #12885
Opened 2022-08-07 02:56 UTC by Sapphire-e

Closes #12626 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio

2022-08-07 15:10 UTC, arkon requested changes

2022-08-07 15:10 UTC, arkon commented on src/fr/littlegarden/src/eu/kanade/tachiyomi/extension/fr/littlegarden/LittleGarden.kt
> +        thumbnail_url = Regex("url\\((.*)\\)").find(element.select(".thumb").attr("style"))?.groupValues?.get(1)
You should use instances of the `Regex` objects rather than recreating it for every iteration. Comment applies for `Regex`s elsewhere too.

2022-08-07 15:10 UTC, arkon commented on src/fr/littlegarden/src/eu/kanade/tachiyomi/extension/fr/littlegarden/LittleGarden.kt
> +        thumbnail_url = null
Why?

2022-08-07 15:10 UTC, arkon commented on src/fr/littlegarden/src/eu/kanade/tachiyomi/extension/fr/littlegarden/LittleGarden.kt
> +        val requestBody = """{"operationName":"chapters","variables":{"slug":"$slug","order":-1,"limit":2000,"isAdmin":true},"query":"query chapters(${"$"}slug: String, ${"$"}limit: Float, ${"$"}skip
Some formatting to make this readable would be ideal.

2022-08-07 15:33 UTC, AntsyLich requested changes

2022-08-07 15:33 UTC, AntsyLich commented on src/fr/littlegarden/src/eu/kanade/tachiyomi/extension/fr/littlegarden/LittleGarden.kt
> +    private val cdnUrl = "https://littlexgarden.com/static/images/webp/"
make this a `const val`

2022-08-07 15:33 UTC, AntsyLich commented on src/fr/littlegarden/src/eu/kanade/tachiyomi/extension/fr/littlegarden/LittleGarden.kt
> +    override val lang = "fr"
the fact that it even has 1 entry from another language should mark it as "all"

2022-08-07 15:33 UTC, AntsyLich commented on src/fr/littlegarden/src/eu/kanade/tachiyomi/extension/fr/littlegarden/LittleGarden.kt
> +            emptyList()
should just return everything if query is null

2022-08-07 15:33 UTC, AntsyLich commented on src/fr/littlegarden/src/eu/kanade/tachiyomi/extension/fr/littlegarden/LittleGarden.kt
> +        val requestBody = """{"operationName":"chapters","variables":{"slug":"$slug","order":-1,"limit":2000,"isAdmin":true},"query":"query chapters(${"$"}slug: String, ${"$"}limit: Float, ${"$"}skip
should use `buildJsonObject` to make it look more clean

2022-08-08 05:30 UTC, Sapphire-e commented on src/fr/littlegarden/src/eu/kanade/tachiyomi/extension/fr/littlegarden/LittleGarden.kt
> +        thumbnail_url = null
I'm bad

2022-08-08 05:31 UTC, Sapphire-e commented
Everything should be fixed thanks to you and the other folks from the Discord

2022-08-09 19:26 UTC, merged