Update mangastic URL
tachiyomiorg/tachiyomi-extensions pull request #13003
Opened 2022-08-15 16:13 UTC by jeremie8

Mangastic switched to mangastic.me recently, updating the URL

Closes issues: #12696 #11879 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2022-08-15 16:51 UTC, CarlosEsco commented
need to add override code

2022-08-15 18:00 UTC, alessandrojean requested changes

2022-08-15 18:00 UTC, alessandrojean commented on multisrc/overrides/madara/mangastic/src/MangaStic.kt
> +package eu.kanade.tachiyomi.extension.en.ohnomanga
There's no need for an override file if you're not changing anything inside the class or passing any custom extra parameters in the constructor. You can safely delete this file.

2022-08-15 18:00 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> +        SingleLang("MangaStic", "https://mangastic.me", "en"),
```suggestion
        SingleLang("MangaStic", "https://mangastic.me", "en", overrideVersionCode = 1),
```

2022-09-01 20:16 UTC, alessandrojean commented
Closing due to inactivity. Feel free to open a new PR later with the changes requested.

2022-09-01 20:16 UTC, closed without merging