Manhwa latino
tachiyomiorg/tachiyomi-extensions pull request #13054
Opened 2022-08-17 20:11 UTC by lberoiza

Manhwa-Latino has changed the HTML Image-Attribute from src to data-src.

- The extension was updated
- The website has deactivate Cloudflare, it was deactivate from the extension to incremente the speed.

Best Regards, Tachiyomi-Team.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2022-08-17 20:48 UTC, alessandrojean commented on src/es/mahnwalatino/src/eu/kanade/tachiyomi/extension/es/manhwalatino/ManhwaLatino.kt
If you're not overriding the client you can safely remove this line IIRC.

2022-08-18 06:00 UTC, lberoiza commented on src/es/mahnwalatino/src/eu/kanade/tachiyomi/extension/es/manhwalatino/ManhwaLatino.kt
it is done, I removed the line of code.

2022-08-19 02:15 UTC, arkon requested changes

2022-08-19 02:15 UTC, arkon commented on src/es/mahnwalatino/src/eu/kanade/tachiyomi/extension/es/manhwalatino/MLConstants.kt
> +//    const val popularMangaNextPageSelector = "nav.navigation-ajax"
Just remove it if you don't need it anymore.

2022-08-19 02:15 UTC, arkon commented on src/es/mahnwalatino/src/eu/kanade/tachiyomi/extension/es/manhwalatino/ManhwaLatinoSiteParser.kt
> +        print("getMangaFromList")
Remove this.

2022-08-19 09:23 UTC, lberoiza commented on src/es/mahnwalatino/src/eu/kanade/tachiyomi/extension/es/manhwalatino/MLConstants.kt
> +//    const val popularMangaNextPageSelector = "nav.navigation-ajax"
Ok, it was removed

2022-08-19 09:24 UTC, lberoiza commented on src/es/mahnwalatino/src/eu/kanade/tachiyomi/extension/es/manhwalatino/ManhwaLatinoSiteParser.kt
> +        print("getMangaFromList")
I didn't saw that, Thanks.
I had removed it

2022-08-19 11:37 UTC, merged