Add some indonesian source's
tachiyomiorg/tachiyomi-extensions pull request #13077
Opened 2022-08-19 06:16 UTC by TheKingTermux

Detail:

- Add 8 New Source
> ManhwaLand #12621 `Status : Tested Pending`
> ManhwaList #10583  `Status : Tested Pending`
> Ryukonesia #11865  `Status : Tested Pending`
> Nekomik #12706  `Status : Tested Pending`
> ManhwaDesu #12524  `Status : Tested Pending`
> Mangayaro #12666  `Status : Tested` `CloudFlare Protected`
> LianScans #12939  `Status : Tested Pending`
> Dojing #13013  `Status : Tested Pending`

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

2022-08-19 23:51 UTC, alessandrojean requested changes

2022-08-19 23:51 UTC, alessandrojean commented on multisrc/overrides/wpmangastream/manhwalist/src/ManhwaList.kt
> +    private val rateLimitInterceptor = RateLimitInterceptor(4)
Use the provided `.rateLimit(4)` directly in the client builder instead.

2022-08-19 23:51 UTC, alessandrojean commented on multisrc/overrides/wpmangastream/nekomik/src/Nekomik.kt
> +    private val rateLimitInterceptor = RateLimitInterceptor(4)
Same here.

2022-08-19 23:51 UTC, alessandrojean commented on multisrc/overrides/wpmangastream/ryukonesia/src/Ryukonesia.kt
> +    private val rateLimitInterceptor = RateLimitInterceptor(4)
And here.

2022-08-20 00:18 UTC, TheKingTermux commented on multisrc/overrides/wpmangastream/manhwalist/src/ManhwaList.kt
> +    private val rateLimitInterceptor = RateLimitInterceptor(4)
Okay
I'm working on it

2022-08-20 00:18 UTC, TheKingTermux commented on multisrc/overrides/wpmangastream/nekomik/src/Nekomik.kt
> +    private val rateLimitInterceptor = RateLimitInterceptor(4)
Okay 👍🏻

2022-08-20 00:18 UTC, TheKingTermux commented on multisrc/overrides/wpmangastream/ryukonesia/src/Ryukonesia.kt
> +    private val rateLimitInterceptor = RateLimitInterceptor(4)
Okay 👍🏻

2022-08-20 00:28 UTC, TheKingTermux commented
Wait a minute, haven't WPMangaStream and WPMangaReader been combined into one in MangaThemesia theme?
But why does the WPMagaStream folder reappear?
Even though I deleted it 🤔

2022-08-20 03:47 UTC, stevenyomi commented
You really need to learn how to use [Git](https://git-scm.com/) properly.

2022-08-20 06:45 UTC, TheKingTermux commented
> You really need to learn how to use [Git](https://git-scm.com/) properly.

Yeah
I think so

2022-08-20 16:37 UTC, alessandrojean approved these changes

2022-08-20 20:38 UTC, merged