Pepper&Carrot: new extension
tachiyomiorg/tachiyomi-extensions pull request #13326
Opened 2022-09-02 18:54 UTC by ObserverOfTime

This is only the translations for now. I'll implement the requests tomorrow.

----

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

----

Closes #13308

2022-09-02 19:02 UTC, alessandrojean requested changes

2022-09-02 19:02 UTC, alessandrojean commented on src/all/peppercarrot/src/eu/kanade/tachiyomi/extension/all/peppercarrot/PepperCarrotFactory.kt
> +class PepperCarrotPT : PepperCarrot("pt")
It's actually `pt-BR` by looking at the text.

```suggestion
class PepperCarrotPT : PepperCarrot("pt-BR", "pt")
```

2022-09-02 22:28 UTC, ObserverOfTime commented
I found some time to implement the rest today after all but testing will have to wait till tomorrow.

I initially wanted to use the [API](https://framagit.org/peppercarrot/documentation/-/blob/master/130_API.md) but decided against it, though I might still use [this](https://www.peppercarrot.com/0_sources/ep01_Potion-of-Flight/lang/eo/info.json) to set the translators.

2022-09-02 22:28 UTC, ObserverOfTime commented on src/all/peppercarrot/src/eu/kanade/tachiyomi/extension/all/peppercarrot/PepperCarrotFactory.kt
> +class PepperCarrotPT : PepperCarrot("pt")
I think I'll keep it as `pt` since its `iso_locale` isn't specified [here](https://www.peppercarrot.com/0_sources/langs.json).

2022-09-02 22:48 UTC, alessandrojean commented on src/all/peppercarrot/src/eu/kanade/tachiyomi/extension/all/peppercarrot/PepperCarrotFactory.kt
> +class PepperCarrotPT : PepperCarrot("pt")
It's wrong there then, as it's clearly pt-BR and not pt.

2022-09-03 06:38 UTC, ObserverOfTime commented on src/all/peppercarrot/src/eu/kanade/tachiyomi/extension/all/peppercarrot/PepperCarrotFactory.kt
> +class PepperCarrotPT : PepperCarrot("pt")
Did you check all the chapters? It could be inconsistent since there's multiple translators.

2022-09-03 11:16 UTC, alessandrojean commented on src/all/peppercarrot/src/eu/kanade/tachiyomi/extension/all/peppercarrot/PepperCarrotFactory.kt
> +class PepperCarrotPT : PepperCarrot("pt")
I checked a few ones.

2022-09-03 11:39 UTC, alessandrojean commented on src/all/peppercarrot/src/eu/kanade/tachiyomi/extension/all/peppercarrot/PepperCarrotFactory.kt
> +class PepperCarrotPT : PepperCarrot("pt")
Checked all now, besides some silent chapters, all of them are indeed in pt-BR.

2022-09-03 11:48 UTC, ObserverOfTime commented on src/all/peppercarrot/src/eu/kanade/tachiyomi/extension/all/peppercarrot/PepperCarrotFactory.kt
> +class PepperCarrotPT : PepperCarrot("pt")
In that case, I'll submit a merge request upstream to fix it there first.

2022-09-03 11:51 UTC, alessandrojean commented on src/all/peppercarrot/src/eu/kanade/tachiyomi/extension/all/peppercarrot/PepperCarrotFactory.kt
> +class PepperCarrotPT : PepperCarrot("pt")
Can already fix it in thr extension since changing it later will requiring overriding the id because of possible existing users. Would be better to avoid that as much as we can.

2022-09-03 13:40 UTC, ObserverOfTime commented
It's basically ready now. Just waiting for my [upstream MR](https://framagit.org/peppercarrot/webcomics/-/merge_requests/869) to be reviewed.

2022-09-03 13:45 UTC, alessandrojean commented
Sure. Good they pinged the translators there, so we can have a confirmation about the locale. The translators words is what matters at the end.

2022-09-03 20:18 UTC, ObserverOfTime commented
Final (?) change: fetching the title & description instead of hardcoding them.
This way, they can be changed upstream without us having to update the extension.

This also means that the source name will be "Pepper&Carrot" in all languages.
Overriding the name *would* require an extension update and an `id` override if it's changed.

2022-09-04 11:32 UTC, CarlosEsco commented
So normally the implementation style you did here is the way to do it and preferred.  However it's a bit overkill since this is for one comic so am leaning towards the all in one approach that  @stevenyomi implemented.

2022-09-04 11:47 UTC, ObserverOfTime commented
Suit yourself.

2022-09-04 11:47 UTC, closed without merging