--> Add new features
tachiyomiorg/tachiyomi-extensions pull request #13494
Opened 2022-09-17 05:12 UTC by Mohamed-Ali-K

- **now you can switch in the extension setting between :**

     (this will affect the Latest button)  
    -show new Mangas 
    or 
    -show new chapters
   

1. **link manga status to tachiyomi native manga status**

**add additional information to description**
  -manga Scanlator status
  - manga start date
  - manga end Date
  - manga Alternative information

1. **add manga type to genre** 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2022-09-17 13:15 UTC, alessandrojean requested changes

2022-09-17 13:15 UTC, alessandrojean commented on src/ar/gmanga/src/eu/kanade/tachiyomi/extension/ar/gmanga/Gmanga.kt
> +                ).format(
Please make all DateTimeFormatter instances a constant in the class otherwise they will be recreated unnecessary a lot of times.

2022-09-17 14:49 UTC, alessandrojean requested changes

2022-09-17 14:49 UTC, alessandrojean commented on src/ar/gmanga/src/eu/kanade/tachiyomi/extension/ar/gmanga/Gmanga.kt
> +    private val parsedDatePattern = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss ZZZ zzz")
On a second thought, extensions runs on Android versions older than this too, so maybe better to use a compatible alternative like `SimpleDateFormat`. Sorry for not noticing that on the previous review.

2022-09-17 16:14 UTC, Mohamed-Ali-K commented on src/ar/gmanga/src/eu/kanade/tachiyomi/extension/ar/gmanga/Gmanga.kt
> +    private val parsedDatePattern = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss ZZZ zzz")
I am sorry too , I was taking a shortcut 🛩️ . but, i did change it. please review it again . thank you for your time

2022-09-17 22:33 UTC, alessandrojean approved these changes

2022-09-18 21:20 UTC, vetleledaal commented on src/ar/gmanga/build.gradle
> +    extVersionCode = 14
only increment this by 1
```suggestion
    extVersionCode = 12
```

2022-09-18 21:20 UTC, vetleledaal commented on src/ar/gmanga/src/eu/kanade/tachiyomi/extension/ar/gmanga/Gmanga.kt
> +        val data = json.decodeFromString<JsonObject>(
this is minor, but consider using kotlinx.serialization to build proper objects (DTOs) for parsing

2022-09-18 21:20 UTC, vetleledaal commented on src/ar/gmanga/src/eu/kanade/tachiyomi/extension/ar/gmanga/Gmanga.kt
> +                            "$description\n\n:$startedDayPrefix ᗏ \n$startedDate •"
Is this symbol "ᗏ" commonly used?

2022-09-18 21:45 UTC, Mohamed-Ali-K commented on src/ar/gmanga/src/eu/kanade/tachiyomi/extension/ar/gmanga/Gmanga.kt
> +                            "$description\n\n:$startedDayPrefix ᗏ \n$startedDate •"
no. not commonly used but it is one of Unicode characters according to wiki .
i can change it with "<". i test it with my European android phone.

2022-09-18 21:48 UTC, Mohamed-Ali-K commented on src/ar/gmanga/build.gradle
> +    extVersionCode = 14
done 👍

2022-09-18 21:56 UTC, Mohamed-Ali-K commented on src/ar/gmanga/src/eu/kanade/tachiyomi/extension/ar/gmanga/Gmanga.kt
> +        val data = json.decodeFromString<JsonObject>(
yeah .  
but I used what the extension's creator provide . I did not what to heavy change the extension . 
I just used what he provide and add features 😄

2022-09-18 23:10 UTC, vetleledaal approved these changes

2022-09-19 13:38 UTC, merged