Update Niceoppai.kt
tachiyomiorg/tachiyomi-extensions pull request #13506
Opened 2022-09-18 16:57 UTC by ponekub083

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

2022-09-18 16:59 UTC, alessandrojean commented
Please follow the checklist

> Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions

2022-09-19 01:20 UTC, ponekub083 commented
- [ t ]

2022-09-19 01:22 UTC, ponekub083 commented
> Please follow the checklist
> 
> > Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions

updated. thx

2022-09-19 03:15 UTC, Riztard requested changes
just remove if not being used

2022-09-19 03:16 UTC, Riztard commented on multisrc/overrides/madara/niceoppai/src/Niceoppai.kt
> +    // override fun latestUpdatesRequest(page: Int): Request = GET("$baseUrl/manga_list/all/any/last-updated/${pagePath(page)}", headers)
remove if unused

2022-09-19 03:17 UTC, Riztard commented on multisrc/overrides/madara/niceoppai/src/Niceoppai.kt
> +                // manga.url = manga.url.removePrefix("/manga")
remove if unused

2022-09-19 03:17 UTC, Riztard commented on multisrc/overrides/madara/niceoppai/src/Niceoppai.kt
> +
this too, remove if unused

2022-09-19 13:57 UTC, happywillow0 reviewed
For your awareness, the build check failed and the following should be changed:

MadaraGenerator.kt:356:67: Lint error > [comma-spacing] Missing spacing after ","
Niceoppai.kt:3:1: Lint error > [import-ordering] Imports must be ordered in lexicographic order without any empty lines in-between with "java", "javax", "kotlin" and aliases in the end
Niceoppai.kt:5:1: Lint error > [no-unused-imports] Unused import
Niceoppai.kt:7:1: Lint error > [no-unused-imports] Unused import
Niceoppai.kt:15:45: Lint error > [op-spacing] Missing spacing after "+"
Niceoppai.kt:19:1: Lint error > [no-blank-line-before-rbrace] Unexpected blank line(s) before "}"
Niceoppai.kt:22:45: Lint error > [op-spacing] Missing spacing after "+"
Niceoppai.kt:25:1: Lint error > [no-blank-line-before-rbrace] Unexpected blank line(s) before "}"
Niceoppai.kt:33:61: Lint error > [no-multi-spaces] Unnecessary space(s)

2022-09-19 14:00 UTC, alessandrojean commented
These would be likely pointed out during extension tests and building if Android Studio was used. Please do make use of it.

2022-09-20 02:22 UTC, ponekub083 commented
> 



> 

i will try

2022-09-22 13:22 UTC, ponekub083 commented
> These would be likely pointed out during extension tests and building if Android Studio was used. Please do make use of it like the checklist asks.

updated . run the extension on Android Studio

2022-09-22 13:25 UTC, stevenyomi commented
Find `MadaraGenerator` in the top right of Android Studio and run it once. It will format your code automatically.

2022-09-22 17:34 UTC, closed without merging