Add new niceoppai extention
tachiyomiorg/tachiyomi-extensions pull request #13552
Opened 2022-09-22 17:37 UTC by ponekub083

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2022-09-22 19:42 UTC, vetleledaal requested changes
Since you're moving from Madara you should remove the other resources (`./multisrc/overrides/madara/niceoppai/`), and the line in `MadaraGenerator.kt`

2022-09-22 19:42 UTC, vetleledaal commented on src/th/niceoppai/build.gradle
> +    extVersionCode = 1
```suggestion
    extVersionCode = 25
```
... to continue from the Madara version

2022-09-23 13:40 UTC, ponekub083 commented
@alessandrojean please review code and build extention for release to main apps.

2022-09-23 21:42 UTC, alessandrojean commented on src/th/niceoppai/build.gradle
> +    extVersionCode = 1
It's the same package name and classname so it should appear as an update. Please apply the changes suggested by Vetle.

2022-09-23 21:43 UTC, alessandrojean commented
The code is fine, just need to apply the changes suggested by Vetle so the new extension appears as an update to existing users.

2022-09-24 03:07 UTC, ponekub083 commented on src/th/niceoppai/build.gradle
> +    extVersionCode = 1
@alessandrojean @vetleledaal  thank you. it applied.

2022-09-24 10:17 UTC, vetleledaal approved these changes

2022-09-24 12:16 UTC, merged