Rewritten the entire extension to improve readability, speed and pave…
tachiyomiorg/tachiyomi-extensions pull request #13620
Opened 2022-09-28 16:07 UTC by sergiomalagon

… the way for future upgrades

Closes #12916

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2022-09-28 16:27 UTC, alessandrojean requested changes

2022-09-28 16:27 UTC, alessandrojean commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +        return client.newCall(
You can just return the GET directly, doesn't need to use the client for that at all.

2022-09-28 16:27 UTC, alessandrojean commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +            GET(
Same here and in other similar places.

2022-09-28 16:27 UTC, alessandrojean commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +        val mangaDataRequest = client.newCall(
Although it's acceptable, it's better to just return the request in the request methods and do additional network calls in the parse methods.

2022-09-28 16:27 UTC, alessandrojean commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +    override fun imageUrlParse(response: Response): String {
Alternatively you can just return a empty string since it won't even be called.

2022-09-28 16:32 UTC, alessandrojean requested changes

2022-09-28 16:32 UTC, alessandrojean commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +        val mangaData = JSONObject(mangaDataRequest.body!!.string())
Use kotlinx-serialization's `Json` instance please, since you're also using it with the DTOs. Don't use more than one parser.

Same for the other JSONObject usages.

2022-09-28 16:47 UTC, stevenyomi commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +            initialized = true
You can consider moving this to a `toSManga()` function inside `MangaDetails` and making the fields `private`. Same for other DTOs if applicable.

2022-09-28 16:56 UTC, stevenyomi commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +            initialized = true
You can consider moving this to a `toSManga()` function inside `MangaDetails` and making the fields `private`. Same for other DTOs if applicable.

2022-09-28 16:56 UTC, stevenyomi commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunFilters.kt
> +class ComickFunFilters() {
```suggestion
```

You don't need to wrap these with a class. Put them in the top level.

2022-09-28 16:56 UTC, stevenyomi commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunHelper.kt
> +class ComickFunHelper {
```suggestion
```
Same here.

2022-09-28 16:56 UTC, stevenyomi commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunHelper.kt
> +        }.toString()
```suggestion
        return buildString {
            if (vol.isNotEmpty()) {
                if (chap.isEmpty()) append("Volume $vol") else append("Vol. $vol")
            }
            if (chap.isNotEmpty()) {
                if (vol.isEmpty()) append("Chapter $chap") else append(", Ch. $chap")
            }
            if (title.isNotEmpty()) {
                if (chap.isEmpty()) append(title) else append(": $title")
            }
        }
```

2022-09-28 16:56 UTC, stevenyomi commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +                filters.forEach { it ->
You can move the filter parsing logic to a separate function in `ComickFunFilters.kt`.

2022-09-28 16:56 UTC, stevenyomi commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +                }.build().toString(),
```suggestion
                }.toString(),
```
Same for other builders.

Also, there's nothing to escape here, so you can just use string template.

2022-09-28 16:56 UTC, stevenyomi commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +                headers, CacheControl.FORCE_NETWORK
```suggestion
                headers
```
You don't need to force network unless the website's cache control is glitchy. Same for other places.

2022-09-28 16:56 UTC, stevenyomi commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +// TODO: Hacer una prueba de descargar un manga entero y que se pueda leer sin problemas
Please use English.

2022-09-28 17:35 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +        val mangaDataRequest = client.newCall(
This one has to be like that, I need chapter_count on the request

2022-09-28 17:54 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +// TODO: Hacer una prueba de descargar un manga entero y que se pueda leer sin problemas
Done

2022-09-28 17:54 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +                headers, CacheControl.FORCE_NETWORK
Done

2022-09-28 17:54 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +                }.build().toString(),
Done

2022-09-28 17:54 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunHelper.kt
> +        }.toString()
Done

2022-09-28 17:54 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunHelper.kt
> +class ComickFunHelper {
Done

2022-09-28 17:54 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunFilters.kt
> +class ComickFunFilters() {
Done

2022-09-28 17:55 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +        val mangaData = JSONObject(mangaDataRequest.body!!.string())
Done

2022-09-28 17:55 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +    override fun imageUrlParse(response: Response): String {
Done

2022-09-28 17:55 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +        val mangaDataRequest = client.newCall(
Done

2022-09-28 17:58 UTC, alessandrojean requested changes
Seems okay to me now, just do this missing change and it will be good.

2022-09-28 18:01 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
>                      SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZZZZ").parse(chapter.created_at)!!.time
You're talking about the function, right?

2022-09-28 18:08 UTC, alessandrojean commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
>                      SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZZZZ").parse(chapter.created_at)!!.time
No, the SimpleDateFormat instance, it should be a constant.

2022-09-28 18:15 UTC, AntsyLich commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +        if (result.chapters.isEmpty()) return listOf(SChapter.create())
Why are you returning a empty chapter? You are supposed to return a empty list

2022-09-28 18:15 UTC, AntsyLich commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +                chapter_number = if (chapter.chap.isEmpty()) 0F else chapter.chap.toFloat()
Don't assign a chapter number if one isn't provided. The app will handle it if you don't provide one.

2022-09-28 18:15 UTC, AntsyLich commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +                    if (chapter.group_name.isEmpty().not()) chapter.group_name[0] else "unknown"
```kt
chapter.group_name.joinToString().takeUnless { it.isBlank() }
```

2022-09-28 18:15 UTC, AntsyLich commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +                url = chapter.hid
Build a proper path don't just keep the id. Some fork has option to directly open chapter with WebView.

2022-09-28 18:15 UTC, AntsyLich commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +        return result.chapter.images.mapIndexed { index, data ->
You did this every time but if you are gonna use map or it's variant then no need to check if the list is empty and returning a empty list

2022-09-28 18:15 UTC, AntsyLich commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunFactory.kt
> -        "all",
Was "all" lang removed from site too? If not then keep it in tachi too

2022-09-28 18:31 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
>                      SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZZZZ").parse(chapter.created_at)!!.time
Done

2022-09-28 18:32 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +    HttpSource() {
Irrelevant, blame Android Studio Formatter

2022-09-28 18:33 UTC, stevenyomi commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +                url = chapter.hid
Should keep the old format if possible: `"${manga.url}/$hid-chapter-$chap-$iso639_1"` (read the deserializer code for meaning)

2022-09-28 18:33 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +        prettyPrint = true
Doesn't affect, I will remove it in future updates

2022-09-28 18:33 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +    }.build()
Irrelevant

2022-09-28 18:35 UTC, alessandrojean commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +    }.build()
The code suggested by Lich is much more readable.

2022-09-28 18:40 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunFactory.kt
> -        "all",
Not necessary, no one wants to open a manga and having 800+ chapters in every language

2022-09-28 18:42 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +    }.build()
Arguably, but it doesn't affect

2022-09-28 18:47 UTC, alessandrojean commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +    }.build()
Yeah, but readability is always appreciated.

2022-09-28 18:58 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +        prettyPrint = true
Done

2022-09-28 18:58 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +    }.build()
Done

2022-09-28 18:59 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +        if (result.chapters.isEmpty()) return listOf(SChapter.create())
Done

2022-09-28 18:59 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +                chapter_number = if (chapter.chap.isEmpty()) 0F else chapter.chap.toFloat()
Done

2022-09-28 18:59 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +                    if (chapter.group_name.isEmpty().not()) chapter.group_name[0] else "unknown"
Done

2022-09-28 18:59 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +        return result.chapter.images.mapIndexed { index, data ->
Done

2022-09-29 01:10 UTC, Riztard commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunFactory.kt
> -        "all",
some multi lang people might use it tho

2022-09-29 01:18 UTC, Riztard commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +    )
maybe put this in the correct order / near the previous one for better diff

2022-09-29 14:16 UTC, alessandrojean commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +                url = chapter.hid
Yeah, keep the old URL format, otherwise existing users will get a lot of "new" chapters when refreshing the library after the extension update.

2022-09-29 14:49 UTC, alessandrojean commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +                chapter_number = chapter.chap.toFloat()
What Lich said, but if you really really want to provide it, do it like this

```suggestion
                chapter_number = chapter.chap.toFloatOrNull() ?: -1f
```

2022-09-29 15:35 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +                chapter_number = chapter.chap.toFloat()
Done

2022-09-29 16:00 UTC, sergiomalagon commented
@alessandrojean I think it's all good now, let me know if I need to change anything more

2022-09-29 16:15 UTC, alessandrojean requested changes
Just found these two issues for now, rest (probably) should be fine.

2022-09-29 16:15 UTC, alessandrojean commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +                }.toString()
The chapter url should not contain the baseUrl. Also no need to use the Url builder as there are no query parameters to be sanitized and escaped.

```kotlin
url = "/comic/${mangaData.comic.slug}/${chapter.hid}-chapter-${chapter.chap}-$comickFunLang"
```

2022-09-29 16:15 UTC, alessandrojean commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +        val chapterHid = chapter.url.split("/").last().split("-").first()
You can do it like this to avoid splitting it.

```kotlin
val chapterHid = chapter.url.substringAfterLast("/").substringBefore("-")

2022-09-29 16:20 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +                }.toString()
Done

2022-09-29 16:20 UTC, sergiomalagon commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +        val chapterHid = chapter.url.split("/").last().split("-").first()
Done

2022-09-29 16:21 UTC, alessandrojean approved these changes

2022-09-29 17:16 UTC, merged