Komikindo.ID: fix HTTP error 404
tachiyomiorg/tachiyomi-extensions pull request #13721
Opened 2022-10-05 19:38 UTC by AhmadGhoni

closes https://github.com/tachiyomiorg/tachiyomi-extensions/issues/13687

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2022-10-05 19:42 UTC, alessandrojean requested changes

2022-10-05 19:42 UTC, alessandrojean commented on src/id/komiku/build.gradle
> +    extVersionCode = 6
Should be `15`.

```suggestion
    extVersionCode = 15
```

2022-10-05 19:42 UTC, alessandrojean commented on src/id/komikindoid/src/eu/kanade/tachiyomi/extension/id/komikindoid/KomikIndoID.kt
> +        val url = "$baseUrl/daftar-manga/page/$page/?".toHttpUrlOrNull()?.newBuilder()!!.addQueryParameter("title", query)
```suggestion
        val url = "$baseUrl/daftar-manga/page/$page/".toHttpUrlOrNull()!!.newBuilder()
            .addQueryParameter("title", query)
```

2022-10-05 19:51 UTC, AhmadGhoni commented
Sorry it looks like I got the build.gradle extension wrong, it should be KomikindoID

2022-10-05 20:46 UTC, merged

2022-10-05 22:24 UTC, TheKingTermux commented
Why did you change the ext VersionCode version in Komiku?
while in the KomikIndoID not?
Looks like you got it wrong in build.gradle

2022-10-06 02:15 UTC, AhmadGhoni commented
I'm looking at the wrong folder

> > build.gradle extension wrong
> 
> Why did you change the extVersionCode version in Komiku? [5284d94](https://github.com/tachiyomiorg/tachiyomi-extensions/commit/5284d946c7466fd91534167da6db7ae8c6d59b52) while in the KomikIndoID not? https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/src/id/komikindoid/build.gradle Looks like you got it wrong in build.gradle