Grmory mangas
tachiyomiorg/tachiyomi-extensions pull request #13744
Opened 2022-10-07 06:34 UTC by suyash01

Closes #13563

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2022-10-07 06:51 UTC, stevenyomi reviewed
You also need to use [this tool](https://as280093.github.io/AndroidAssetStudio/icons-launcher.html) to generate a square launcher icon to keep consistent.

2022-10-07 06:51 UTC, stevenyomi commented on multisrc/overrides/mangathemesia/gremorymangas/src/GremoryMangas.kt
> +        }
```suggestion
        return doOnNext { mangas.forEach(SManga::tempUrlToPermIfNeeded) }
```

2022-10-07 06:51 UTC, stevenyomi commented on multisrc/overrides/mangathemesia/gremorymangas/src/GremoryMangas.kt
> +        }
```suggestion
        return super.fetchChapterList(sManga).doOnNext {
            forEach { tempUrlToPermIfNeeded(sManga) }
        }
```

2022-10-07 06:51 UTC, stevenyomi commented on multisrc/overrides/mangathemesia/gremorymangas/src/GremoryMangas.kt
> +        val sMangaTitleFirstWord = this.title.split(" ")[0]
```suggestion
        val sMangaTitleFirstWord = this.title.substringBefore(' ')
```
Same for `SChapter.tempUrlToPermIfNeeded()`.

2022-10-07 06:51 UTC, stevenyomi commented on multisrc/overrides/mangathemesia/gremorymangas/src/GremoryMangas.kt
> +            }
The listeners are useless. You should remove them.

2022-10-07 06:51 UTC, stevenyomi commented on multisrc/overrides/mangathemesia/gremorymangas/src/GremoryMangas.kt
> +    }
You don't need to include `lang` in the key. The `SharedPreferences` key already includes source ID which is computed based on the language.

2022-10-07 06:51 UTC, stevenyomi commented on multisrc/overrides/mangathemesia/gremorymangas/src/GremoryMangas.kt
> +        private val TEMP_TO_PERM_URL_REGEX = Regex("""(/)\d+-""")
Is there a special reason to capture the first slash and use `$1` to replace? You can skip capturing that and just replace with `/`. Also you can prepend `^` if the substring must be the beginning (not sure about this).

2022-10-07 06:51 UTC, stevenyomi commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesiaGenerator.kt
> +        SingleLang("Gremory Mangas", "https://gremorymangas.com/", "es", overrideVersionCode = 1),
Put this line in the correct place according to the alphabet order.

2022-10-07 06:57 UTC, mobi2002 commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesiaGenerator.kt
> +        SingleLang("Gremory Mangas", "https://gremorymangas.com/", "es", overrideVersionCode = 1),
Since this is a new extension, and not a change to an existing extension, you don't really need `overrideVersionCode`
```suggestion
        SingleLang("Gremory Mangas", "https://gremorymangas.com/", "es"),
```

2022-10-07 07:53 UTC, suyash01 commented
> You also need to use [this tool](https://as280093.github.io/AndroidAssetStudio/icons-launcher.html) to generate a square launcher icon to keep consistent.

how do I get transparent background though? The tool always has a solid color selected.
Is keeping the background white fine?

2022-10-07 11:40 UTC, stevenyomi commented
> Is keeping the background white fine?

Yes.

2022-10-07 13:32 UTC, CarlosEsco commented
Marking draft until things are approved

2022-10-07 17:35 UTC, suyash01 commented
I have looked at more extension codes and figured that we don't need all that perma url logic

2022-10-07 18:33 UTC, stevenyomi commented on multisrc/overrides/mangathemesia/gremorymangas/src/GremoryMangas.kt
> +package eu.kanade.tachiyomi.extension.es.gremorymangas
You can remove this file as there's nothing special. It will be automatically generated on compile.

2022-10-07 18:57 UTC, suyash01 commented on multisrc/overrides/mangathemesia/gremorymangas/src/GremoryMangas.kt
> +package eu.kanade.tachiyomi.extension.es.gremorymangas
Removed the class, Thanks.

2022-10-08 01:48 UTC, alessandrojean requested changes

2022-10-08 01:48 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesiaGenerator.kt
> +        SingleLang("Gremory Mangas", "https://gremorymangas.com/", "es"),
Remove the trailing slash.

```suggestion
        SingleLang("Gremory Mangas", "https://gremorymangas.com", "es"),
```

2022-10-09 17:13 UTC, merged