Add MultiScr "ZeistManga" and DatGarScan
tachiyomiorg/tachiyomi-extensions pull request #14491
Opened 2022-12-07 10:28 UTC by seew3l

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

Closes #14207

2022-12-07 11:53 UTC, AntsyLich commented
Use `ParsedHttpSource` since you are parsing htmls. Also use Dtos when parsing json

2022-12-07 22:24 UTC, seew3l commented
I think it's ready

2022-12-08 06:18 UTC, vetleledaal commented
Consider this an opinionated refactor https://gist.github.com/vetleledaal/708918ea8054ee7c4a88a1b121b3259a, didn't want to spam reviews here as the diff is quite large.

There's still some duplicated code, or weird non-standard ways of doing things. Thumbnails are weirdly lowres, and there appears to be lacking pagination support. Could be something to investigate for later.

2022-12-09 01:34 UTC, alessandrojean requested changes

2022-12-09 01:34 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/zeistmanga/ZeistMangaDto.kt
> +    @SerialName("feed") val feed: ZeistMangaFeedDto? = null,
These attributes with the `@SerialName` that are exactly equal to the attribute name in the class can be removed.

Take this as an example:

```suggestion
    val feed: ZeistMangaFeedDto? = null,
```

2022-12-09 01:34 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/zeistmanga/ZeistMangaDto.kt
> +        chapter_number = this@ZeistMangaEntryDto.title.t.trim().substringAfterLast(" ").toFloat()
This will fall if the title doesn't contain a valid number. You don't necessarily need to set this as the app will try to parse the chapter name and get the chapter number automatically. If you fell you really need to set it, do like this:

```suggestion
        chapter_number = this@ZeistMangaEntryDto.title.t.trim().substringAfterLast(" ").toFloatOrNull() ?: -1f
```

2022-12-09 01:34 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/zeistmanga/ZeistMangaDto.kt
> +        date_upload = SimpleDateFormat("yyyy-MM-dd", Locale.getDefault()).parse(chapterDate)?.time ?: 0
Make the SimpleDateFormat a constant, otherwise it will be recreated for every chapter. Also wrap it with a `runCatching` or with a `try-catch` like in the example in the CONTRIBUTING.md guide, as it can throw Exceptions if the parsing fails.

2022-12-09 01:34 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/zeistmanga/ZeistMangaDto.kt
> +    }
```suggestion
    private fun getChapterLink(list: List<ZeistMangaEntryLink>): String {
        return list.first { it.rel == "alternate" }
    }
```

2022-12-09 02:15 UTC, alessandrojean approved these changes

2022-12-11 13:08 UTC, merged