Fix No results found iutruyentranh
tachiyomiorg/tachiyomi-extensions pull request #14563
Opened 2022-12-15 14:36 UTC by dejavui

Checklist:
Closes #11389
- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

2022-12-16 00:27 UTC, alessandrojean requested changes

2022-12-16 00:27 UTC, alessandrojean commented on src/vi/iutruyentranh/src/eu/kanade/tachiyomi/extension/vi/iutruyentranh/IuTruyenTranh.kt
> +                    throw Exception("ID tìm kiếm không hợp lệ.")
It's better to return an `Observable.error` in this case I guess.

2022-12-16 00:27 UTC, alessandrojean commented on src/vi/iutruyentranh/src/eu/kanade/tachiyomi/extension/vi/iutruyentranh/IuTruyenTranh.kt
> +        baseUrl.toHttpUrl().newBuilder().apply {
No need to build manually the URL here and in some other places, you can use simple string interpolation.

2022-12-16 00:27 UTC, alessandrojean commented on src/vi/iutruyentranh/src/eu/kanade/tachiyomi/extension/vi/iutruyentranh/IuTruyenTranh.kt
> +            addPathSegment("search.php")
Here you can keep the URL building as the filters are dynamic and can create a lot of query parameters.

2022-12-16 10:12 UTC, dejavui commented on src/vi/iutruyentranh/src/eu/kanade/tachiyomi/extension/vi/iutruyentranh/IuTruyenTranh.kt
> +                    throw Exception("ID tìm kiếm không hợp lệ.")
ext iutruyentranh search manga is the same ext truyentranh8

2022-12-20 13:47 UTC, alessandrojean requested changes
There's also a build error, please fix it.

2022-12-20 13:47 UTC, alessandrojean commented on src/vi/iutruyentranh/src/eu/kanade/tachiyomi/extension/vi/iutruyentranh/IuTruyenTranh.kt
>      }
Literally no need at all to do that... Just do like this

```kotlin
return GET("$baseUrl/search.php?act=search&andor=and&sort=xem&view=thumb&page=$page", headers)
```

Same to other similar instances.

2022-12-20 13:47 UTC, alessandrojean commented on src/vi/iutruyentranh/src/eu/kanade/tachiyomi/extension/vi/iutruyentranh/IuTruyenTranh.kt
> +                    throw Exception("ID tìm kiếm không hợp lệ.")
Being the same doesn't mean it's correct.

2022-12-20 15:46 UTC, closed without merging