fix reaperscans image links
tachiyomiorg/tachiyomi-extensions pull request #14813
Opened 2023-01-05 21:12 UTC by AriaMoradi

closes #14248
closes #13936

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2023-01-05 21:47 UTC, alessandrojean requested changes

2023-01-05 21:47 UTC, alessandrojean commented on src/en/reaperscans/src/eu/kanade/tachiyomi/extension/en/reaperscans/ReaperScans.kt
> +            val imageSrc = element.attr("src")!!
Can just use `attr("abs:src")` instead.

2023-01-05 23:52 UTC, alessandrojean approved these changes

2023-01-06 05:28 UTC, ArjixWasTaken commented
+1

2023-01-06 13:29 UTC, merged