ComickFun: Updated API address and fixed error when API returns no url for a page
tachiyomiorg/tachiyomi-extensions pull request #14842
Opened 2023-01-07 22:28 UTC by buhbbl

Fixes and Closes #14786.
Addresses #14788 by changing the API URL.

The slug and hid changes in #14788 have not been addressed in this PR.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2023-01-08 12:51 UTC, buhbbl commented
Implemented the use of the new search API endpoint which should address the issue #14668.

Further updated to now address the deprecated API calls. 

But will need to be re-visited once ext-lib 1.4 is released as currently the app will store the slugs in the url property instead of the hid which will cause issues if the slugs are changed.

2023-01-08 14:04 UTC, alessandrojean requested changes

2023-01-08 14:04 UTC, alessandrojean commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +            JSONObject(response.body?.string() ?: "").getString(mangaSlug)
Use kotlinx.serialization instead, replace the usages of `org.json` with the `json` instance you already have available in the class.

2023-01-08 16:21 UTC, buhbbl commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +            JSONObject(response.body?.string() ?: "").getString(mangaSlug)
Need to use parseToJsonElement instead of using Dto as the API does not have a defined structure. 

Will update it.

2023-01-08 16:22 UTC, alessandrojean commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +            JSONObject(response.body?.string() ?: "").getString(mangaSlug)
No problem in using the kotlinx.serialization's JsonElement if it's the case 👍🏻

2023-01-08 16:23 UTC, alessandrojean approved these changes

2023-01-10 18:54 UTC, alessandrojean requested changes

2023-01-10 18:54 UTC, alessandrojean commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +    private fun slugMapRequest(mangaSlug: String): String {
Better to rename the method as it's not returning a request, it's rather fetching data.

```kotlin
private fun findCurrentSlug(oldSlug: String): String {
```

2023-01-10 23:08 UTC, buhbbl commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFun.kt
> +    private fun slugMapRequest(mangaSlug: String): String {
got it

2023-01-10 23:34 UTC, merged