QManga
tachiyomiorg/tachiyomi-extensions pull request #14867
Opened 2023-01-09 12:42 UTC by beerpiss

Closes #14745

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2023-01-09 12:56 UTC, AntsyLich requested changes

2023-01-09 12:56 UTC, AntsyLich commented on src/vi/qmanga/AndroidManifest.xml
> +			android:name="eu.kanade.tachiyomi.extension.vi.qmanga.QMangaUrlActivity"
Too much indents

2023-01-09 12:56 UTC, AntsyLich commented on src/vi/qmanga/src/eu/kanade/tachiyomi/extension/vi/qmanga/QManga.kt
> +class QManga : HttpSource() {
Use `ParsedHttpSource`

2023-01-09 17:02 UTC, beerpiss commented on src/vi/qmanga/src/eu/kanade/tachiyomi/extension/vi/qmanga/QManga.kt
> +class QManga : HttpSource() {
`popularMangaParse`, `latestUpdatesParse`, `searchMangaParse` all parse the same way. I intentionally used `HttpSource` to make it shorter and to not repeat a bunch of code.

2023-01-10 18:55 UTC, alessandrojean requested changes

2023-01-10 18:55 UTC, alessandrojean commented on src/vi/qmanga/AndroidManifest.xml
> +	xmlns:android="http://schemas.android.com/apk/res/android"
As Lich said, fix the indentation and replace the tabs by spaces.

2023-01-11 17:34 UTC, merged