Add MangaXY
tachiyomiorg/tachiyomi-extensions pull request #14870
Opened 2023-01-09 17:58 UTC by dejavui

Checklist:

- [ ] Have tested the modifications by compiling and running the extension through Android Studio

2023-01-09 23:36 UTC, beerpiss commented on src/vi/mangaxy/src/eu/kanade/tachiyomi/extension/vi/MangaXY/MangaXY.kt
> +    }
```suggestion
    override fun latestUpdatesFromElement(element: Element): SManga = popularMangaFromElement(element)
```
they are the same so why not

2023-01-09 23:36 UTC, beerpiss commented on src/vi/mangaxy/src/eu/kanade/tachiyomi/extension/vi/MangaXY/MangaXY.kt
> +                    .map { MangasPage(listOf(it), false) }
Add the URL to the returned `SManga` since `fetchMangaDetails` doesn't do that.

2023-01-10 18:57 UTC, alessandrojean commented
Use the icon generator tool linked in the CONTRIBUTING.md file. The one in this PR uses a different pattern from the one used in all other extensions in the repository,

2023-01-10 19:02 UTC, alessandrojean requested changes

2023-01-10 19:02 UTC, alessandrojean commented on src/vi/mangaxy/src/eu/kanade/tachiyomi/extension/vi/MangaXY/MangaXY.kt
> +    )
```suggestion
    override fun popularMangaRequest(page: Int) = GET(
        "$baseUrl/search.php".toHttpUrl().newBuilder()
            .addQueryParameter("act", "search")
            .addQueryParameter("sort", "xem")
            .addQueryParameter("view", "thumb")
            .addQueryParameter("page", page.toString())
            .toString(),
        headers
    )

```

2023-01-10 19:02 UTC, alessandrojean commented on src/vi/mangaxy/src/eu/kanade/tachiyomi/extension/vi/MangaXY/MangaXY.kt
> +            addPathSegment("search.php")
Same here, include the "search.php" part in the String and make it more readable.

2023-01-10 19:02 UTC, alessandrojean commented on src/vi/mangaxy/src/eu/kanade/tachiyomi/extension/vi/MangaXY/MangaXY.kt
> +            addPathSegment("search.php")
Same here, can add the "search.php" to the `baseUrl.toHttpUrl()` part directly.

2023-01-10 19:02 UTC, alessandrojean commented on src/vi/mangaxy/src/eu/kanade/tachiyomi/extension/vi/MangaXY/MangaXY.kt
> +    private val dateFormat = SimpleDateFormat("yyyy-MM-dd HH:mm:ss", Locale.US).apply {
Put a blank line between the methods, it makes the readability better.

2023-01-10 19:02 UTC, alessandrojean commented on src/vi/mangaxy/src/eu/kanade/tachiyomi/extension/vi/MangaXY/MangaXY.kt
> +            Page(i, "", img.attr("abs:src"))
```suggestion
            Page(i, imageUrl = img.attr("abs:src"))
```

2023-01-10 19:02 UTC, alessandrojean commented on src/vi/mangaxy/src/eu/kanade/tachiyomi/extension/vi/MangaXY/MangaXY.kt
> +
Remove this empty line.

2023-01-11 13:45 UTC, alessandrojean commented on src/vi/mangaxy/src/eu/kanade/tachiyomi/extension/vi/MangaXY/MangaXY.kt
> +        chapter_number = if (name.lowercase().startsWith("vol")) {
Unless it's extremely necessary, you really don't need to set this, the app already have a chapter number recognition algorithm.

2023-01-11 14:59 UTC, dejavui commented on src/vi/mangaxy/src/eu/kanade/tachiyomi/extension/vi/MangaXY/MangaXY.kt
> +        chapter_number = if (name.lowercase().startsWith("vol")) {
> Unless it's extremely necessary, you really don't need to set this, the app already have a chapter number recognition algorithm.

Ok. I removed it because it was not so necessary.

2023-01-11 15:02 UTC, alessandrojean approved these changes

2023-01-11 17:34 UTC, merged