Adding New Source To Madara
tachiyomiorg/tachiyomi-extensions pull request #15123
Opened 2023-01-26 23:43 UTC by rashid19961

Checklist:
This Closes #15079 

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2023-01-26 23:47 UTC, rashid19961 commented
Is it possible to delte the other stuff couldn't delete them from my side

2023-01-27 00:00 UTC, alessandrojean requested changes
Also you're adding extra icons for another extension that doesn't exist anymore, remove them from this PR.

2023-01-27 00:02 UTC, alessandrojean commented
You can properly delete stuff if you use Git (through terminal or by the desktop client) instead of using the website directly. Follow the CONTRIBUTING.md guide.

2023-01-27 10:59 UTC, M-Cry reviewed
Tested the pull, everything works with the given suggestions

2023-01-27 10:59 UTC, M-Cry commented on multisrc/overrides/madara/falconmangaar/src/FalconMangaAr.kt
> +/* ktlint-disable */
```suggestion

```

Tested works fine without

2023-01-27 10:59 UTC, M-Cry commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> +        SingleLang("فالكون مانجا", "https://falconmanga.com/", "ar", className = "FalconMangaAr"),
```suggestion
        SingleLang("فالكون مانجا", "https://falconmanga.com", "ar", className = "FalconMangaAr"),
```

No need for trailling "/"

2023-01-27 10:59 UTC, M-Cry commented on multisrc/overrides/madara/falconmangaar/src/FalconMangaAr.kt
> +class FalconMangaAr : Madara("فالكون مانجا", "https://falconmanga.com/", "ar")
```suggestion
class FalconMangaAr : Madara("فالكون مانجا", "https://falconmanga.com", "ar")
```

No need for trailling "/"

2023-01-27 12:08 UTC, alessandrojean commented on multisrc/overrides/madara/falconmangaar/src/FalconMangaAr.kt
> +/* ktlint-disable */
That's not the issue. The override file doesn't override anything really, so it's completely useless as it's the same thing that will be auto generated in the build process. It can be removed.

2023-01-27 12:08 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> +        SingleLang("فالكون مانجا", "https://falconmanga.com/", "ar", className = "FalconMangaAr"),
Good catch, need fix this as well.

2023-01-29 15:57 UTC, alessandrojean commented
Closing due to inactivity.

2023-01-29 15:57 UTC, closed without merging