Hiperdex baseUrl option
tachiyomiorg/tachiyomi-extensions pull request #15303
Opened 2023-02-10 21:29 UTC by Basara-Hatake

Closes #15302

Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [X] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [X] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [X] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio

2023-02-10 22:51 UTC, stevenyomi requested changes
I know you're copying the code from another extension, but here are the issues. Either fix them for this extension, or fix for both/all extensions.

2023-02-10 22:51 UTC, stevenyomi commented on multisrc/overrides/madara/hiperdex/src/Hiperdex.kt
> +        private val BASE_URL_PREF = "overrideBaseUrl_v${AppInfo.getVersionName()}"
This won't work as expected because `AppInfo.getVersionName()` returns the app's version name.

2023-02-10 22:51 UTC, stevenyomi commented on multisrc/overrides/madara/hiperdex/src/Hiperdex.kt
> +        val baseUrlPref = androidx.preference.EditTextPreference(screen.context).apply {
Not sure if a list preference is better here.

2023-02-10 22:51 UTC, stevenyomi commented on multisrc/overrides/madara/hiperdex/src/Hiperdex.kt
> +            key = BASE_URL_PREF_TITLE
```suggestion
            key = BASE_URL_PREF
```

2023-02-10 22:51 UTC, stevenyomi commented on multisrc/overrides/madara/hiperdex/src/Hiperdex.kt
> +                    val res = preferences.edit().putString(BASE_URL_PREF, newValue as String).commit()
This line is not needed. To eliminate the whole change listener thing, put the restart prompt in the summary.

2023-02-10 22:51 UTC, stevenyomi commented on multisrc/overrides/madara/hiperdex/src/Hiperdex.kt
> +        super.setupPreferenceScreen(screen)
I don't think there is a super implementation of this. Same applies to the edit to EmpireWebtoon.

2023-02-11 10:35 UTC, stevenyomi commented on multisrc/overrides/madara/hiperdex/src/Hiperdex.kt
> +        super.setupPreferenceScreen(screen)
Then remove `ConfigurableSource` from the class declaration, as Madara already implements it.

2023-02-11 19:09 UTC, Basara-Hatake commented on multisrc/overrides/madara/hiperdex/src/Hiperdex.kt
> +        private val BASE_URL_PREF = "overrideBaseUrl_v${AppInfo.getVersionName()}"
how do i get the extension version code then

2023-02-11 19:12 UTC, Basara-Hatake commented on multisrc/overrides/madara/hiperdex/src/Hiperdex.kt
> +        val baseUrlPref = androidx.preference.EditTextPreference(screen.context).apply {
list preference doesnt make any sense

2023-02-11 19:13 UTC, Basara-Hatake commented on multisrc/overrides/madara/hiperdex/src/Hiperdex.kt
> +                    val res = preferences.edit().putString(BASE_URL_PREF, newValue as String).commit()
the restart toast is done everywhere like this

2023-02-11 19:25 UTC, stevenyomi commented on multisrc/overrides/madara/hiperdex/src/Hiperdex.kt
> +                    val res = preferences.edit().putString(BASE_URL_PREF, newValue as String).commit()
I'm referring to the `edit()` line. That line is not needed.

Removing that line causes the change listener to only do the toast thing. TBH toasts are easy neglected, so putting the prompt into summary is a good idea.

2023-02-11 19:28 UTC, stevenyomi commented
According to the original issue, the URL of this site just jumps back and forth between two alternatives. I doubt if a list/switch preference to choose from, or even better, automatic detection without settings is better.

2023-02-11 19:29 UTC, stevenyomi commented on multisrc/overrides/madara/hiperdex/src/Hiperdex.kt
> +        private val BASE_URL_PREF = "overrideBaseUrl_v${AppInfo.getVersionName()}"
Use `BuildConfig.VERSION_CODE` and make sure it's a `private const val`. Your IDE might complain not finding it, but it's generated on build and will pass the build.

2023-02-11 19:30 UTC, stevenyomi commented on multisrc/overrides/madara/hiperdex/src/Hiperdex.kt
> +        private val BASE_URL_PREF = "overrideBaseUrl_v${AppInfo.getVersionName()}"
Also make sure your import line is `import eu.kanade.tachiyomi.extension.BuildConfig` otherwise it will be something else.

2023-02-11 20:06 UTC, stevenyomi commented on multisrc/overrides/madara/hiperdex/src/Hiperdex.kt
> +                    val res = preferences.edit().putString(BASE_URL_PREF, newValue as String).commit()
```suggestion
```

This line still needs to be removed.

2023-02-12 18:27 UTC, merged