fix japanread source
tachiyomiorg/tachiyomi-extensions pull request #15361
Opened 2023-02-15 04:43 UTC by Adam935

Creation/modification of the japanread source which became bentomanga

I left the name and the image because it's the same source with a new interface and name (people know japanread).
I don't know why but changing extVersionCode causes the build to fail !

![image](https://user-images.githubusercontent.com/50600860/218932316-c0183a11-5dc2-4ed2-9c7b-c6fd5acbe7b8.png)
![image](https://user-images.githubusercontent.com/50600860/218932380-67b4e628-d5e2-4cdd-b44a-1e459cb04269.png)

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

2023-02-15 10:58 UTC, alessandrojean commented
Change the extName, the class name and the name attribute (but keep the old id, there's a whole section in the contributing guide about it), but keep the same package name. Also do bump the extVersionCode so users receive an update.

The repository was updated to extensions-lib 1.4 these days, try syncing your branch with the most recent commits and sync Gradle.

2023-02-15 11:01 UTC, alessandrojean requested changes
I'm guessing your branch is out of date with the Jsoup and OkHttp version changes, so that's why AS is not complaining about some nullability changes. Try doing what I suggested earlier and sync your branch with master.

2023-02-15 11:01 UTC, alessandrojean commented on src/fr/japanread/src/eu/kanade/tachiyomi/extension/fr/japanread/Japanread.kt
> +        val jsonData = apiResponse.body!!.string()
body is not nullable anymore, can remove the `!!`

2023-02-15 11:01 UTC, alessandrojean commented on src/fr/japanread/src/eu/kanade/tachiyomi/extension/fr/japanread/Japanread.kt
> +        val jsonResult = json.parseToJsonElement(apiResponse.body!!.string()).jsonObject
Same here and in other places.

2023-02-15 11:01 UTC, alessandrojean commented on src/fr/japanread/src/eu/kanade/tachiyomi/extension/fr/japanread/Japanread.kt
> +    /*
If you're not using these filters anymore, remove them instead of letting it commented.

2023-02-16 09:47 UTC, alessandrojean commented on src/fr/japanread/build.gradle
> +    extName = 'bentomanga'
```suggestion
    extName = 'Bento Manga'
```

2023-02-16 09:48 UTC, alessandrojean commented on src/fr/japanread/src/eu/kanade/tachiyomi/extension/fr/japanread/bentomanga.kt
> +class bentomanga : ParsedHttpSource() {
Class names should start with uppercase.

```suggestion
class BentoManga : ParsedHttpSource() {
```

Rename the file to `BentoManga.kt` as well.

2023-02-16 09:48 UTC, alessandrojean commented on src/fr/japanread/src/eu/kanade/tachiyomi/extension/fr/japanread/bentomanga.kt
> +    override val name = "bentomanga"
```suggestion
    override val name = "Bento Manga"
```

2023-02-17 01:09 UTC, Adam935 commented
mb I completely forgot the letter maj at the beginning (●'◡'●)

2023-02-17 03:14 UTC, seew3l commented
You forgot to rename the file to `BentoManga.kt`

2023-02-17 06:05 UTC, Adam935 commented
> You forgot to rename the file to `BentoManga.kt`

mb i will, life sucks(❁´◡`❁)

2023-02-17 06:24 UTC, Adam935 commented
hope all is fine now

2023-02-17 11:26 UTC, alessandrojean approved these changes

2023-02-18 15:31 UTC, merged