New source: Pixiv
tachiyomiorg/tachiyomi-extensions pull request #15387
Opened 2023-02-17 19:23 UTC by Solitai7e

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] ~~Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions~~
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] ~~Have explicitly kept the `id` if a source's name or language were changed~~
- [x] Have tested the modifications by compiling and running the extension through Android Studio

Closes #13452 (?)

2023-02-17 19:47 UTC, alessandrojean commented
A few things you can do to make the code legibility better is using DTOs instead of accessing the JSON elements like maps. Also please use the icon generator tool linked in the CONTRIBUTING.md guide, as this one differs from the pattern adapted by the other extensions in the repository.

2023-02-18 15:21 UTC, alessandrojean requested changes
I suggested some things to fix a few issues, but overall it looks okay.

2023-02-18 15:21 UTC, alessandrojean commented on src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Common.kt
> +    url = "$BASE_URL/artworks/${artwork.id}"
Should not include the baseURL in the `url` fields to prevent future issues if ever the source changes their URL.

```suggestion
    url = "/artworks/${artwork.id}"
```

2023-02-18 15:21 UTC, alessandrojean commented on src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Common.kt
> +    url = "$BASE_URL/artworks/${result.id}"
```suggestion
    url = "/artworks/${result.id}"
```

2023-02-18 15:21 UTC, alessandrojean commented on src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Pixiv.kt
> +    override fun getChapterUrl(chapter: SChapter): String = chapter.url
Should add the `getMangaUrl` as well, as by default it calls `mangaDetailsRequest` and it will throw an exception. I also included the `baseUrl` in the methods as a follow-up to the first change request.

```suggestion
    override fun getMangaUrl(manga: SManga): String = baseUrl + manga.url

    override fun getChapterUrl(chapter: SChapter): String = baseUrl + chapter.url
```

2023-02-18 15:21 UTC, alessandrojean commented on src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Common.kt
> +    illustIdRegex.find(url)?.groupValues?.get(1)?.toInt()
Can just use `substringAfterLast("/")`.

2023-02-18 15:37 UTC, Solitai7e commented
ok I'm really really really sorry to be asking this but would it be fine if I moved things around again cause I'm only now realizing how stupid some of the changes I made in the last 10 or so pushes are

2023-02-18 15:46 UTC, alessandrojean commented
No problem at all as long you follow the suggestions, but consider using a branch next time and do through commits.

2023-02-18 20:41 UTC, alessandrojean requested changes
A few more suggestions. And answering your question in the previous commit, yes, everything will be squashed when merged.

2023-02-18 20:41 UTC, alessandrojean commented on src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Pixiv.kt
> +    runCatching { dateFormat.parse(string)?.time!! }.getOrDefault(0)
Move these to inside the `Pixiv` class.

2023-02-18 20:41 UTC, alessandrojean commented on src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Pixiv.kt
> +            throw RuntimeException(response.message)
Throw just a regular `Exception` here and in other places where `RuntimeException` is being used, should be fine.

2023-02-18 20:41 UTC, alessandrojean commented on src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Pixiv.kt
> +            .asSequence()
You don't need to make it a sequence. It's also better to handle nullability as well.

```kotlin
val mangas = (results.manga ?: results.illustManga)?.data.orEmpty()
```

2023-02-18 20:41 UTC, alessandrojean commented on src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Pixiv.kt
> +            .toList()
Can remove this as it will not be a sequence anymore.

2023-02-18 20:41 UTC, alessandrojean commented on src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Pixiv.kt
> +            .toList()
```suggestion
        val popularResult = results.popular
        val mangas = (popularResult?.recent.orEmpty() + popularResult?.permanent.orEmpty())
            .map(::searchResultParse)
```

2023-02-18 20:41 UTC, alessandrojean commented on src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Pixiv.kt
> +        genre = illust.tags?.tags?.mapNotNull { it.tag }?.joinToString()
This one is just a suggestion, following it or not is up to you.

```suggestion
        genre = illust.tags?.tags.orEmpty()
            .filterNotNull { it.tag }
            .joinToString { it.tag }
```

2023-02-18 20:41 UTC, alessandrojean commented on src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Pixiv.kt
> +private val dateFormat by lazy { SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss", Locale.JAPAN) }
There's nothing in Japanese in the pattern, so better to change it to `Locale.ENGLISH` or `Locale.US`.

```suggestion
private val dateFormat by lazy { SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss", Locale.ENGLISH) }
```

2023-02-18 20:41 UTC, alessandrojean commented on src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Pixiv.kt
> +    private fun ajax(method: String, path: String, params: Map<String, String> = emptyMap()): Request {
Technically, the extension doesn't do any AJAX requests, so better to rename this method.

```suggestion
    private fun apiRequest(method: String, path: String, params: Map<String, String> = emptyMap()): Request {
```

2023-02-18 20:41 UTC, alessandrojean commented on src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Pixiv.kt
> +    private inline fun <reified T> ajaxParse(response: Response): T {
Same here.

```suggestion
    private inline fun <reified T> apiResponseParse(response: Response): T {
```

2023-02-19 16:22 UTC, alessandrojean approved these changes

2023-02-19 17:01 UTC, merged