Tachidesk (Suwayomi): Implement search
tachiyomiorg/tachiyomi-extensions pull request #15466
Opened 2023-02-24 19:21 UTC by Sirver51

Closes #14167

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Have not changed source names
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2023-02-24 19:29 UTC, jobobby04 commented
Why are you filtering in searchMangaRequest and not searchMangaParse? You could add the query into the request as a query parameter and grab it in the parse, and do the parsing in the background instead of blocking the UI by doing it in the request.

2023-02-24 20:26 UTC, alessandrojean commented
Yeah, don't do any network calls on the `request` methods, they're supposed to only return the Request that will be done by the `fetch` methods.

2023-02-25 06:38 UTC, Sirver51 commented
Welp, I feel silly now; doing what you said reduces the amount of data being passed in the request and obviates the need for overriding fetchSearchManga. Should have caught that, my bad.

2023-02-25 13:17 UTC, alessandrojean requested changes

2023-02-25 13:17 UTC, alessandrojean commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +                        GZIPInputStream(categoryMangaListResponse.body.byteStream())
Can't you just use `response.body.string()`? I think OkHttp already handles Gzip encoding automatically.

2023-02-25 13:17 UTC, alessandrojean commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +            val jsonString = json.encodeToString(
Use the other method

```kotlin
json.encodeToString<List<MangaDataClass>>(searchResults)
```

I could be wrong and this could not exist at all, but if it does it requires an extra import IIRC. Alternatively it could be like this, but test as well:

```kotlin
json.encodeToString(searchResults)
```

2023-02-25 13:17 UTC, alessandrojean commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +            request = Request.Builder()
Could just return straightaway instead, no need for the variable.

You can also make it more optimized by sending the query through the fragment of the URL. By definition fragments are not sent to the server but they will be available in the `response.request.url.fragment` later.

By using the fragment you don't even need to use the Request builder, could just use the provided `GET` method by the extensions-lib directly.

2023-02-25 13:17 UTC, alessandrojean commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +        if (searchQuery != null && searchQuery.isNotEmpty()) {
```suggestion
        if (!searchQuery.isNullOrEmpty()) {
```

2023-02-25 13:17 UTC, alessandrojean commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +                val fieldsToCheck = listOf<String?>(
Can use `listOfNotNull`, so it will build a list without nullable strings and you can skip the null check later.

2023-02-25 17:20 UTC, Sirver51 commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +                        GZIPInputStream(categoryMangaListResponse.body.byteStream())
I did that because it wasn't working without it, but I may have confused it with another error - I'll check it out again.

2023-02-25 17:24 UTC, Sirver51 commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +            val jsonString = json.encodeToString(
Android Studio marks both of these as a type mismatch on my machine; the second one is actually what I tried first. I will check to see if it builds in spite of the linter error, but any ideas on what's causing that?

2023-02-25 17:31 UTC, Sirver51 commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +            request = Request.Builder()
> Could just return straightaway instead, no need for the variable.

Since the request to be returned depends on the conditional, I figured it would be better to just have one return statement rather than one in each in the if and else. This is how I usually handle such a situation, but if what you said is more conformant with the expected style for this repo, I can change that.

> You can also make it more optimized by sending the query through the fragment of the URL. By definition fragments are not sent to the server but they will be available in the `response.request.url.fragment` later.

That makes sense, I'll make that change. Thanks for the info about fragments not going to the server, I wasn't aware of that.

2023-02-25 17:32 UTC, Sirver51 commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +        if (searchQuery != null && searchQuery.isNotEmpty()) {
Sorry, not familiar with Kotlin; will make that change.

2023-02-25 17:35 UTC, Sirver51 commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +                val fieldsToCheck = listOf<String?>(
Didn't know you could do that, will incorporate, thanks.

2023-02-25 18:04 UTC, jobobby04 commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +            val jsonString = json.encodeToString(
That specific function needs to be imported, use the IDE autocomplete to find and select that function.

2023-02-26 11:52 UTC, Sirver51 commented
I implemented the suggested changes, as well as an option to search a specific category rather than the whole library, and did some cleanup. I'm also halfway through an implementation for pagination (extension right now has trouble with large numbers of entries), but I have some questions that need answering, for which I will create a new issue.

2023-02-28 01:25 UTC, merged