Created OlympusScans
tachiyomiorg/tachiyomi-extensions pull request #15540
Opened 2023-03-01 17:22 UTC by wolfghost9898

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

OlympusScalation moved they page to another domain, but they changed all page.
now they use the name "OlympusScan"

2023-03-01 18:06 UTC, alessandrojean requested changes
There's a lot of stuff that needs to be changed. Major one is changing the package name, class name, source name (including rename/moving the folders).

You also need to remove the old extension from Madara and make it a single lang extension with only the Portuguese one (https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/multisrc/overrides/madara/olympusscanlation/src/OlympusScanlationFactory.kt).

2023-03-01 18:06 UTC, alessandrojean commented on src/es/olympusscans/src/eu/kanade/tachiyomi/extension/es/olympusscans/olympusscans.kt
> +        chapter_number = chapter.name!!.toFloat()
What if it suddenly isn't a valid float any more? You need to handle that as well.

```suggestion
        chapter_number = chapter.name.toFloatOrNull() ?: -1f
```

Do fill the `upload_date` as well. There's some examples in the CONTRIBUTING.md guide.

2023-03-01 18:06 UTC, alessandrojean commented on src/es/olympusscans/src/eu/kanade/tachiyomi/extension/es/olympusscans/olympusscans.kt
> +    override fun pageListParse(document: Document): List<Page> = throw UnsupportedOperationException("Not used")
Remove when changing to `HttpSource`.

2023-03-01 18:06 UTC, alessandrojean commented on src/es/olympusscans/src/eu/kanade/tachiyomi/extension/es/olympusscans/olympusscans.kt
> +        val slug = chapter.url.toString().substringAfter("comic-").substringBefore("/chapters").substringBefore("/comic")
`chapter.url` is already a string, so no need to use `toString()`. Also please format it better, the legibility is pretty bad.

```suggestion
        var id = chapter.url
            .substringAfter("/capitulo/")
            .substringBefore("/comic")
        val slug = chapter.url.substringAfterLast("comic-")
```

2023-03-01 18:06 UTC, alessandrojean commented on src/es/olympusscans/src/eu/kanade/tachiyomi/extension/es/olympusscans/olympusscans.kt
> +        return GET("$baseURLApi/api/series/$slug/chapters/$id?type=comic")
```suggestion
        return GET("$apiBaseUrl/api/series/$slug/chapters/$id?type=comic")
```

2023-03-01 18:06 UTC, alessandrojean commented on src/es/olympusscans/src/eu/kanade/tachiyomi/extension/es/olympusscans/olympusscans.kt
> +    override fun popularMangaRequest(page: Int): Request =
You need to provide that, otherwise users will be getting an error if they open the browse section of the extension.

2023-03-01 18:06 UTC, alessandrojean commented on src/es/olympusscans/src/eu/kanade/tachiyomi/extension/es/olympusscans/olympusscans.kt
> +    private fun String.toStatus(): String =
You're not even using this, can remove.

2023-03-01 18:07 UTC, alessandrojean commented
Will mark this one as a draft as it needs a lot of rewriting. Feel free to mark it as ready to review when finished, or ask any new questions here or at the #programming channel in our [Discord server](https://discord.gg/tachiyomi).

2023-03-02 08:00 UTC, AntsyLich commented on src/es/olympusscans/src/eu/kanade/tachiyomi/extension/es/olympusscans/olympusscans.kt
> +    }
we don't even need the whole url now just the slug is ok

2023-03-02 17:33 UTC, julioxd123 commented
When Updating the update The Olympians 😄

2023-03-05 03:13 UTC, wolfghost9898 commented
Thanks for feedback, just give a few days, i am going to work on it.

2023-03-10 17:39 UTC, kaekaes commented
Please accept this PR, we need it D:

2023-03-10 18:02 UTC, wolfghost9898 commented
i made the request changes and i deleted the old olympus extension.
also i added description, popular and latest mangas

2023-03-10 18:20 UTC, alessandrojean commented
You deleted the Portuguese version of the old extension still uses Madara, you need to move it to an individual Madara extension.

2023-03-10 18:23 UTC, alessandrojean requested changes

2023-03-10 18:23 UTC, alessandrojean commented on src/es/olympusscanlation/src/eu/kanade/tachiyomi/extension/es/olympusscanlation/olympusscanlation.kt
> +package eu.kanade.tachiyomi.extension.es.olympusscan
Wrong package name.

```suggestion
package eu.kanade.tachiyomi.extension.es.olympusscanlation
```

2023-03-10 18:23 UTC, alessandrojean commented on src/es/olympusscanlation/src/eu/kanade/tachiyomi/extension/es/olympusscanlation/DTO/OlympusScanlationDto.kt
> +package eu.kanade.tachiyomi.extension.es.olympusscanlation.DTO
Package names should be all lowercase, so rename it to `dto`

2023-03-10 18:23 UTC, alessandrojean commented on src/es/olympusscanlation/src/eu/kanade/tachiyomi/extension/es/olympusscanlation/olympusscanlation.kt
> +class olympusscanlation : HttpSource() {
```suggestion

class OlympusScanlation : HttpSource() {
```

2023-03-10 18:24 UTC, wolfghost9898 commented
i searched for another Olympus extension on madara, but i didn't find another one.
I understand that the Spanish and Portuguese versions was together.

2023-03-10 18:25 UTC, alessandrojean commented
It was a multi language extension, it contained both languages but they are separate websites. So you need to move the Portuguese one to a Madara single lang extension with only the Portuguese website.

2023-03-10 18:32 UTC, wolfghost9898 commented
yes but "https://br.olympusscanlation.com" it wasn't exist any more

2023-03-10 23:36 UTC, alessandrojean commented
Ah, in that case so it's everything alright.

2023-03-10 23:38 UTC, alessandrojean approved these changes

2023-03-11 17:03 UTC, hugocornago commented
I have tested the extension and it is working like the old one.

2023-03-13 14:43 UTC, arkon requested changes
Can you rebase and also delete [this](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/dd554f20b73665a9a4f0cb8947d18a8b886537fa/.github/workflows/issue_moderator.yml#L55-L60) as part of this PR?

2023-03-26 14:47 UTC, wolfghost9898 commented
I resolved the conflict, if you need that i make a change just let me know.

2023-03-28 13:32 UTC, merged