Shinigami.id
tachiyomiorg/tachiyomi-extensions pull request #15671
Opened 2023-03-11 14:06 UTC by mobi2002

closes #15408

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2023-03-11 18:46 UTC, alessandrojean requested changes

2023-03-11 18:46 UTC, alessandrojean commented on multisrc/overrides/madara/reaperscans/src/ReaperScansFactory.kt
> +class ReaperScansId : ReaperScans("https://shinigami.id", "id") {
As they're not part of Reaper Scans anymore as it seems, its actually better to remove it from the multi lang extension and make it a separate single lang extension.

2023-03-12 04:03 UTC, alessandrojean approved these changes

2023-03-12 12:27 UTC, Riztard commented
so people need to install the new ext right? 
but no migrating, since it keeps the id

2023-03-12 12:43 UTC, alessandrojean commented
Correct

2023-03-12 12:55 UTC, kataceking commented
> so people need to install the new ext right? but no migrating, since it keeps the id

Maksudnya gimana bang

2023-03-12 22:36 UTC, JoyBoy666 commented
> so people need to install the new ext right? but no migrating, since it keeps the id

New ext nya blom ada ya kan bg ?

2023-03-13 00:15 UTC, Riztard commented
> New ext nya blom ada ya kan bg ?

blom

> Maksudnya gimana bang

kalo udah di merge, nanti harus install ext yang baru biar bisa lagi

2023-03-13 14:38 UTC, merged