Add Extension
tachiyomiorg/tachiyomi-extensions pull request #15825
Opened 2023-03-24 18:36 UTC by MeLoseAgain

Closes: #15654 
Closes: #15554 
Closes: #15433
Closes: #15337 
Closes: #15329 
Closes: #15299 
Closes: #15132 
Closes: #14865

I fixed the icon for inazumanga which uses the default icon, added res to the folder

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

2023-03-24 18:39 UTC, alessandrojean requested changes

2023-03-24 18:39 UTC, alessandrojean commented on multisrc/overrides/madara/freemangatop/res/mipmap-hdpi/ic_launcher.png
You don't need to add the icon from the base theme to the overrides, can remove these.

2023-03-24 18:40 UTC, alessandrojean commented
About https://github.com/tachiyomiorg/tachiyomi-extensions/issues/15433, you need to remove/move the existing extension as well. Move from mangafront to Madara.

2023-03-24 18:41 UTC, MeLoseAgain commented on multisrc/overrides/madara/freemangatop/res/mipmap-hdpi/ic_launcher.png
> You don't need to add the icon from the base theme to the overrides, can remove these.

I'm moving from inazumanga/ to inazumanga/res so is that a problem

2023-03-24 18:42 UTC, alessandrojean commented on multisrc/overrides/madara/freemangatop/res/mipmap-hdpi/ic_launcher.png
You don't need these files as they're the same default ones from the theme. They will be copied during the build.

If you added it to a wrong folder in a previous commit, just delete them in a new commit.

2023-03-24 18:52 UTC, alessandrojean approved these changes

2023-03-24 18:56 UTC, MeLoseAgain commented
Wait a minute

2023-03-25 06:24 UTC, stevenyomi commented
Better split into 3 PRs (one for each multisrc).

2023-03-25 07:10 UTC, MeLoseAgain commented
Is that so? I don't mind deleting it (⁠≧⁠▽⁠≦⁠)

2023-04-01 19:42 UTC, merged