uk/honeymanga
tachiyomiorg/tachiyomi-extensions pull request #16069
Opened 2023-04-16 16:37 UTC by ihoneymanga

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

2023-04-16 18:06 UTC, scb261 requested changes

2023-04-16 18:06 UTC, scb261 commented on src/uk/honeymanga/src/eu/kanade/tachiyomi/extension/uk/honeymanga/HoneyManga.kt
> +        private fun parseDate(dateAsString: String): Long = dateFormat.parse(dateAsString)?.time ?: 0L
This potentially can break the extension if the date format ever changes. Better to wrap it with try catch to keep the extension usable when it happens. See #9002 as an example.

2023-04-16 18:06 UTC, scb261 commented on src/uk/honeymanga/src/eu/kanade/tachiyomi/extension/uk/honeymanga/HoneyManga.kt
> +            .addQueryParameter("pageSize", "1000") // most likely there will not be any more
Some manga can have more than 1000 chapters. For example One Piece and Martial Peak have 1000+ chapters on other sites, and potentially could be added to this site. Better to increase the limit

2023-04-16 21:40 UTC, alessandrojean requested changes
There's some stuff that needs to be changed, so I let it as suggestions. Also, please replace the icon with one generated by the [tool mentioned](https://as280093.github.io/AndroidAssetStudio/icons-launcher.html) in the CONTRIBUTING.md guide. The current icon in this PR doesn't match the extension icon pattern from the other extensions.

2023-04-16 21:40 UTC, alessandrojean commented on src/uk/honeymanga/src/eu/kanade/tachiyomi/extension/uk/honeymanga/HoneyManga.kt
> +            """
Use the kotlinx.serialization builders instead, it will handle special cases and JSON characters encoding if needed.

https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#json-element-builders

2023-04-16 21:40 UTC, alessandrojean commented on src/uk/honeymanga/src/eu/kanade/tachiyomi/extension/uk/honeymanga/HoneyManga.kt
> +            headers = headersBuilder().build(),
```suggestion
            headers = headers,
```

2023-04-16 21:40 UTC, alessandrojean commented on src/uk/honeymanga/src/eu/kanade/tachiyomi/extension/uk/honeymanga/HoneyManga.kt
> +            headers = headersBuilder().build(),
```suggestion
            headers = headers,
```

2023-04-16 21:40 UTC, alessandrojean commented on src/uk/honeymanga/src/eu/kanade/tachiyomi/extension/uk/honeymanga/HoneyManga.kt
> +                headersBuilder().build(),
```suggestion
                headers,
```

2023-04-16 21:40 UTC, alessandrojean commented on src/uk/honeymanga/src/eu/kanade/tachiyomi/extension/uk/honeymanga/HoneyManga.kt
> +        return GET(url, headersBuilder().build())
```suggestion
        return GET(url, headers)
```

2023-04-16 21:40 UTC, alessandrojean commented on src/uk/honeymanga/src/eu/kanade/tachiyomi/extension/uk/honeymanga/HoneyManga.kt
> +    }
```suggestion
    override fun imageRequest(page: Page): Request = GET(page.imageUrl!!, headers)
```

2023-04-16 21:40 UTC, alessandrojean commented on src/uk/honeymanga/src/eu/kanade/tachiyomi/extension/uk/honeymanga/HoneyManga.kt
> +        private fun parseDate(dateAsString: String): Long = dateFormat.parse(dateAsString)?.time ?: 0L
In addition to this, there's an example in the [CONTRIBUTING.md](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/CONTRIBUTING.md#chapter) guide.

2023-04-16 21:40 UTC, alessandrojean commented on src/uk/honeymanga/src/eu/kanade/tachiyomi/extension/uk/honeymanga/HoneyManga.kt
> +        private inline fun <reified R : Any> Response.asClass() = run { json.decodeFromString<R>(body.string()) }
Use `use` instead so it closes the `Response` as needed after using it.

```suggestion
        private inline fun <reified R : Any> Response.asClass() = use { json.decodeFromString<R>(body.string()) }
```

2023-04-16 21:40 UTC, alessandrojean commented on src/uk/honeymanga/src/eu/kanade/tachiyomi/extension/uk/honeymanga/HoneyManga.kt
> +                url = "https://data.api.honey-manga.com.ua/manga/${mangaDto.id}"
Don't store the full URL as if the API changes its URL users will need to migrate. Store instead the manga URL in the website and parse it to build the URL in the `mangaDetailsRequest` method or just save the id in the `url`.

2023-04-16 21:40 UTC, alessandrojean commented on src/uk/honeymanga/src/eu/kanade/tachiyomi/extension/uk/honeymanga/HoneyManga.kt
> +                url = "$API_URL/chapter/frames/${it.id}"
Same here, store the website URL for that chapter or only the ID and parse it to build the API request when needed.

2023-04-16 21:40 UTC, alessandrojean commented on src/uk/honeymanga/src/eu/kanade/tachiyomi/extension/uk/honeymanga/dtos/HoneyMangaChapterDto.kt
> +package eu.kanade.tachiyomi.extension.uk.honeymanga.dtos
Can merge the all 4 files for DTOs in a single one, as they're small data classes. For example,  `HoneyMangaDto.kt` in the root package.

2023-04-17 11:21 UTC, ihoneymanga commented on src/uk/honeymanga/src/eu/kanade/tachiyomi/extension/uk/honeymanga/HoneyManga.kt
> +        private fun parseDate(dateAsString: String): Long = dateFormat.parse(dateAsString)?.time ?: 0L
> In addition to scb comment, there's an example in the [CONTRIBUTING.md](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/CONTRIBUTING.md#chapter) guide.

nice suggestion, thanks! :+1:

2023-04-17 11:21 UTC, ihoneymanga commented on src/uk/honeymanga/src/eu/kanade/tachiyomi/extension/uk/honeymanga/HoneyManga.kt
> +            .addQueryParameter("pageSize", "1000") // most likely there will not be any more
I see your point :+1:

2023-04-17 13:11 UTC, ihoneymanga commented
@alessandrojean @scb261Thanks for the review. Could you please take a look once again ?

2023-04-17 13:34 UTC, alessandrojean commented
Haven't looked at the code yet, but the icon still needs to be changed to match the other extensions icons. Use the tool linked above to generate it.

https://as280093.github.io/AndroidAssetStudio/icons-launcher.html

2023-04-17 14:19 UTC, ihoneymanga commented
> Haven't looked at the code yet, but the icon still needs to be changed to match the other extensions icons. Use the tool linked above to generate it.
> 
> https://as280093.github.io/AndroidAssetStudio/icons-launcher.html

Done :+1:

2023-04-17 15:27 UTC, scb261 approved these changes
You don't need to increase the extension version since it wasn't released yet. Otherwise looks fine to me.

2023-04-17 20:08 UTC, ihoneymanga commented
@alessandrojean @scb261 could you please merge the PR or there are any other requirements ?  🙂

2023-04-17 20:09 UTC, alessandrojean commented
I am just waiting submitting one PR in a few moments so I can merge both and build both extensions at once.

2023-04-17 20:10 UTC, ihoneymanga commented
> I am just waiting submitting one PR in a few moments so I can merge both and build both extensions at once.

Great, thank you :+1:

2023-04-17 20:24 UTC, merged