Add Mangafireto
tachiyomiorg/tachiyomi-extensions pull request #16121
Opened 2023-04-21 10:15 UTC by Druzai

Closes #15370

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2023-04-21 12:22 UTC, alessandrojean requested changes
There's some stuff which needs to be changed. About the icon, please generate using the tool linked in the `CONTRIBUTING.md` guide as the one currently in this PR has a more rounded border compared to all extensions in the repository.

About the text translation, its just a suggestion, feel free to not follow it although its highly recommended to do so since users from a lot of languages will potentially use it. If you don't know other languages, at least create the `MangaFireIntl.kt` class structure and any other contributor will eventually add more languages.

2023-04-21 12:22 UTC, alessandrojean commented on src/all/mangafireto/build.gradle
> +    extName = 'MangaFire.to'
Make the same name from the source `name` attribute.

```suggestion
    extName = 'MangaFire'
```

2023-04-21 12:22 UTC, alessandrojean commented on src/all/mangafireto/src/eu.kanade.tachiyomi.extension.all.mangafireto/MangaFire.kt
> +    }
Use `flatMap`, it makes the code more easy to read.

```suggestion
    private fun MangasPage.insertVolumeEntries(): MangasPage {
        if (preferences.showVolume.not()) return this
        
        val newList = mangas.flatMap { manga ->
            val volume = SManga.create().apply {
                url = manga.url + VOLUME_URL_SUFFIX
                title = VOLUME_TITLE_PREFIX + manga.title
                thumbnail_url = manga.thumbnail_url
            }
          
            listOf(manga, volume)
        }
        
        return MangasPage(newList, hasNextPage)
    }
```

2023-04-21 12:22 UTC, alessandrojean commented on src/all/mangafireto/src/eu.kanade.tachiyomi.extension.all.mangafireto/MangaFire.kt
> +        GET("$baseUrl/filter?sort=recently_updated&language[]=$lang&page=$page", headers)
You will need to map the languages code from Tachi to the site one, since we don't use `pt-br` (all in lowercase) to Brazilian Portuguese for example (we use `pt-BR`).

2023-04-21 12:22 UTC, alessandrojean commented on src/all/mangafireto/src/eu.kanade.tachiyomi.extension.all.mangafireto/MangaFire.kt
> +        return Request.Builder().url(urlBuilder.build()).headers(headers).build()
Use the `GET` method conveninence, it accepts `HttpUrl` as well.

2023-04-21 12:22 UTC, alessandrojean commented on src/all/mangafireto/src/eu.kanade.tachiyomi.extension.all.mangafireto/MangaFire.kt
> +        }
```suggestion
        genre = root.select(".sidebar .more-info span:contains(Genres)").orEmpty()
            .joinToString{ it.ownText().trim() }
        author = root.select(".sidebar .more-info span:contains(Author)").orEmpty()
            .joinToString { it.ownText().trim() }
```

2023-04-21 14:04 UTC, stevenyomi commented
I'm going to try merging this with MangaReader.to so you don't need to address the reviews for now.

2023-04-21 14:39 UTC, Druzai commented
Also about the wrong icon, is this how it should be?
![ic_launcher](https://user-images.githubusercontent.com/70586473/233662205-4be0221d-d4a0-48fc-9605-44d5ab68c5d1.png)
I'll update icon after the merge if this one is correct.

2023-04-21 14:43 UTC, stevenyomi commented
> Also about the wrong icon, is this how it should be?

It's like that but you seem to have over-cropped it. In this case the best solution is to fill the corners with the colors before generating. I'll take care of it when I'm on it.

2023-04-23 11:12 UTC, stevenyomi commented
Superseded by #16138

2023-04-23 11:12 UTC, closed without merging