Suwayomi (Tachidesk): Implement pagination, sorting, tag-based filtering
tachiyomiorg/tachiyomi-extensions pull request #16252
Opened 2023-04-30 19:25 UTC by Sirver51

QoL features for the Tachidesk extension. Pagination in particular drastically improves performance; app no longer slows down when fetching a library with hundreds of manga and/or high-res thumbnails.

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Have not changed source names
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2023-04-30 19:32 UTC, Sirver51 commented
Did most of this a couple of months ago - didn't want to submit the PR until I finished tags, and didn't get around to that until now. Some implementation choices may be a bit odd (see: the tag filtering), mostly because I wanted to avoid code duplication if at all possible.

Also, I see that one of the automated Gradle checks has failed - sorry about that if it's my fault. I'm unsure as to what the issue is or how to fix it, since it works on my machine and I don't understand Gradle at the best of times.

2023-04-30 19:33 UTC, alessandrojean commented
The Action failed due to an external issue, I will trigger a rerun.

2023-04-30 21:28 UTC, alessandrojean requested changes

2023-04-30 21:28 UTC, alessandrojean commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Dto.kt
> +//    val unreadCount: Int? = 0,
If you're not using anymore, just remove the line instead of letting it commented.

2023-04-30 21:28 UTC, alessandrojean commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +    class SortBy(options: List<Pair<String, KProperty1<MangaDataClass, Any?>>>) :
I believe it's better to you manually map each attribute to the value later instead of using reflection, as it can easily cause issues.

2023-05-01 06:11 UTC, Sirver51 commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Dto.kt
> +//    val unreadCount: Int? = 0,
My bad, missed that during cleanup, will fix.

2023-05-01 06:13 UTC, Sirver51 commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +    class SortBy(options: List<Pair<String, KProperty1<MangaDataClass, Any?>>>) :
Yeah OK, will change. Looking at it now I'm honestly not sure why I decided to do it this way.

2023-05-06 14:14 UTC, alessandrojean approved these changes

2023-05-06 14:16 UTC, merged