Extension operational again
tachiyomiorg/tachiyomi-extensions pull request #16361
Opened 2023-05-07 21:43 UTC by RGFRv2

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2023-05-08 15:26 UTC, RGFRv2 commented on src/fr/scanmanga/src/eu/kanade/tachiyomi/extension/fr/scanmanga/ScanManga.kt
> +        val jsonObj = JSONArray(jsonRaw)
How ?

2023-05-08 16:06 UTC, RGFRv2 commented on src/fr/scanmanga/src/eu/kanade/tachiyomi/extension/fr/scanmanga/ScanManga.kt
> +        val findGenres = Regex("</span>([^'<]+)</a>").findAll(document.toString())
Like this ? 

```suggestion
        val genres = mutableListOf<String>()
        val aTags = document.select("a.infoBulle")
        for (aTag in aTags) {
            val spanTag = aTag.select("span").first()
            val text = aTag.ownText()
            if (text.isNotEmpty() && spanTag != null) {
                val spanText = spanTag.text()
                val content = text.replace(spanText, "").trim()
                genres.add(content)
            }
        }

```
Line 173 to 177 in actual code.

2023-05-08 16:38 UTC, RGFRv2 commented on src/fr/scanmanga/src/eu/kanade/tachiyomi/extension/fr/scanmanga/ScanManga.kt
> +        val jsonObj = JSONArray(jsonRaw)
Like this ? 
``` 
val mangaList = mutableListOf<SManga>()
val json = Json { ignoreUnknownKeys = true }
val jsonArray = json.parseToJsonElement(jsonRaw).jsonArray

for (jsonElement in jsonArray) {
    jsonElement.jsonArray?.let { innerArray ->
        if (innerArray.size > 0) {
            val item = SManga.create().apply {
                title = innerArray[0].jsonPrimitive.content
                url = innerArray[1].jsonPrimitive.content.replace("https://m.scan-manga.com", "")
            }
            mangaList.add(item)
        }
    }
}
```

2023-05-08 17:13 UTC, alessandrojean commented on src/fr/scanmanga/src/eu/kanade/tachiyomi/extension/fr/scanmanga/ScanManga.kt
> +        val jsonObj = JSONArray(jsonRaw)
Yes, but the `json` instance you get from the app by using `injectLazy`, as pointed out in the CONTRIBUTING.md guide.

You also don't need to create a mutable list, you can use the `.map` function on the jsonArray to automatically create a new list for you with the content you need, instead of pushing manually into a list.

2023-05-08 17:14 UTC, alessandrojean commented on src/fr/scanmanga/src/eu/kanade/tachiyomi/extension/fr/scanmanga/ScanManga.kt
> +        val findGenres = Regex("</span>([^'<]+)</a>").findAll(document.toString())
Can use `.map` here as well instead of a for loop.

2023-05-08 18:15 UTC, RGFRv2 commented on src/fr/scanmanga/src/eu/kanade/tachiyomi/extension/fr/scanmanga/ScanManga.kt
> +        val findGenres = Regex("</span>([^'<]+)</a>").findAll(document.toString())
Like this ? 
```kotlin
val genres = document.select("a.infoBulle").mapNotNull { aTag ->
    val spanTag = aTag.select("span").firstOrNull()
    val text = aTag.ownText().trim()
    if (text.isNotEmpty() && spanTag != null) {
        val spanText = spanTag.text()
        text.replace(spanText, "").trim()
    } else {
        null
    }
}
```

2023-05-08 18:15 UTC, RGFRv2 commented on src/fr/scanmanga/src/eu/kanade/tachiyomi/extension/fr/scanmanga/ScanManga.kt
> +        val jsonObj = JSONArray(jsonRaw)
Like this ?
```kotlin
val mangaList = json.parseToJsonElement(jsonRaw).jsonArray
    .mapNotNull { jsonElement ->
        jsonElement.jsonArray?.takeIf { it.size > 1 }?.let { innerArray ->
            SManga.create().apply {
                title = innerArray[0].jsonPrimitive.content
                url = innerArray[1].jsonPrimitive.content.replace("https://m.scan-manga.com", "")
            }
        }
    }
```

2023-05-19 13:56 UTC, alessandrojean requested changes

2023-05-19 13:56 UTC, alessandrojean commented on src/fr/scanmanga/src/eu/kanade/tachiyomi/extension/fr/scanmanga/ScanManga.kt
> +        val response = client.newCall(
The `imageRequest` method isn't supposed to do any network calls, it must just return a request to be fetched. If you need to do additional requests, you will need to do through a interceptor since there isn't a imageParse method you could use to do the additional requests.

2023-06-23 20:37 UTC, alessandrojean commented
Closing as this seems to be stale. Feel free to open a new PR if you still want to work on it.

2023-06-23 20:37 UTC, closed without merging