Update Japscan.kt
tachiyomiorg/tachiyomi-extensions pull request #16908
Opened 2023-06-28 21:26 UTC by Rajh

Japscan splitted tables, fast fix for it
Closes #16898

Checklist:

- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [X] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [X] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [X] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio

2023-06-28 22:21 UTC, Krylanc3lo commented
Thanks a lot @Rajh !

2023-06-29 15:14 UTC, alessandrojean requested changes

2023-06-29 15:14 UTC, alessandrojean commented on src/fr/japscan/src/eu/kanade/tachiyomi/extension/fr/japscan/Japscan.kt
> +        Log.d("japscan", "raw short lookup tables: $rawShortStringLookupTables")
```suggestion
```

2023-07-01 07:02 UTC, ronycohen commented
@Rajh

2023-07-01 12:49 UTC, ronycohen commented
Thanks a lot @Rajh !

2023-07-01 14:07 UTC, merged