YugenMangas: Disable fetchAllTitles
tachiyomiorg/tachiyomi-extensions pull request #17004
Opened 2023-07-04 01:42 UTC by bapeey

Yugen needs +100 requests for fetch all titles. Also they are not using the timestamp

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2023-07-04 01:54 UTC, alessandrojean requested changes

2023-07-04 01:54 UTC, alessandrojean commented on multisrc/overrides/heancms/yugenmangas/src/YugenMangas.kt
> +    override val fetchAllTitles = false
Only Brazilian RS is using at the moment, so should be fine to make the default as `false` and make it opt-in now (by setting it to true on RS only and removing the overrides on the other extensions -- bumping the version for the others isn't needed as technically nothing will change in behavior).

2023-07-04 01:58 UTC, bapeey commented on multisrc/overrides/heancms/yugenmangas/src/YugenMangas.kt
> +    override val fetchAllTitles = false
Done

2023-07-04 02:22 UTC, merged

2023-07-07 23:56 UTC, Striven100 commented
Hola, no se q problemas tenga con tachiyomi, pero ahora la pagina yugenmangas.com funciona bien. No se si fue un problema temporal u otra cosa. Porfavor, esta pagina es muy importante para las fuentes de lectores en español