fix(id/doujindesu): fix chapter does not load
tachiyomiorg/tachiyomi-extensions pull request #17027
Opened 2023-07-05 12:40 UTC by Sofie99

Closes #14004

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2023-07-07 23:21 UTC, TheKingTermux commented
I forget to mention it on #14004
The chapter name is missing like this image
![Screenshot_2023-07-08-06-12-02-49_afd66b7916d19a60815f56273408b73e.jpg](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/50316075/46909432-155b-4a78-a67c-5615b991875d)
There is no `"Chapter {number} {doujin_title}"` or `"Chapter {number}"` in there and for example when it is downloaded, it will generate a `"(invalid)"` folder on storage, there is only a *date* there, but that date *does not follow* the date of the *chapter that was created / uploaded* from DoujinDesu, but follows the date when we *first opened Doujin*
Has it been fixed?

2023-07-08 13:56 UTC, TheKingTermux commented
> This issues has been solved too..
> ![Screenshot_20230708-173759.png](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/117321707/cef40c3b-7886-45ae-8ac8-d666f3e1d4b6)

Uumm.... Where the release date ?
There was an error in the upload / release date

2023-07-08 16:23 UTC, TheKingTermux commented
> @TheKingTermux I've fixed date, popular and new.
> Everything should work fine now
> ![Screenshot_2023_0708_224611.jpg](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/117321707/ed1a9dc1-aaac-4e41-919d-5f6dde19b10b)
> 

That's what I mean, thanks for fixing it, sorry if I'm a bother, because I don't have any laptop / PC available that I can use to fix or testing this extension since December last year

2023-07-09 05:58 UTC, AhriVastayan1 commented
> > @TheKingTermux I've fixed date, popular and new.
> > Everything should work fine now
> > ![Screenshot_2023_0708_224611.jpg](https://user-images.githubusercontent.com/117321707/252012485-ed1a9dc1-aaac-4e41-919d-5f6dde19b10b.jpg)
> 
> That's what I mean, thanks for fixing it, sorry if I'm a bother, because I don't have any laptop / PC available that I can use to fix or testing this extension since December last year, LGTM to approve, but idk when the moderator review it

How to solve that man, it say page not found

2023-07-09 06:03 UTC, TheKingTermux commented
> How to solve that man, it say page not found

Just wait, updates will be available when this PR has been approved and merged by the moderator

2023-07-09 06:03 UTC, TheKingTermux commented
> How to solve that man, it say page not found

Just wait, updates will be available when this PR has been approved and merged by the moderator

2023-07-09 16:35 UTC, alessandrojean requested changes

2023-07-09 16:35 UTC, alessandrojean commented on src/id/doujindesu/src/eu/kanade/tachiyomi/extension/id/doujindesu/DoujinDesu.kt
> +        return epsStr?.filter { it.isDigit() }?.toFloatOrNull() ?: 1F
Should instead default to `-1f`.

```suggestion
        return epsStr?.filter { it.isDigit() }?.toFloatOrNull() ?: -1f
```

2023-07-09 16:55 UTC, merged