Random User-Agent Refactor
tachiyomiorg/tachiyomi-extensions pull request #17059
Opened 2023-07-09 13:11 UTC by AwkwardPeak7

- Moved away from interceptor since it was below in the chain, meaning the user-agent was not set for the webview in `cloudflareInterceptor`, thus rendering it useless for cloudflare issues
- Moved the shared logic to a lib
- Added ability to choose between desktop and mobile user-agents in Madara and Mangathemesia
- Added Chrome mobile to Nhentai

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2023-07-09 13:47 UTC, AntsyLich requested changes
Have the function below in the library and use that
```kt
fun Headers.Builder.applyUserAgent(userAgent: String?) = apply {
    if (userAgent == null) return@apply
    set("User-Agent", userAgent)
}
```

2023-07-09 13:47 UTC, AntsyLich commented on lib/randomua/src/main/java/eu/kanade/tachiyomi/lib/randomua/RandomUserAgent.kt
> +    }
```suggestion
   /**
     * Helper function to fetch latest random user agents
     *
     * @param userAgentType User Agent type one of (Desktop, Mobile, Off)
     * @param customUA  Optional custom user agent used when userAgentType is "off"
     * @param filterInclude Filter to only include User Agents containing these strings 
     * @param filterExclude Filter to exclude User Agents containing these strings
     */
    fun getUserAgent(
        userAgentType: Options,
        customUA: String? = null,
        filterInclude: List<String> = emptyList(),
        filterExclude: List<String> = emptyList(),
    ): String? {
        if (userAgentType == Options.Off) {
            return customUA?.ifBlank { null }
        }

        if (!userAgent.isNullOrEmpty()) return userAgent

        val uaResponse = client.newCall(GET(UA_DB_URL)).execute()
        
        if (!uaResponse.isSuccessful) {
            uaResponse.close()
            return null
        }

        val userAgentList = uaResponse.use { json.decodeFromString<UserAgentList>(it.body.string()) }
        
        return when (userAgentType) {
            Options.Desktop -> userAgentList.desktop
            Options.Mobile -> userAgentList.mobile
            else -> error("Expected Options.Desktop or Options.Mobile got Options.${userAgentType.name}")
        }
            .filter {
                filterInclude.any { filter ->
                    it.contains(filter, ignoreCase = true)
                }
            }
            .filterNot {
                filterExclude.any { filter ->
                    it.contains(filter, ignoreCase = true)
                }
            }
            .random()
            .also { userAgent = it }
    }
```

2023-07-09 13:47 UTC, AntsyLich commented on lib/randomua/src/main/java/eu/kanade/tachiyomi/lib/randomua/RandomUserAgent.kt
> +}
All caps maybe?

2023-07-09 14:10 UTC, AwkwardPeak7 commented on lib/randomua/src/main/java/eu/kanade/tachiyomi/lib/randomua/RandomUserAgent.kt
> +    }
done

2023-07-09 16:44 UTC, alessandrojean requested changes

2023-07-09 16:44 UTC, alessandrojean commented on lib/randomua/src/main/java/eu/kanade/tachiyomi/lib/randomua/RandomUserAgent.kt
> +enum class Options {
Rename it to `UserAgentType`? `Options` is very vague.

2023-07-09 16:44 UTC, alessandrojean commented on lib/randomua/src/main/java/eu/kanade/tachiyomi/lib/randomua/RandomUserAgent.kt
> +            else -> error("Expected Options.Desktop or Options.Mobile got Options.${userAgentType.name}")
Remember to rename the enum type and values here as well.

2023-07-09 16:44 UTC, alessandrojean commented on lib/randomua/src/main/java/eu/kanade/tachiyomi/lib/randomua/RandomUserAgent.kt
> +    val desktop: List<String>,
Could probably already add the new `recommended` field (and also add it as an option in the enum) so extensions can use it as well.

2023-07-09 16:44 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +    // override with "desktop" or "mobile if you want randomUserAgentType to be on by default for some source
```suggestion
    // override with DESKTOP or MOBILE if you want randomUserAgentType to be on by default for some source
```

2023-07-09 16:44 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +        .applyUserAgent(randomUA)
This will make the request to be called the first time in the library, executing requests in the `requests` methods, which should not be done. Using interceptors guarantee this will not happen.

2023-07-09 16:44 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangahub/MangaHub.kt
> +        .applyUserAgent(randomUA)
Same here.

2023-07-09 16:44 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangathemesia/MangaThemesia.kt
> +        .applyUserAgent(randomUA)
And here.

2023-07-09 16:44 UTC, alessandrojean commented on src/all/nhentai/src/eu/kanade/tachiyomi/extension/all/nhentai/NHentai.kt
> +        .applyUserAgent(randomUA)
Also here.

2023-07-09 16:45 UTC, alessandrojean commented
> Moved away from interceptor since it was below in the chain, meaning the user-agent was not set for the webview in cloudflareInterceptor, thus rendering it useless for cloudflare issues

About this, it is possible to add it in a specific position in the chain, can change the extension function to do that instead.

2023-07-10 05:28 UTC, AwkwardPeak7 commented
I am getting this error for source where `randomUserAgentType` is overriden
```
ExtensionLoader        E  Extension load error: DragonTea (eu.kanade.tachiyomi.extension.en.dragontea.DragonTea)
                          java.lang.reflect.InvocationTargetException
                          	at java.lang.reflect.Constructor.newInstance0(Native Method)
                          	at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
                          	at eu.kanade.tachiyomi.extension.util.ExtensionLoader.loadExtension(SourceFile:498)
                          	at eu.kanade.tachiyomi.extension.util.ExtensionLoader.loadExtensionFromPkgName(SourceFile:67)
                          	at eu.kanade.tachiyomi.extension.util.ExtensionInstallReceiver$getExtensionFromIntent$3.invokeSuspend(Unknown Source:9)
                          	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
                          	at kotlinx.coroutines.DispatchedTask.run(SourceFile:112)
                          	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
                          	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:63)
                          Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method eu.kanade.tachiyomi.lib.randomua.RandomUserAgentKt.setRandomUserAgent, parameter userAgentType
                          	at eu.kanade.tachiyomi.lib.randomua.RandomUserAgentKt.setRandomUserAgent(Unknown Source:7)
                          	at eu.kanade.tachiyomi.multisrc.madara.Madara.<init>(Madara.kt:73)
                          	at eu.kanade.tachiyomi.extension.en.dragontea.DragonTea.<init>(DragonTea.kt:22)
                          	at java.lang.reflect.Constructor.newInstance0(Native Method) 
                          	at java.lang.reflect.Constructor.newInstance(Constructor.java:343) 
                          	at eu.kanade.tachiyomi.extension.util.ExtensionLoader.loadExtension(SourceFile:498) 
                          	at eu.kanade.tachiyomi.extension.util.ExtensionLoader.loadExtensionFromPkgName(SourceFile:67) 
                          	at eu.kanade.tachiyomi.extension.util.ExtensionInstallReceiver$getExtensionFromIntent$3.invokeSuspend(Unknown Source:9) 
                          	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12) 
                          	at kotlinx.coroutines.DispatchedTask.run(SourceFile:112) 
                          	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1) 
                          	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:63) 
```

2023-07-10 06:11 UTC, AntsyLich requested changes

2023-07-10 06:11 UTC, AntsyLich commented on lib/randomua/src/main/java/eu/kanade/tachiyomi/lib/randomua/RandomUserAgent.kt
> +            }
```suggestion
            .filterNot {
                filterExclude.any { filter ->
                    it.contains(filter, ignoreCase = true)
                }
            }
```
Safe to not check here

2023-07-10 06:11 UTC, AntsyLich commented on lib/randomua/src/main/java/eu/kanade/tachiyomi/lib/randomua/RandomUserAgent.kt
> +    val desktop: List<String>,
It has been reverted for the time being cause extensions broke

2023-07-10 06:11 UTC, AntsyLich commented on multisrc/overrides/madara/default/additional.gradle
>  }
Can you add a new line

2023-07-10 06:11 UTC, AntsyLich commented on multisrc/overrides/mangathemesia/default/additional.gradle
> +}
New line

2023-07-10 06:11 UTC, AntsyLich commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +            else -> UserAgentType.OFF
Since the preference logic is being re-used might as well make it part of the lib

2023-07-10 07:18 UTC, AntsyLich commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +        if (randomUserAgentType == UserAgentType.OFF) {
I also meant moving the preference screen stuff to lib too

2023-07-10 07:28 UTC, AwkwardPeak7 commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +        if (randomUserAgentType == UserAgentType.OFF) {
tfw

2023-07-10 08:19 UTC, AntsyLich requested changes
Looks good to me except the last 2 changes

2023-07-10 08:19 UTC, AntsyLich commented on lib/randomua/src/main/java/eu/kanade/tachiyomi/lib/randomua/RandomUserAgent.kt
> +private class RandomUserAgent(
```suggestion
private class RandomUserAgentInterceptor(
```

2023-07-10 08:19 UTC, AntsyLich commented on lib/randomua/src/main/java/eu/kanade/tachiyomi/lib/randomua/RandomUserAgent.kt
> +            }.also(screen::addPreference)
Hide if random user agent is turned on? You can update the isVisible (i think) field

2023-07-10 08:29 UTC, AwkwardPeak7 commented on lib/randomua/src/main/java/eu/kanade/tachiyomi/lib/randomua/RandomUserAgent.kt
> +            }.also(screen::addPreference)
I can't find this field

2023-07-10 11:27 UTC, AntsyLich requested changes

2023-07-10 11:27 UTC, AntsyLich commented on lib/randomua/src/main/java/eu/kanade/tachiyomi/lib/randomua/RandomUserAgentPreference.kt
> +        const val CUSTOM_UA_SUMMARY = "Leave blank to use application default user-agent. (Required App Restart)"
```suggestion
        const val CUSTOM_UA_SUMMARY = "Leave blank to use application default user-agent. (Requires App Restart)"
```

2023-07-10 11:27 UTC, AntsyLich commented on lib/randomua/src/main/java/eu/kanade/tachiyomi/lib/randomua/RandomUserAgentPreference.kt
> +            if (preferences.getString(PREF_KEY_RANDOM_UA, "off") == "off") {
Use `getPrefUAType`?

2023-07-10 11:29 UTC, AwkwardPeak7 commented on lib/randomua/src/main/java/eu/kanade/tachiyomi/lib/randomua/RandomUserAgentPreference.kt
> +            if (preferences.getString(PREF_KEY_RANDOM_UA, "off") == "off") {
Not really needed since only checking against "off"

2023-07-10 11:44 UTC, AntsyLich requested changes

2023-07-10 16:19 UTC, AntsyLich commented
I have 0 clue

2023-07-11 17:07 UTC, AntsyLich approved these changes
Kinda sad that we couldn't do it in the previous way

2023-07-11 23:18 UTC, alessandrojean requested changes
Rest seems fine now 👍🏻

2023-07-11 23:18 UTC, alessandrojean commented on lib/randomua/src/main/java/eu/kanade/tachiyomi/lib/randomua/RandomUserAgentInterceptor.kt
> +            else -> error("Expected UserAgentType.Desktop or UserAgentType.Mobile got UserAgentType.${userAgentType.name}")
```suggestion
            else -> error("Expected UserAgentType.DESKTOP or UserAgentType.MOBILE but got UserAgentType.${userAgentType.name} instead")
```

2023-07-11 23:18 UTC, alessandrojean commented on lib/randomua/src/main/java/eu/kanade/tachiyomi/lib/randomua/RandomUserAgentInterceptor.kt
> + * Helper interceptor to set latest random user agent
```suggestion
 * Helper interceptor to add a latest random user agent interceptor.
 * The interceptor will added at the first position in the chain.
```

2023-07-15 21:31 UTC, alessandrojean approved these changes

2023-07-15 22:52 UTC, merged