Cleanup dead French MMRCMS sources and update Lelscan URL
tachiyomiorg/tachiyomi-extensions pull request #17060
Opened 2023-07-09 20:45 UTC by KirinRaikage

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

2023-07-10 13:34 UTC, stevenyomi requested changes

2023-07-10 13:38 UTC, KirinRaikage commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mmrcms/SourceData.kt
> +        "https://phoenix-scans.pl" -> """{"name":"Phoenix-Scans","base_url":"https://phoenix-scans.pl","supports_latest":false,"item_url":"<!doctype html>\n<html lang=\"pl-PL\">\n <head>\n  <meta htt
I could just repaste whatever was previously there on the file, but I didn't touch it manually anyway.

2023-07-10 13:49 UTC, stevenyomi commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mmrcms/SourceData.kt
> +        "https://phoenix-scans.pl" -> """{"name":"Phoenix-Scans","base_url":"https://phoenix-scans.pl","supports_latest":false,"item_url":"<!doctype html>\n<html lang=\"pl-PL\">\n <head>\n  <meta htt
You could, but if you have extra time you can try fixing them.

2023-07-11 23:20 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mmrcms/SourceData.kt
> +        "https://phoenix-scans.pl" -> """{"name":"Phoenix-Scans","base_url":"https://phoenix-scans.pl","supports_latest":false,"item_url":"<!doctype html>\n<html lang=\"pl-PL\">\n <head>\n  <meta htt
Some sources have a higher Cloudflare or block access from external IPs, although it is an auto generated file, it's better if you update it manually to only include the specific changes related to the sources you are changing instead.

2023-07-14 13:05 UTC, KirinRaikage commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mmrcms/SourceData.kt
> +        "https://phoenix-scans.pl" -> """{"name":"Phoenix-Scans","base_url":"https://phoenix-scans.pl","supports_latest":false,"item_url":"<!doctype html>\n<html lang=\"pl-PL\">\n <head>\n  <meta htt
Thanks for reviewing. I've reverted the changes and updated manually SourceData.kt instead.

2023-07-15 20:44 UTC, merged