Pixiv: new filters, group-by-series support
tachiyomiorg/tachiyomi-extensions pull request #17256
Opened 2023-07-25 18:17 UTC by Solitai7e

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

Closes #16035

2023-07-25 18:33 UTC, alessandrojean commented
There's a lot of Flow/suspend/coroutines stuff being handled that seems like overkill, an extension doesn't need that at all. Should be able to use the overridable methods and do any extra requests needed on the parse methods.

2023-07-25 18:34 UTC, alessandrojean requested changes

2023-07-25 18:34 UTC, alessandrojean commented on src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/PixivFactory.kt
> -package eu.kanade.tachiyomi.extension.all.pixiv
Keep it in a separate file, please.

2023-07-25 18:36 UTC, AntsyLich requested changes

2023-07-25 18:36 UTC, AntsyLich commented on src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Pixiv.kt
> +    private val pixivLang = if (lang == "all") "ja" else lang
Get rid of all lang then

2023-07-25 18:44 UTC, vetleledaal commented on src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Pixiv.kt
> +                val manga = SManga.create()
```kt
SManga.create().apply {
    setUrlWithoutDomain(...)
    title = "..."
    thumbnail_url = "..."
}
```

2023-07-25 18:44 UTC, vetleledaal commented on src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Pixiv.kt
> +                        word = filters.tags.state.ifBlank { "漫画" },
if this is a multi-lang extension, consider using English or different text for each language

2023-07-25 19:55 UTC, Solitai7e commented on src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Pixiv.kt
> +                        word = filters.tags.state.ifBlank { "漫画" },
That's actually just a fallback query string (the API doesn't seem to allow empty queries) for posts with the "manga" tag and I'm fairly certain the different language forms are all aliased to the same tag.

2023-07-25 20:10 UTC, alessandrojean requested changes
A general comment as well: using custom classes for a lot of operations doesn't seem to be helping much, and is instead making the code bloated. Also a lot of advanced stuff like threads, mutexes and locks aren't needed.

2023-07-25 20:10 UTC, alessandrojean commented on src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Pixiv.kt
> +    private open inner class HttpCall(href: String?) {
I don't think there's a need for this class and the `ApiCall` one. If you need to always have the Accept header in the API calls, you can have an inner val like `apiHeaders` and always use it with the `GET`/`POST` methods provided by the ext-lib instead.

```kotlin
private fun apiHeadersBuilder(): Headers.Builder = super.headersBuilder()
    .add("Accept", "application/json")

private val apiHeaders by lazy { apiHeadersBuilder().build() }
```

2023-07-25 20:10 UTC, alessandrojean commented on src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Pixiv.kt
> +                    if (entries.isEmpty()) break
Why instead of having to deal with a custom sequence, just do a normal while...?

Also, would be easier to actually use the parse (like `popularMangaParse`) methods instead of overriding the fetch and having to deal with Observables (which will be removed in the future).

A better way of dealing with this is making the first request with the normal popularMangaRequest(), and inside `popularMangaParse()` do the parsing of the first page by consuming the response and making any additional requests inside the parse method. If the source doesn't have pagination, can add a variable inside the class to act like a cache and then return sublists in each page.

Use sources like MangaDex as an code example, they do consume an API and are better structured to do so.

2023-07-25 20:10 UTC, alessandrojean commented on src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Pixiv.kt
> +    override fun fetchSearchManga(page: Int, query: String, filters: FilterList): Observable<MangasPage> {
Same here in this method, the whole synchronized/coroutines/sequences things is making the code a little unreadable and very hard to understand. It's better to use the methods provided by the super class instead.

2023-07-25 20:10 UTC, alessandrojean commented on src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Pixiv.kt
> +    override fun fetchLatestUpdates(page: Int): Observable<MangasPage> = synchronized(latestMangaLock) {
Same here.

2023-07-25 20:10 UTC, alessandrojean commented on src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Pixiv.kt
> +    private fun Sequence<PixivIllust>.toSManga() = sequence {
I don't get it why there's a need of using sequences.

2023-07-25 20:10 UTC, alessandrojean commented on src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Pixiv.kt
> +    override fun popularMangaRequest(page: Int): Request =
Consider using them as it will make the code more easier to read and understand.

2023-07-25 20:10 UTC, alessandrojean commented on src/all/pixiv/src/eu/kanade/tachiyomi/extension/all/pixiv/Pixiv.kt
> +    override fun searchMangaParse(response: Response): MangasPage =
Same here.

2023-07-25 22:21 UTC, Solitai7e commented
Thing is there's now this client-side filtering step for the search/popular/latest functions to deal with stuff like removing duplicate series (see toSManga) and making (most of) the filters work when search results are being fetched from an API that doesn't support one or more filters. For example right now if you do a search with an empty query and the users filter instead of a regular search it actually does a user search followed by a query for the posts of each of the users, which requires me to keep track of the progress of both searches on top of a list of series IDs for removing duplicates and I don't really know of a good way to do all that that doesn't involve flows/sequences, closures, or god forbid even more class-scope variables (though I now realize it might be a better idea to bundle them together with the iterators)

The synchronization blocks are there because I thought maybe Tachi assumes the class is thread-safe and calls from multiple threads, if that's not the case then I'll get rid of them.

2023-07-25 22:50 UTC, alessandrojean commented
> The synchronization blocks are there because I thought maybe Tachi assumes the class is thread-safe and calls from multiple threads

You can assume the methods will be called already in a separate and unique thread for that, we didn't have any issues with these things before in other extensions, so should be safe.

> that doesn't support one or more filters

Better to addopt the strategy other extensions does of warning the user through a Title filter that only one filter can be used at once, and if the query is not empty the filters will be ignored. That will make the implementation easier and the users are already familiar with this approach.

> removing duplicates

You can keep a private variable inside the class to keep track of the IDs of the series already displayed, just a simple string/int list will do the job. If the app call with the page = 1, you can clear it and start again.

2023-07-26 18:25 UTC, Solitai7e commented
I can't access the Discord since only people who are SMS-verified are allowed to post. (Discord doesn't like my number for some reason)

If you're OK with doing this in DMs please send a friend request to `solitai7e`.

2023-07-26 19:45 UTC, Solitai7e commented
(I wish github had private messages)

Re:
> ![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/60846439/ca45c0c5-860d-4278-86b4-87e58b330924)

It still wouldn't let me click on submit on the required steps screen.

2023-07-27 11:48 UTC, Solitai7e commented
I fail to comprehend how this is more readable or understandable than simply using a sequence.

```kotlin
private val userSearchCall = HttpCall("/search_user.php?s_mode=s_usr")
private val userIllustsCall = ApiCall("/touch/ajax/user/illusts")

private var searchUserIllustsNextPage = 1
private var userSearchNextPage = 1
private var userIllustsNextPage = 1

private lateinit var userSearchUnprocessedResults: Iterator<String>

private fun searchUserIllustsNextUser(): Boolean {
    userSearchCall.url.addEncodedQueryParameter("p", userSearchNextPage++.toString())

    userSearchUnprocessedResults = Jsoup.parse(userSearchCall.execute().body.string())
        .select(".user-recommendation-item > a").eachAttr("href")
        .map { it.substringAfterLast('/') }
        .iterator()

    if (!userSearchUnprocessedResults.hasNext()) return false
    
    userIllustsNextPage = 1
    userIllustsCall.url.setEncodedQueryParameter("id", userSearchUnprocessedResults.next())
    
    return true
}

private fun searchUserIllusts(page: Int, nick: String, type: String?): List<PixivIllust>? {
    if (page == 1) {
        searchUserIllustsNextPage = 1
        userSearchNextPage = 1
        searchUserIllustsNextUser()
    } else {
        require(page == searchUserIllustsNextPage)
    }

    searchUserIllustsNextPage++
    userIllustsCall.url.setEncodedQueryParameter("id", userSearchUnprocessedResults.next())

    val illusts = userIllustsCall.executeApi<PixivResults>().illusts!!
    if (illusts.isEmpty() && !searchUserIllustsNextUser()) return null

    return illusts
}
```

2023-07-27 12:32 UTC, alessandrojean commented
I guess it can be kept like it is for now, and it will be open to a future rewrite instead when needed. I still think it's overcomplicated code, but if it works, it works.

2023-07-27 12:33 UTC, merged

2023-07-27 14:01 UTC, alessandrojean commented
@Solitai7e Can you make a new PR to change the LruCache instance to be created `by lazy`? It direct usage is making the extension inspector to fail and not release the new versions of the extensions.

2023-07-27 14:26 UTC, alessandrojean commented
> Still can't access the Discord by the way, is there something special I'm supposed to do for the bypass to work?

Doesn't think so, it should be already working.