Fix Manhuaren parameters
tachiyomiorg/tachiyomi-extensions pull request #17295
Opened 2023-07-28 16:30 UTC by felixfon

Avoiding blocking by randomizing the Android model and build ID works, but you may still experience occasional blocking. In this case, the solution is to restart the application to change the model.

Closes #17170

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2023-07-28 17:43 UTC, AntsyLich commented on src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt
> +            add("User-Agent", "Dalvik/2.1.0 (Linux; U; Android 13; $model Build/$buildId)")
What's the issue with using the device's actual model and build

2023-07-29 02:22 UTC, DasCrystal commented
Why can't extension use user's device model?

2023-07-29 02:33 UTC, DasCrystal commented on src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt
> +            add("User-Agent", "Dalvik/2.1.0 (Linux; U; Android 13; $model Build/$buildId)")
> What's the issue with using the device's actual model and build 

Kinda worry about frequently changing device model (instead of actual model) under same ip would got blocking easier

2023-07-30 11:19 UTC, DasCrystal commented
Well, after testing, I think this version of extension sn' stable.

When I compile and install it, everyting works good, but after a few hours, it gets down.
So, I followed instruction in this PR, and tried some ways to restart application.
As result, **Swipe in recents**, **Force close in Settings** and **Clear cache before force close** are not working.
(Entering manga list will stil get "signature error")

2023-07-30 20:51 UTC, alessandrojean requested changes

2023-07-30 20:51 UTC, alessandrojean commented on src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt
> +            .url("https://storage.googleapis.com/play_public/supported_devices.csv")
Not really a fan of this, as suggested by others, use the actual model from the device instead, or add a preference so users can change it manually if they need.

2023-07-30 20:52 UTC, alessandrojean commented
Also worth to consider this is a cat and mouse game. If they break this approach, consider removing the extension instead next time, it's not worth to keep playing this game.

2023-08-01 09:36 UTC, DasCrystal commented
Well, after testing, I think this version of extension sn' stable.

When I compile and install it, everyting works good, but after a few hours, it gets down.
So, I followed instruction in this PR, and tried some ways to restart application.
As result, **Swipe in recents**, **Force close in Settings** and **Clear cache before force close** are not working.
(Entering manga list will stil get "signature error")
    
EDIT 2023:8:1: Cool news, the extension worked again, I just refreshed my Library, then it works normally, maybe random model helped?

2023-08-05 11:25 UTC, felixfon commented on src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt
> +            .url("https://storage.googleapis.com/play_public/supported_devices.csv")
I've replace with the actual device model.

2023-08-05 11:26 UTC, felixfon commented on src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt
> +            .url("https://storage.googleapis.com/play_public/supported_devices.csv")
I've replaced it with the actual device model.

2023-08-05 12:22 UTC, DasCrystal commented
It doesn't work for me, currently.

Before this (using real model name) version, I have had filled my device module in previous Manhuaren.kt, which is "using real module name" in a janky way, and it's effect just like using random model name.

And in this version, it even didn't work for a while. After update, it just said "no value for response".

Tested Actions:
- Directly install and use* - NVFR / SE*
- Clear cache / Force stop. - NVFR / SE
- Using extension with Cloudflare WARP - NVFR / SE

I am going to test on another phone, for more exact result.

* use = Explore > Manhuaren
* NVFR / SE = No value for response / Signature Error

2023-08-05 13:26 UTC, alessandrojean requested changes

2023-08-05 13:26 UTC, alessandrojean commented on src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt
> +            setEnabled(false)
What's the need for this if it isn't enabled?

2023-08-05 13:26 UTC, alessandrojean commented on src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt
> +internal const val USER_ID_PREF = "userId"
Move it to the `companion` object inside the class.

2023-08-05 13:26 UTC, alessandrojean commented on src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/RemoveTokenInterceptor.kt
> +        if (response != null && JSONObject(response.body.string()).has("errorResponse")) {
Consider using `kotlinx.serialization` instead of `org.json`.

```suggestion
        if (response != null && JSONObject(response.body.string()).has("errorResponse")) {
```

2023-08-05 13:26 UTC, alessandrojean commented on src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/SimpleEditTextPreference.kt
> +    }
Doesn't need this as summary can be set directly.

2023-08-05 13:26 UTC, alessandrojean commented on src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt
> +    private val buildId: String by lazy(mode = LazyThreadSafetyMode.SYNCHRONIZED) { generateBuildId() }
What's the issue into using the device actual build id? Randomizing it doesn't seem a good idea as well.

2023-08-05 17:55 UTC, stevenyomi commented on src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt
> +internal const val USER_ID_PREF = "userId"
Global variables are perfectly fine. Companion objects are not equivalent of Java's static fields; Kotlin encourages using global variables and functions.

2023-08-05 17:57 UTC, stevenyomi commented on src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/SimpleEditTextPreference.kt
> +    }
I guess it's to make the summary field show the preference value even if edited? Just a guess.

2023-08-05 18:07 UTC, stevenyomi commented on src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt
> +    private val buildId: String by lazy(mode = LazyThreadSafetyMode.SYNCHRONIZED) { generateBuildId() }
Probably anti-blocking?

2023-08-06 00:47 UTC, DasCrystal commented on src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt
> +    private val buildId: String by lazy(mode = LazyThreadSafetyMode.SYNCHRONIZED) { generateBuildId() }
Perhaps tachiyomi has own behavior mode?
If yes, then using random value won't work so long.

Also considering from server side, if implement an automatic-time-splited update mechanism, made tachiyomi act like official app, maybe would decrease server count that blocking tachiyomi. Just a approach.

2023-08-06 11:27 UTC, DasCrystal commented on src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/Manhuaren.kt
> +    private val buildId: String by lazy(mode = LazyThreadSafetyMode.SYNCHRONIZED) { generateBuildId() }
Perhaps tachiyomi has own behavior mode?
If yes, then using random value won't work so long.

Also considering from server side, if implement an automatic-time-splited update mechanism, made tachiyomi act like official app, maybe would decrease server count that blocking tachiyomi. Just a approach.

2023-08-06 11:34 UTC, DasCrystal reviewed
Oh, there have preferences in extension now, but tachiyomi just crashed after I clicked on the cog.

What is perferences in this extension used for currently?

2023-08-06 21:20 UTC, alessandrojean commented on src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/SimpleEditTextPreference.kt
> +    }
Wouldn't "%s" already do this? Extensions usually use it instead.

2023-08-07 02:35 UTC, stevenyomi commented on src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/SimpleEditTextPreference.kt
> +    }
No, that only works for list preferences.

2023-08-07 13:13 UTC, stevenyomi commented on src/zh/manhuaren/src/eu/kanade/tachiyomi/extension/zh/manhuaren/SimpleEditTextPreference.kt
> +    }
Can probably just get the value from the `SharedPreferences` instance.

2023-08-21 14:09 UTC, Nam1031 commented
Manhuaren is still not working

2023-08-30 14:51 UTC, alessandrojean commented
Closing as it seems to be stale. Feel free to open a new PR if you still want to work on this.

2023-08-30 14:51 UTC, closed without merging