Comick: Add MangaUpdates categories and comic type to the genre section in Manga details
tachiyomiorg/tachiyomi-extensions pull request #17348
Opened 2023-08-02 01:37 UTC by iD-666

Closes #17085

The genres will be like this:
```
Manga, Action, Comedy, Sci-Fi, Superhero, Monsters, ...
//Breakline for readability
Cyborg/s, Bald Protagonist, Monster/s, ...
```

Co-authored-by: AntsyLich <59261191+AntsyLich@users.noreply.github.com>

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

2023-08-02 02:13 UTC, alessandrojean commented
The `SManga.genre` doesn't support line breaks, it's supposed to be a comma separated string only, so can remove the `\n` usages into it.

2023-08-02 17:51 UTC, alessandrojean requested changes

2023-08-03 05:37 UTC, AwkwardPeak7 commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunDto.kt
> +    @SerialName("mu_comic_categories") val muCategories: List<MuComicCategory> = emptyList(),
![image](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/48650614/2c1e20a5-7ee4-4438-b70f-d05aa205794f)
I don't see `mu_comic_categories` in the response here. Please actually test your changes before making prs.

2023-08-03 17:24 UTC, iD-666 commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunDto.kt
> +    @SerialName("mu_comic_categories") val muCategories: List<MuComicCategory> = emptyList(),
I saw it in the /comic/{slug}/ response body
https://api.comick.app/comic/00-one-punch-man/?tachiyomi=true
![IMG_20230804_000315](https://github.com/tachiyomiorg/tachiyomi-extensions/assets/139281826/f00b1691-c696-40a6-b905-591cd7a7654d)

Would also be nice to include **"relate_to"** and **"md_relates"** in the description. It will be very useful so you could know if the comic has a prequel/sequel, and colored version

2023-08-03 17:32 UTC, AwkwardPeak7 commented on src/all/comickfun/src/eu/kanade/tachiyomi/extension/all/comickfun/ComickFunDto.kt
> +    @SerialName("mu_comic_categories") val muCategories: List<MuComicCategory> = emptyList(),
It's not where you put in the pr, as I said, it is not in the root of the response.

2023-08-03 17:34 UTC, alessandrojean commented
Closing as per #17364.

2023-08-03 17:34 UTC, closed without merging