Add Comic Fury Extension
tachiyomiorg/tachiyomi-extensions pull request #17479
Opened 2023-08-11 08:59 UTC by Tharow

Site: https://comicfury.com/
Site Moto: Comic Fury is a free, easy-to-use, advertisement free host for your webcomic(s). You can put up your own comics and get a website dedicated to them. 

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2023-08-13 12:21 UTC, AwkwardPeak7 commented
> Referenced all related issues in the PR body (e.g. "Closes #xyz")

#16983

2023-08-14 18:56 UTC, Tharow commented
> > Referenced all related issues in the PR body (e.g. "Closes #xyz")
> 
> #16983

Sorry I didn't know that there was an issue associated with it, next time I make an extension I'll be sure to check for related issues

2023-08-16 21:15 UTC, alessandrojean commented on src/all/comicfury/src/eu/kanade/tachiyomi/extension/all/comicfury/ComicFuryFactory.kt
> +        ComicFury("notext"),
How does the app shows that in the language header?

2023-08-16 21:15 UTC, alessandrojean commented on src/all/comicfury/src/eu/kanade/tachiyomi/extension/all/comicfury/ComicFury.kt
> +        req.addQueryParameter("language", lang.replace("-BR", "")) //remove ending to pt-BR
Can make a constructor variable instead such as `siteLang` which could defaults to `lang`, it will allow the variable to be changed if needed to other languages as well.

2023-08-21 17:18 UTC, Tharow commented on src/all/comicfury/src/eu/kanade/tachiyomi/extension/all/comicfury/ComicFuryFactory.kt
> +        ComicFury("notext"),
now shows No-Text

2023-08-23 16:16 UTC, alessandrojean requested changes

2023-08-23 16:16 UTC, alessandrojean commented on src/all/comicfury/src/eu/kanade/tachiyomi/extension/all/comicfury/ComicFuryFactory.kt
> +        ComicFury("No-Text", "notext"),
Can you make it as `other` as well and append a `(No text)` or something similar to the `name` instead? Would be better as `No-Text` isn't localizable by the `Locale` APIs as it isn't a valid ISO code (except `other` that the app explicit handles).

There was another similar extension in the past we followed this approach.

2023-08-23 17:36 UTC, Tharow commented on src/all/comicfury/src/eu/kanade/tachiyomi/extension/all/comicfury/ComicFuryFactory.kt
> +        ComicFury("No-Text", "notext"),
now displays as 
"other (NOTEXT)" in the app

2023-08-23 17:45 UTC, scb261 requested changes

2023-08-23 17:45 UTC, scb261 commented on src/all/comicfury/src/eu/kanade/tachiyomi/extension/all/comicfury/ComicFuryFactory.kt
> +        ComicFury("other-notext", "notext"),
Here's an example of how you can append text to the source name https://github.com/tachiyomiorg/tachiyomi-extensions/pull/6337

Note the `extraName` argument.

2023-08-23 17:51 UTC, alessandrojean commented on src/all/comicfury/src/eu/kanade/tachiyomi/extension/all/comicfury/ComicFuryFactory.kt
> +        ComicFury("No-Text", "notext"),
Not what I suggested, refer to the scb261 comment instead.

2023-08-23 20:59 UTC, Tharow commented on src/all/comicfury/src/eu/kanade/tachiyomi/extension/all/comicfury/ComicFuryFactory.kt
> +        ComicFury("No-Text", "notext"),
I apologize; I misunderstood what you meant,  has been corrected in latest revision.

2023-09-02 23:06 UTC, alessandrojean approved these changes

2023-09-02 23:06 UTC, merged