Kemono: Add option to load low resolution image in settings
tachiyomiorg/tachiyomi-extensions pull request #17556
Opened 2023-08-15 16:06 UTC by HisuianZoroark69

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2023-08-15 16:43 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/kemono/Kemono.kt
> +            summary = "Reduce load time significantly\nNeeds to clear chapter cache to take full effect."
```suggestion
            summary = "Reduce load time significantly. You need to clear the chapter cache to take effect."
```

2023-08-15 16:52 UTC, stevenyomi requested changes
You can override `imageRequest()` and insert the `/thumbnail` part to the network request to make it take effect immediately.

2023-08-16 07:59 UTC, HisuianZoroark69 commented
> You can override `imageRequest()` and insert the `/thumbnail` part to the network request to make it take effect immediately.

I think the cached image is linked to the page itself, not the url. So adding the ```/thumbnail``` in neither the ```pageListParse()``` nor the ```imageRequest()``` will effect immediately without clearing the chapter cache.
The best solution right now would be clearing the chapter cache automatically in code or prompt the user to change it like in your ```MangaReader``` extension: https://github.com/tachiyomiorg/tachiyomi-extensions/blob/ef58b57c6547516045c4c7ca1d6f7a1718d78f35/multisrc/overrides/mangareader/mangareaderto/src/Preferences.kt#L9-L18

But apparently I have yet to find a way to clear the chapter cache by code 😹.

2023-08-16 09:25 UTC, stevenyomi commented
What I mean is: if you open a chapter but images fail to load, then you turn on showing thumbnails, you don't need to clear the chapter cache (cached URLs) and the extension will request thumbnails upon opening the chapter again.

With your current solution, you'd always need to clear the chapter cache for opened chapters to reload.

Indeed, if you have already loaded thumbnails and then turn off this setting to view original images, you have to clear chapter cache. This is required in any solution.

I suggest you implement my suggestion and reword the summary to "When turning off, clear chapter cache to remove cached low resolution images."

Regarding MangaReader, it's because they don't have a predictable URL pattern to modify in `imageRequest()` (or I ddin't figure out), so I had to use the provided image quality preference when fetching image URLs.

2023-08-16 11:25 UTC, HisuianZoroark69 commented
I have implemented your suggestion by adding the ```/thumbnail``` at ```imageRequest()``` instead of ```pageListParse()``` and indeed it worked like what you've said.😸

I'll also reword the summary to "Reduce load time significantly. When turning off, clear chapter cache to remove cached low resolution images." as you've suggested.

Thank you for your help.

2023-08-16 11:29 UTC, stevenyomi requested changes

2023-08-16 11:29 UTC, stevenyomi commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/kemono/Kemono.kt
> +    override fun imageRequest(page: Page) = GET(baseUrl + (if (preferences.getBoolean(USE_LOW_RES_IMG, false)) "/thumbnail" else "") + page.imageUrl!!, headers)
Keep the original image URL to avoid breaking exisiting cached chapters. Instead, split the URL and insert the `/thumbnail` part in `imageRequest()`.

2023-08-16 12:00 UTC, HisuianZoroark69 commented
Is this ok?

2023-08-16 12:11 UTC, stevenyomi requested changes

2023-08-16 12:11 UTC, stevenyomi commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/kemono/Kemono.kt
> +        return GET(url.toString(), headers)
```suggestion
        val imageUrl = page.imageUrl!!
        if (!preferences.getBoolean(USE_LOW_RES_IMG, false)) return GET(imageUrl, headers)
        val index = imageUrl.indexOf('/', startIndex = 8) // https://
        val url = buildString { 
            append(imageUrl, 0, index)
            append("/thumbnail")
            append(imageUrl, index, imageUrl.length)
        }
        return GET(url, headers)
```

Use `imageUrl.indexOf('/', startIndex = 8)` since `baseUrl` might change (by preference, etc).

You can use the insert method; early return and more `append` lines are just optimizations.

2023-08-16 13:13 UTC, stevenyomi requested changes

2023-08-16 13:13 UTC, stevenyomi commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/kemono/Kemono.kt
> +        private var USE_LOW_RES_IMG = "USE_LOW_RES_IMG"
```suggestion
        private const val USE_LOW_RES_IMG = "USE_LOW_RES_IMG"
```

2023-08-18 20:48 UTC, alessandrojean approved these changes

2023-08-19 14:56 UTC, merged