Add Collected Curios to Tachiyomi extensions.
tachiyomiorg/tachiyomi-extensions pull request #17671
Opened 2023-08-25 17:37 UTC by Tomoka1

Adds Collected Curios to Tachiyomi extensions.
The site is quite splattered so further work is still need in adding more categories.
Main interests are available though, that's why i am submitting this merge request.

Closes #17670

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2023-08-25 17:59 UTC, alessandrojean commented
Can you use the icon generator tool linked at the CONTRIBUTING.md guide? This one seems to be missing the shadow.

2023-08-26 14:28 UTC, arkon requested changes

2023-08-26 14:28 UTC, arkon commented on src/en/collectedcurios/AndroidManifest.xml
> +<manifest package="eu.kanade.tachiyomi.extension" />
```suggestion
<manifest />
```

2023-08-26 14:28 UTC, arkon commented on src/en/collectedcurios/build.gradle
> +    extVersionCode = 2
```suggestion
    extVersionCode = 1
```

2023-08-26 14:28 UTC, arkon commented on src/en/collectedcurios/src/eu/kanade/tachiyomi/extension/en/collectedcurios/Collectedcurios.kt
> +                    /*
Remove if not needed?

2023-08-26 14:28 UTC, arkon commented on src/en/collectedcurios/src/eu/kanade/tachiyomi/extension/en/collectedcurios/Collectedcurios.kt
> +        // return Observable.just(MangasPage(emptyList(), false))
Remove if not needed?

2023-08-26 14:28 UTC, arkon commented on src/en/collectedcurios/src/eu/kanade/tachiyomi/extension/en/collectedcurios/Collectedcurios.kt
> +                    date_upload = 0L
Why explicitly 0?

2023-08-26 14:28 UTC, arkon commented on src/en/collectedcurios/src/eu/kanade/tachiyomi/extension/en/collectedcurios/Collectedcurios.kt
> +                    name = listOf("Chapter", i).joinToString(" - ")
Seems like an overkill way to build strings. Just inline them.

2023-08-26 14:28 UTC, arkon commented on src/en/collectedcurios/src/eu/kanade/tachiyomi/extension/en/collectedcurios/Collectedcurios.kt
> +    }
Why explicitly 0?

2023-08-26 14:28 UTC, arkon commented on src/en/collectedcurios/src/eu/kanade/tachiyomi/extension/en/collectedcurios/Collectedcurios.kt
> +        name = element.selectFirst(".w3-round")?.attr("value")!!.ifBlank { "date" }
Weird name ("date")?

2023-08-26 14:56 UTC, Tomoka1 commented on src/en/collectedcurios/src/eu/kanade/tachiyomi/extension/en/collectedcurios/Collectedcurios.kt
> +                    date_upload = 0L
Copied from another extension. Looked like a default value.

2023-08-26 15:24 UTC, Tomoka1 commented on src/en/collectedcurios/src/eu/kanade/tachiyomi/extension/en/collectedcurios/Collectedcurios.kt
> +                    date_upload = 0L
Copied from another extension. Looked like a default value to me.

2023-08-26 15:25 UTC, Tomoka1 commented on src/en/collectedcurios/src/eu/kanade/tachiyomi/extension/en/collectedcurios/Collectedcurios.kt
> +                    /*
Will be needed in next version.

2023-08-26 15:27 UTC, Tomoka1 commented on src/en/collectedcurios/AndroidManifest.xml
> +<manifest package="eu.kanade.tachiyomi.extension" />
Copied from another extension. Seemed logical to me, but i found the other "Remove package names" commit.

2023-08-26 15:31 UTC, Tomoka1 commented on src/en/collectedcurios/src/eu/kanade/tachiyomi/extension/en/collectedcurios/Collectedcurios.kt
> +        name = element.selectFirst(".w3-round")?.attr("value")!!.ifBlank { "date" }
Can probably be removed all together.

2023-08-26 15:48 UTC, Tomoka1 commented
Sorry, this is my first actual code review. I hope i didn't botch it by resolving everything now. I addressed most of Arkons issues now. Some i am keeping as reminder.

2023-08-27 17:23 UTC, alessandrojean requested changes

2023-08-27 17:23 UTC, alessandrojean commented on src/en/collectedcurios/build.gradle
> +    extName = 'Collectedcurios by Jolly Jack'
Can name it like the source itself.

```suggestion
    extName = 'Collected Curios'
```

2023-08-27 17:23 UTC, alessandrojean commented on src/en/collectedcurios/src/eu/kanade/tachiyomi/extension/en/collectedcurios/Collectedcurios.kt
> +        name = element.selectFirst(".w3-round")?.attr("value")!!.ifBlank { "date" }
```suggestion
        name = element.selectFirst(".w3-round")?.attr("value") ?: "Chapter"
```

2023-08-27 17:23 UTC, alessandrojean commented on src/en/collectedcurios/src/eu/kanade/tachiyomi/extension/en/collectedcurios/Collectedcurios.kt
> +        date_upload = 0L
Doesn't need to set if you don't have the date.

```suggestion
```

2023-08-27 17:23 UTC, alessandrojean commented on src/en/collectedcurios/src/eu/kanade/tachiyomi/extension/en/collectedcurios/Collectedcurios.kt
> +    }
```suggestion
    override fun imageUrlParse(response: Response): String {
        val url = response.request.url.toString()
        val document = response.asJsoup()
        
        return when {
            url.contains("sequentialart") ->
                document.selectFirst(".w3-image")!!.absUrl("src")
            url.contains("battlebunnies") || url.contains("spiderandscorpion") ->
                document.selectFirst("#strip")!!.absUrl("src")
            else -> throw Exception("Could not find the image")
        }
    }
```

2023-08-28 23:42 UTC, merged