Update Domain MGKomik (id)
tachiyomiorg/tachiyomi-extensions pull request #17747
Opened 2023-08-31 05:07 UTC by MeLoseAgain

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

2023-08-31 21:20 UTC, arkon requested changes
There's an override too: https://github.com/tachiyomiorg/tachiyomi-extensions/blob/63203338db57d3ebb9718f3afd9cad1f3e95cbf9/multisrc/overrides/madara/mgkomik/src/MGKomik.kt#L7

Please actually test your change first.

2023-09-01 22:31 UTC, alessandrojean commented
Marking as a draft until it's properly tested on Android Studio.

2023-09-06 16:41 UTC, alessandrojean requested changes

2023-09-06 17:22 UTC, MeLoseAgain commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> +        SingleLang("MG Komik", "https://mgkomik.id", "id", overrideVersionCode = 5),
Thanks for the review, I'll check

2023-09-07 16:15 UTC, merged