Update Manhwa18net layout
tachiyomiorg/tachiyomi-extensions pull request #18040
Opened 2023-09-19 03:05 UTC by BrutuZ

Updated parser to the current layout.
- Changed URL paths
- Changed values for sorting
- Changed CSS selector for pages
- Overrode Chapter parser

Closes #15460

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2023-09-19 03:08 UTC, alessandrojean requested changes

2023-09-19 03:08 UTC, alessandrojean commented on multisrc/overrides/fmreader/manhwa18net/src/Manhwa18NetFactory.kt
> +    return runCatching { SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH).parse(dateStr)?.time }
Make the SimpleDateFormat a constant, otherwise it will be recreated for every chapter.

2023-09-19 03:25 UTC, BrutuZ commented on multisrc/overrides/fmreader/manhwa18net/src/Manhwa18NetFactory.kt
> +    return runCatching { SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH).parse(dateStr)?.time }
Like so?

2023-09-19 22:30 UTC, alessandrojean requested changes
Also, there's a build error, fix it, or otherwise it won't be able to get merged.

2023-09-19 22:30 UTC, alessandrojean commented on multisrc/overrides/fmreader/manhwa18net/src/Manhwa18NetFactory.kt
> +    SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH)
Can move it to inside the class.

2023-09-19 22:38 UTC, BrutuZ commented on multisrc/overrides/fmreader/manhwa18net/src/Manhwa18NetFactory.kt
> +    SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH)
Could I instead move the `parseDate` function and object to the main FMReader generator class (https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/fmreader/FMReader.kt#L300) and then reference it on those two language instances?

2023-09-19 22:39 UTC, alessandrojean commented on multisrc/overrides/fmreader/manhwa18net/src/Manhwa18NetFactory.kt
> +    SimpleDateFormat("dd/MM/yyyy", Locale.ENGLISH)
Just make the `parseChapterDate` `protected open` there and override inside the source class.

2023-09-20 15:25 UTC, alessandrojean approved these changes

2023-09-20 15:26 UTC, merged