InazuManga: Change name and factory source
tachiyomiorg/tachiyomi-extensions pull request #18442
Opened 2023-10-08 18:11 UTC by AhmadGhoni

I changed the overrideVersionCode from 0 to 6 to trigger the update. Please let me know if I made a mistake.

Closes #17810
Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2023-10-08 21:43 UTC, alessandrojean requested changes

2023-10-08 21:43 UTC, alessandrojean commented on multisrc/overrides/mangathemesia/inazumanga/src/YumeKomik.kt
> +    override val id: Long = 4092752168230839868
Since they changed their theme, it's good to not keep the old `id` to force the users to migrate to update their entries URLs.

```suggestion
```

2023-10-09 03:16 UTC, AhmadGhoni commented on multisrc/overrides/mangathemesia/inazumanga/src/YumeKomik.kt
> +    override val id: Long = 4092752168230839868
So, is this like creating a new extension, and users need to migrate from the old `id` to the new source?

2023-10-09 04:20 UTC, alessandrojean commented on multisrc/overrides/mangathemesia/inazumanga/src/YumeKomik.kt
> +    override val id: Long = 4092752168230839868
Yes but existing users will receive as an update so they know it's the "same site", besides having to migrate after the update.

2023-10-09 21:30 UTC, merged