[RU]Senkuro and Senkognito new source
tachiyomiorg/tachiyomi-extensions pull request #18552
Opened 2023-10-14 11:54 UTC by e-shl

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

2023-10-15 11:17 UTC, Riztard commented
the lint issue probably from extra white space in new/empty line

2023-10-16 22:13 UTC, alessandrojean requested changes

2023-10-16 22:13 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/senkuro/SenkuroQueries.kt
> +                         mangaTachiyomiChapterPages(mangaId: %mangaId,chapterId: %chapterId) {
Can you fix the indentation for all the query strings?

2023-10-16 22:13 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/senkuro/Senkuro.kt
> +        .add("User-Agent", "Tachiyomi (+https://github.com/tachiyomiorg/tachiyomi)")
Have they explicit asked for this to be sent?

2023-10-17 04:06 UTC, e-shl commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/senkuro/Senkuro.kt
> +        .add("User-Agent", "Tachiyomi (+https://github.com/tachiyomiorg/tachiyomi)")
Yes

2023-10-18 00:16 UTC, alessandrojean requested changes
Also please change the icon to follow the pattern used by all extensions (**square** with rounded corners). Use the tool linked in the CONTRIBUTING.md guide to generate it.

2023-10-18 00:16 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/senkuro/SenkuroQueries.kt
> +                                    %query: String,
This still seems to be indented with unnecessary spaces. Fix it to use 4 spaces.

2023-10-18 00:16 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/senkuro/SenkuroQueries.kt
> +                mangaTachiyomiInfo(mangaId: %mangaId) {
Same here.

2023-10-18 00:16 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/senkuro/SenkuroQueries.kt
> +                                                            message
And here and all other queries.

2023-10-18 03:43 UTC, e-shl commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/senkuro/SenkuroQueries.kt
> +                                    %query: String,
Enough. This is just a string representation for further conversion.

2023-10-18 04:03 UTC, e-shl commented
> _**square**_ with rounded corners

@alessandrojean subjective stylization. And I already violated the pattern  https://github.com/tachiyomiorg/tachiyomi-extensions/tree/master/src/ru/remanga/res

2023-10-18 13:06 UTC, alessandrojean commented
Well, that probably passed without a notice in the review process. It still should be a square with rounded borders, please change it.

2023-10-18 14:49 UTC, alessandrojean commented
All sources uses it, so that should be fine to indicate. But will add to the CONTRIBUTING.md guide to make explicit as well.

2023-10-21 14:28 UTC, alessandrojean requested changes
Indentation is important to keep a good code readability. It doesn't matter if the source server will strip all the spaces or whatsoever, it needs to be clean for any contributor to be able to read and understand properly the code.

I suggested some changes to fix this and will commit the suggestions to enforce the same indentation.

2023-10-21 14:28 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/senkuro/SenkuroQueries.kt
> +
```suggestion
        query searchTachiyomiManga(
            %query: String,
            %type: MangaTachiyomiSearchTypeFilter,
            %status: MangaTachiyomiSearchStatusFilter,
            %translationStatus: MangaTachiyomiSearchTranslationStatusFilter,
            %genre: MangaTachiyomiSearchGenreFilter,
            %tag: MangaTachiyomiSearchTagFilter,
            %format: MangaTachiyomiSearchGenreFilter,
            %rating: MangaTachiyomiSearchTagFilter,
            %offset: Int,
        ) {
            mangaTachiyomiSearch(
                query:%query,
                type: %type,
                status: %status,
                translationStatus: %translationStatus,
                genre: %genre,
                tag: %tag,
                format: %format,
                rating: %rating,
                offset: %offset,
            ) {
                mangas {
                    id
                    slug
                    originalName {
                        lang
                        content
                    }
                    titles {
                        lang
                        content
                    }
                    alternativeNames {
                        lang
                        content
                    }
                    cover {
                        original {
                            url
                        }
                    }
                }
            }
        }
```

2023-10-21 14:28 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/senkuro/SenkuroQueries.kt
> +
```suggestion
        query fetchTachiyomiManga(%mangaId: ID!) {
            mangaTachiyomiInfo(mangaId: %mangaId) {
                id
                slug
                originalName {
                    lang
                    content
                }
                titles {
                    lang
                    content
                }
                alternativeNames {
                    lang
                    content
                }
                localizations {
                    lang
                    description
                }
                type
                rating
                status
                formats
                genres {
                    slug
                    titles {
                        lang
                        content
                    }
                }
                tags {
                    slug
                    titles {
                        lang
                        content
                    }
                }
                translationStatus
                cover {
                  original {
                      url
                  }
                }
                mainStaff {
                    roles
                    person {
                        name
                    }
                }
            }
        }
```

2023-10-21 14:28 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/senkuro/SenkuroQueries.kt
> +
```suggestion
        query fetchTachiyomiChapters(%mangaId: ID!) {
            mangaTachiyomiChapters(mangaId: %mangaId) {
                message
                chapters {
                    id
                    slug
                    branchId
                    name
                    teamIds
                    number
                    volume
                    updatedAt
                }
                teams {
                    id
                    slug
                    name
                }
            }
        }

```

2023-10-21 14:28 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/senkuro/SenkuroQueries.kt
> +
```suggestion
        query fetchTachiyomiChapterPages(
             %mangaId: ID!,
             %chapterId: ID!
        ) {
            mangaTachiyomiChapterPages(
                mangaId: %mangaId,
                chapterId: %chapterId
            ) {
                pages {
                    url
                }
            }
        }
```

2023-10-21 14:28 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/senkuro/SenkuroQueries.kt
> +        }
```suggestion
        query fetchTachiyomiSearchFilters {
            mangaTachiyomiSearchFilters {
                genres {
                    id
                    slug
                    titles {
                        lang
                        content
                    }
                }
                tags {
                    id
                    slug
                    titles {
                        lang
                        content
                    }
                }
            }
        }
```

2023-10-21 14:40 UTC, merged