Add Hentalk extension
tachiyomiorg/tachiyomi-extensions pull request #18593
Opened 2023-10-17 01:06 UTC by BrutuZ

Closes #18550

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2023-10-17 01:12 UTC, alessandrojean commented
Haven't reviewed it properly yet, but can you remove the log statements from the source class? The ones in the deep linking activity are fine to be kept.

2023-10-17 01:21 UTC, BrutuZ commented
Totally overlooked that 😅. I even had the Search and Replace already filled with the RegEx but forgot to "do the thing" after the device tests

2023-10-18 00:35 UTC, alessandrojean requested changes

2023-10-18 00:35 UTC, alessandrojean commented on src/en/hentalk/src/eu/kanade/tachiyomi/extension/en/hentalk/HenTalk.kt
> +                when {
Kotlin has proper support to `==`. This whole `when` can be simplified like:

```kotlin
when (filter.name) {
  "Title", "Artist", "Circle" -> { /* ... */ }
  "Tag" -> { /* ... */ }
  else -> { /* ... */ }
}
```

2023-10-18 00:35 UTC, alessandrojean commented on src/en/hentalk/src/eu/kanade/tachiyomi/extension/en/hentalk/HenTalk.kt
> +                }.distinct().joinToString()
```suggestion
            document.select(".metadata a[href^='/artists/'], article > a div.artists")
                .map { it.text() }.distinct().joinToString()
```

2023-10-18 00:35 UTC, alessandrojean commented on src/en/hentalk/src/eu/kanade/tachiyomi/extension/en/hentalk/HenTalk.kt
> +                chapter_number = ch.toFloat()
Doesn't need to set it, let the app parse it.

2023-10-18 00:35 UTC, alessandrojean commented on src/en/hentalk/src/eu/kanade/tachiyomi/extension/en/hentalk/HenTalk.kt
> +            throw UnsupportedOperationException("Error: Empty pages (try Webview)")
Just return an `emptyList()` in this case, as the app already handles this. The user can open in WebView if needed, there isn't need for a custom error.

2023-10-18 00:35 UTC, alessandrojean commented on src/en/hentalk/src/eu/kanade/tachiyomi/extension/en/hentalk/HenTalk.kt
> +        }
```suggestion
        val previewImages = document.select(".previews > .preview img")
            .map { if (it.hasAttr("data-src")) it.absUrl("data-src") else it.absUrl("src") }
            
        if (previewImages.isEmpty()) {
            val cover = document.selectFirst("figure.thumbnail")!!
                .attr("src").replace("/896/", "/320/")
            val cdnUrl = cover.substringBeforeLast("/")
                .substringBeforeLast("/")
            
            return List(totalPages) { Page(it, imageUrl = "$cdn/${i + 1}.jpg" }
        }
        
        return previewImages.mapIndexed { index, imageSrc -> {
            Page(index, imageUrl = imageSrc.replace("/320.webp", ".jpg"))
        }
```

2023-10-18 00:35 UTC, alessandrojean commented on src/en/hentalk/src/eu/kanade/tachiyomi/extension/en/hentalk/HenTalkUrlActivity.kt
> + * Springboard that accepts https://fakku.cc/archive/xxxxx intents and redirects them to
```suggestion
 * Activity that accepts https://fakku.cc/archive/xxxxx intents and redirects them to
```

2023-10-18 00:35 UTC, alessandrojean commented on src/en/hentalk/src/eu/kanade/tachiyomi/extension/en/hentalk/HenTalkWebViewInterceptor.kt
> +        if (response.headers("Content-Type").any { it.contains("text/html") }) {
There's only one `Content-Type` header. If the site is sending multiple, they have an issue.

```suggestion
        if (response.headers["Content-Type"]!!.contains("text/html")) {
```

2023-10-18 00:55 UTC, BrutuZ commented on src/en/hentalk/src/eu/kanade/tachiyomi/extension/en/hentalk/HenTalk.kt
> +                chapter_number = ch.toFloat()
It'll handle all the way from `val ch = ...`?

2023-10-18 01:10 UTC, alessandrojean commented on src/en/hentalk/src/eu/kanade/tachiyomi/extension/en/hentalk/HenTalk.kt
> +                chapter_number = ch.toFloat()
Can remove just the line that sets `chapter_number`.

2023-10-21 16:53 UTC, BrutuZ commented
Worked for the OG Koushoku layout they had going, not it's pointless since the site just switched to LANraragi

2023-10-21 16:53 UTC, closed without merging