NEW - TaddyINK extension
tachiyomiorg/tachiyomi-extensions pull request #18699
Opened 2023-10-24 18:26 UTC by dmathewwws

Hi, 

TaddyINK distributes comics to multiple comic apps using an [open source standard](https://3s-docs.org/comicseries)). This extension can parse any comic feed that is in this standard so that it can be displayed in the app.

**One useful note:** You don't need to have used TaddyINK to upload your comic. As long as your comic is in the [open-source standard](https://3s-docs.org/comicseries), add your comic to TaddyInk's directory by following these [instructions](https://taddy.org/developers/comics-api/add-a-comicseries-to-taddy) and it will show up in this extension.

Checklist:
- [X] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [X] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [X] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [X] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [X] Have not changed source names
- [X] Have explicitly kept the `id` if a source's name or language were changed
- [X] Have tested the modifications by compiling and running the extension through Android Studio

2023-10-24 18:56 UTC, alessandrojean commented
Can you redo the icons using the Icon Generator tool linked in the CONTRIBUTING.md guide? We don't have support for vectorized and dynamic icons yet.

2023-10-24 18:57 UTC, alessandrojean requested changes
Will do a proper review later again.

2023-10-24 18:57 UTC, alessandrojean commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyUtils.kt
> +import org.json.JSONObject
Please use kotlinx.serialization.

2023-10-24 18:57 UTC, alessandrojean commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyInk.kt
> +    private val popularManagaLimit = 25
```suggestion
    private val popularMangaLimit = 25
```

2023-10-24 18:57 UTC, alessandrojean commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyInk.kt
> +    private val searchManagaLimit = 25
```suggestion
    private val searchMangaLimit = 25
```

2023-10-24 19:06 UTC, AntsyLich requested changes
Also use the icon generated using the [Icon Generator](https://as280093.github.io/AndroidAssetStudio/icons-launcher.html) in [CONTRIBUTING.md](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/master/CONTRIBUTING.md)

2023-10-24 19:06 UTC, AntsyLich commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyUtils.kt
> +            update_strategy = UpdateStrategy.ONLY_FETCH_ONCE
This will make it so that it will only fetch chapter and metadata only once and never again. Pretty sure you want users to keep checking for more chapters?

2023-10-24 19:06 UTC, AntsyLich commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyInkFactory.kt
> +        TaddyInk("all", ""),
Do you plan to add more languages? If not then no need to use a source factory

2023-10-24 19:06 UTC, AntsyLich commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyInk.kt
> +    }
```suggestion
    override fun latestUpdatesRequest(page: Int): Request = throw UnsupportedOperationException("Not used!")

    override fun latestUpdatesParse(response: Response): MangasPage = throw UnsupportedOperationException("Not used!")
```

2023-10-24 19:08 UTC, AntsyLich commented
Missed @alessandrojean doing a review... Anyway I've more stuff to review but those can come after this changes

2023-10-24 22:43 UTC, dmathewwws commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyInk.kt
> +    private val searchManagaLimit = 25
When I change to:
```
    private const val popularMangaLimit = 25
    private const val searchMangaLimit = 25
```

I get the following error
```
Const 'val' are only allowed on top level, in named objects, or in companion objects
```

2023-10-24 22:45 UTC, dmathewwws commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyInkFactory.kt
> +        TaddyInk("all", ""),
Yes. we plan to add more languages in the next couple months

2023-10-24 22:51 UTC, AntsyLich commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyInk.kt
> +    private val searchManagaLimit = 25
Then move it to companion object? Also since both are same value can just merge and rename to `BROWSE_ITEM_LIMIT`

2023-10-24 22:55 UTC, dmathewwws commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyInk.kt
> +        ListPreference(screen.context).apply {
I get an error saying:

```
SwitchPreference is deprecated
```

2023-10-24 23:01 UTC, AntsyLich commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyInk.kt
> +        ListPreference(screen.context).apply {
Use `SwitchPreferenceCompat`

2023-10-24 23:06 UTC, dmathewwws commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyUtils.kt
> +            url = sssUrl
not sure what you mean. "keep the id"?

don't I have to set all the parameters

```
url = sssUrl
title = name
creators?.let { if (it.isNotEmpty() && it.isNotBlank()) author = it }
description = sssDescription
thumbnail_url = thumbnailUrl
status = SManga.ONGOING
update_strategy = UpdateStrategy.ALWAYS_UPDATE
genre = genres
initialized = true
```

2023-10-24 23:08 UTC, alessandrojean commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyUtils.kt
> +            url = sssUrl
He means only using the id as the URL of the manga. Then use the id to build the URLs when needed.

2023-10-24 23:11 UTC, dmathewwws commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyInk.kt
> +    private val searchManagaLimit = 25
moved it to the companion object

2023-10-25 13:39 UTC, dmathewwws commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyUtils.kt
> +            url = sssUrl
the url doesn't always have the taddy.org baseUrl FYI. (this extension can display any SSS comic feed, so it can be hosted on any domain). I mention it above in my first comment.

2023-10-25 13:50 UTC, AntsyLich commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyUtils.kt
> +            url = sssUrl
So it is possible to get comics outside of  taddy.org using the api? If that is the case no need to change it

2023-10-25 14:00 UTC, alessandrojean requested changes

2023-10-25 14:00 UTC, alessandrojean commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyUtils.kt
> +        return formatter.parse(timeString)?.time ?: 0L
This can throw exceptions.

```suggestion
        return runCatching { formatter.parse(timeString)?.time }
            .getOrNull() ?: 0L
```

2023-10-25 15:26 UTC, dmathewwws commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyInk.kt
> +    private var displayFullTitle: Boolean = when (preferences.getString(TITLE_PREF, "full")) {
I do have a question, can i set Webtoons layout as the default layout using SwitchPreferenceCompat or SharedPreferences?

2023-10-25 15:30 UTC, alessandrojean commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyInk.kt
> +    private var displayFullTitle: Boolean = when (preferences.getString(TITLE_PREF, "full")) {
If you mean setting the reader layout in the app, you can't.

2023-10-25 18:14 UTC, alessandrojean requested changes
Overall seems good now 👍🏻, just these minor things.

2023-10-25 18:14 UTC, alessandrojean commented on src/all/taddyink/build.gradle
> +    extName = 'Taddy INK (Webtoons)'
Can it be named like the site names itself, so it's less confusing for the final users? If yes, the same package name can be kept, doesn't need to change it. If not, there's no problem into keeping as it is.

```suggestion
    extName = 'Taddy'
```

2023-10-25 18:14 UTC, alessandrojean commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyInk.kt
> +    override val name = "Taddy INK (Webtoons)"
Same here if accepted.

```suggestion
    override val name = "Taddy"
```

2023-10-25 18:14 UTC, alessandrojean commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyUtils.kt
> +        }?.joinToString(", ")
```suggestion
        val genres = comicObj.genres.orEmpty()
            .mapNotNull { genreMap[it] }
            .joinToString()
```

2023-10-25 18:14 UTC, alessandrojean commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyUtils.kt
> +        }?.joinToString(", ")
```suggestion
        val creators = comicObj.creators
            ?.mapNotNull { it.name }
            ?.joinToString()
```

2023-10-25 18:14 UTC, alessandrojean commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyUtils.kt
> +            creators?.takeIf { it.isNotBlank() }?.let { author = it }
I don't remember at the moment if `author` and `artist` accepts `null`. If it accepts:

```suggestion
            author = creators
```

If not:

```suggestion
            author = creators.orEmpty()
```

2023-10-26 07:07 UTC, dmathewwws commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyInk.kt
> +    override val name = "Taddy INK (Webtoons)"
I would prefer to keep Taddy INK (Webtoons) vs Taddy.

2023-10-27 00:47 UTC, alessandrojean commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyUtils.kt
> +            creators?.takeIf { it.isNotBlank() }?.let { author = it }
It will be set as Unknown if the user manually refreshes the details, so this isn't much of an issue.

2023-10-27 01:36 UTC, dmathewwws commented on src/all/taddyink/src/eu/kanade/tachiyomi/extension/all/taddyink/TaddyUtils.kt
> +            creators?.takeIf { it.isNotBlank() }?.let { author = it }
I tested refreshing, and it keeps the old value. Maybe I missed a case on how to refresh.

But right now the main screen gets the creator name, you go to the comic (and you see the creator name), you pull to reload (and the creator name stays)

2023-10-27 14:16 UTC, merged

2023-10-27 22:49 UTC, dmathewwws commented
🙌