New Source: One Piece Berwarna
tachiyomiorg/tachiyomi-extensions pull request #18747
Opened 2023-10-27 01:18 UTC by Rewtio

Close #16710

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2023-10-27 13:12 UTC, Riztard commented on src/id/onepieceberwarna/src/eu/kanade/tachiyomi/extension/id/onepieceberwarna/OnePieceBerwarna.kt
> +        return document.select(".entry-content img")
```suggestion
        return document.select(".entry-content img:not(a > img):is([data-src])")
```
can filter non manga img entirely with css selector instead or something similar

2023-10-27 13:20 UTC, Riztard commented on src/id/onepieceberwarna/src/eu/kanade/tachiyomi/extension/id/onepieceberwarna/OnePieceBerwarna.kt
> +                element.select(".elementor-widget-container > img").let {
```suggestion
                element.select(".elementor-widget-container > img[data-src]").let {
```
ini juga kenapa ga begini aja daripada ngecek pake IF

2023-10-27 13:28 UTC, Riztard commented on src/id/onepieceberwarna/src/eu/kanade/tachiyomi/extension/id/onepieceberwarna/OnePieceBerwarna.kt
> +                author = title.substringAfter("to")
```suggestion
                author = "Eichiro Oda"
```
hardcode aja yang ini mah, 1 manga doang juga

2023-10-27 13:30 UTC, Riztard commented on src/id/onepieceberwarna/src/eu/kanade/tachiyomi/extension/id/onepieceberwarna/OnePieceBerwarna.kt
> +            }
```suggestion
            author = "Eichiro Oda"
```
harcode aja yang ini mah, manganya cuma 1 doang juga

2023-10-27 13:37 UTC, Rewtio commented on src/id/onepieceberwarna/src/eu/kanade/tachiyomi/extension/id/onepieceberwarna/OnePieceBerwarna.kt
> +            }
Iya juga, sempet kepikiran mau hardcode tapi malah nggak jadi

2023-10-28 01:16 UTC, Riztard commented on src/id/onepieceberwarna/src/eu/kanade/tachiyomi/extension/id/onepieceberwarna/OnePieceBerwarna.kt
> +        return document.select(".entry-content img")
`rel` adanya di `a` kan ya itu sama exclude

2023-10-28 01:44 UTC, Rewtio commented on src/id/onepieceberwarna/src/eu/kanade/tachiyomi/extension/id/onepieceberwarna/OnePieceBerwarna.kt
> +        return document.select(".entry-content img")
ada beberapa ads yang nggak masuk ke `a > img` tapi semua ads pake parent `rel` jadi saya pake `rel`

2023-10-28 01:51 UTC, Riztard commented on src/id/onepieceberwarna/src/eu/kanade/tachiyomi/extension/id/onepieceberwarna/OnePieceBerwarna.kt
> +        return document.select(".entry-content img")
kalo ini di ilangin `>` masuk tak

2023-10-28 02:12 UTC, Rewtio commented on src/id/onepieceberwarna/src/eu/kanade/tachiyomi/extension/id/onepieceberwarna/OnePieceBerwarna.kt
> +        return document.select(".entry-content img")
oh iya, bisa kalo dihilangin `>` nya

2023-10-28 15:42 UTC, alessandrojean requested changes

2023-10-28 15:42 UTC, alessandrojean commented on src/id/onepieceberwarna/src/eu/kanade/tachiyomi/extension/id/onepieceberwarna/OnePieceBerwarna.kt
> +        artist = "Shuesha™"
Shueisha isn't the artist.

```suggestion
```

2023-10-28 15:42 UTC, alessandrojean commented on src/id/onepieceberwarna/src/eu/kanade/tachiyomi/extension/id/onepieceberwarna/OnePieceBerwarna.kt
> +        author = "Eichiro Oda©"
```suggestion
        author = "Eiichiro Oda"
```

2023-10-28 15:42 UTC, alessandrojean commented on src/id/onepieceberwarna/src/eu/kanade/tachiyomi/extension/id/onepieceberwarna/OnePieceBerwarna.kt
> +    override fun chapterFromElement(element: Element) = throw UnsupportedOperationException("Not used")
Use the proper methods for parsing the HTML. Can override the `chapterListParse` to return `super.chapterListParse().reversed()`.

2023-10-28 20:51 UTC, Rewtio commented on src/id/onepieceberwarna/src/eu/kanade/tachiyomi/extension/id/onepieceberwarna/OnePieceBerwarna.kt
> +    override fun chapterFromElement(element: Element) = throw UnsupportedOperationException("Not used")
i can't do that, since we have to take `manga.url` for `section` id

2023-10-28 20:54 UTC, alessandrojean commented on src/id/onepieceberwarna/src/eu/kanade/tachiyomi/extension/id/onepieceberwarna/OnePieceBerwarna.kt
> +    override fun chapterFromElement(element: Element) = throw UnsupportedOperationException("Not used")
Just pass it as the URL fragment and access it through chapterListParse. It's better than having to deal with Observables directly.

2023-10-28 21:26 UTC, Rewtio commented on src/id/onepieceberwarna/src/eu/kanade/tachiyomi/extension/id/onepieceberwarna/OnePieceBerwarna.kt
> +    override fun chapterFromElement(element: Element) = throw UnsupportedOperationException("Not used")
will this be enough?
```kotlin


    override fun chapterListSelector(): String = "section[data-id=${'$'}] .elementor-text-editor strong > a"

    override fun fetchChapterList(manga: SManga): Observable<List<SChapter>> = Single.create {
        val response = client.newCall(GET(baseUrl, headers)).execute()
        val doc = response.asJsoup()

        it.onSuccess(
            // get section base on data-id stored in manga.url
            doc.select(chapterListSelector().format(manga.url))
                .map { element -> chapterFromElement(element) }
                .reversed()
        )
    }.toObservable()

    override fun chapterFromElement(element: Element): SChapter = SChapter.create().apply {
        name = element.text()
        setUrlWithoutDomain(element.attr("href"))
    }
```

2023-10-28 22:28 UTC, alessandrojean commented on src/id/onepieceberwarna/src/eu/kanade/tachiyomi/extension/id/onepieceberwarna/OnePieceBerwarna.kt
> +    override fun chapterFromElement(element: Element) = throw UnsupportedOperationException("Not used")
More like this:

```kotlin
override fun chapterListRequest(manga: SManga) = GET("$baseUrl/#${manga.url}", headers)

override fun chapterListParse(response: Response): List<SChapter> {
    val document = response.asJsoup()

    val dataId = response.request.url.fragment!!
    val selector = chapterListSelector().replace("%dataId", dataId)

    return document.select(selector)
        .map(::chapterFromElement)
}

override fun chapterListSelector(): String = "section[data-id=%dataId] .elementor-text-editor strong > a"

override fun chapterFromElement(element: Element): SChapter = SChapter.create().apply {
    name = element.text()
    setUrlWithoutDomain(element.attr("href"))
}
```

2023-10-28 22:56 UTC, Rewtio commented on src/id/onepieceberwarna/src/eu/kanade/tachiyomi/extension/id/onepieceberwarna/OnePieceBerwarna.kt
> +    override fun chapterFromElement(element: Element) = throw UnsupportedOperationException("Not used")
can i use `String.format`, it seems faster and neater than `String.replace`

2023-10-28 22:57 UTC, alessandrojean commented on src/id/onepieceberwarna/src/eu/kanade/tachiyomi/extension/id/onepieceberwarna/OnePieceBerwarna.kt
> +    override fun chapterFromElement(element: Element) = throw UnsupportedOperationException("Not used")
Sure.

2023-10-28 23:26 UTC, Rewtio commented
@alessandrojean Thank you for the suggestion changes, it helped me to understand more about the code base, 
If there are any changes that I can make, I will gradly change it

2023-10-28 23:28 UTC, merged