New Source: Project Suki
tachiyomiorg/tachiyomi-extensions pull request #18774
Opened 2023-10-28 15:08 UTC by npgx

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

Related Issues:
#6275 - mentions Project Suki
#6804 - mentions Project Suki

Comment:
I've tested the extension for a reasonable amount of mangas, everything seems to be working.
Latest isn't supported because Project Suki doesn't exactly differentiate between trending, latest etc... in the main page.
Basic idea is to just grab all the mangas by url and figure out the thumbnail and title.

2023-10-28 15:37 UTC, alessandrojean requested changes

2023-10-28 15:37 UTC, alessandrojean commented on src/all/projectsuki/src/eu/kanade/tachiyomi/extension/all/projectsuki/NormalizedURL.kt
> +data class NormalizedURL(
Why having all this work instead of just using OkHttp's `HttpUrl` builder?

2023-10-28 15:37 UTC, alessandrojean commented on src/all/projectsuki/src/eu/kanade/tachiyomi/extension/all/projectsuki/ProjectSuki.kt
> +    override val lang: String = PS.lang
Doesn't need to have these constants, just put it directly like all sources do.

2023-10-28 15:37 UTC, alessandrojean commented on src/all/projectsuki/src/eu/kanade/tachiyomi/extension/all/projectsuki/ProjectSuki.kt
> +        .processLangPref()
Using it like this will require users restarting the app to the settings to apply. Use this instead:

```suggestion
    private val SharedPreferences.whitelistedLanguages: List<String>
        get() = getString(PS.PREFERENCE_WHITELIST_LANGUAGES, "")!!
            .processLangPref()
```

Then use it as `preferences.whitelistedLanguages`.

2023-10-28 15:37 UTC, alessandrojean commented on src/all/projectsuki/src/eu/kanade/tachiyomi/extension/all/projectsuki/ProjectSuki.kt
> +        .processLangPref()
Same here.

2023-10-28 15:37 UTC, alessandrojean commented on src/all/projectsuki/src/eu/kanade/tachiyomi/extension/all/projectsuki/ProjectSuki.kt
> +                }
Can remove as the suggested extension function will already have the most updated value.

```suggestion
```

2023-10-28 15:37 UTC, alessandrojean commented on src/all/projectsuki/src/eu/kanade/tachiyomi/extension/all/projectsuki/ProjectSuki.kt
> +                }
Same here.

```suggestion
```

2023-10-28 15:37 UTC, alessandrojean commented on src/all/projectsuki/src/eu/kanade/tachiyomi/extension/all/projectsuki/ProjectSuki.kt
> +        debug { "INIT -> OkHttpClient" }
Remove these log statements. Also the client doesn't need to be build by lazy.

2023-10-28 15:37 UTC, alessandrojean commented on src/all/projectsuki/src/eu/kanade/tachiyomi/extension/all/projectsuki/ProjectSuki.kt
> +            },
Can use `mapOf`.

```suggestion
            mapOf(
                "bookid" to bookid,
                "chapterid" to chapterid,
                "first" to "true",
            ),
```

2023-10-28 15:51 UTC, npgx commented on src/all/projectsuki/src/eu/kanade/tachiyomi/extension/all/projectsuki/NormalizedURL.kt
> +data class NormalizedURL(
honestly, never used OkHttp, I could change it.
I assume you're saying it because OkHttp can normalize Urls?

2023-10-28 15:55 UTC, alessandrojean commented on src/all/projectsuki/src/eu/kanade/tachiyomi/extension/all/projectsuki/NormalizedURL.kt
> +data class NormalizedURL(
It is supposed to do, yes.

2023-10-28 16:39 UTC, npgx commented on src/all/projectsuki/src/eu/kanade/tachiyomi/extension/all/projectsuki/NormalizedURL.kt
> +data class NormalizedURL(
I tested it on a couple of mangas and it seems to be working

2023-10-28 17:02 UTC, npgx commented
One thing to note:
when searching for mangas, it will always report that there are "no results found" when scrolling to the end of the results.
On projectsuki there is always a "next" page button when there's at least one manga in the current window, even if the next page will have 0 results, as such hasNextPage is always true when creating the MangasPage for the search results.

Any clues on how to fix this?
(there always seem to be 30 manga in a full results page, but that could be changes easily and there could still be 0 results in the following page even if the current one has 30 mangas)

2023-10-28 17:27 UTC, alessandrojean commented
No problem with it, you can make it return false if the length of the page <= 30 and it's fine as well. The button always appearing on the site is something they need to fix.

2023-10-28 17:47 UTC, npgx commented
A single request to a very generic search like 'a' would give you the updated max number of results in the page, but that wouldn't fix the edge case where the current page is full and the next one is empty, so 30 is good-enough.

2023-10-28 22:31 UTC, alessandrojean reviewed
Seems okay now, just need to remove all the `Log` and `debug` statements, otherwise they will end up appearing in the crash logs and that's not desired.

2023-10-29 11:39 UTC, npgx commented
Tested and everything seems to _still_ be working

2023-10-31 17:13 UTC, npgx commented
Found some edge cases where title shows up as "show more", thought I fixed them, will investigate.

2023-11-02 01:10 UTC, merged