HeanCMS: Added paid chapter preference
tachiyomiorg/tachiyomi-extensions pull request #19006
Opened 2023-11-16 21:38 UTC by buhbbl

I noticed that the new updated removed all paid chapters and I have now added a preference that allows the user to choose if they want paid chapters or not. 

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2023-11-16 22:28 UTC, alessandrojean requested changes

2023-11-16 22:28 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/heancms/HeanCms.kt
> +            title = "Display Paid Chapters"
Please use the `HeanCmsIntl` class for strings.

2023-11-16 22:28 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/heancms/HeanCms.kt
> +    private val SharedPreferences.showPaidChap: Boolean
```suggestion
    private val SharedPreferences.showPaidChapters: Boolean
```

2023-11-16 22:28 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/heancms/HeanCms.kt
> +            .filter { it.price == 0 || preferences.showPaidChap }
Get the value outside the filter and save it in a local variable, otherwise you will be accessing the preferences for each item and it's not optimized.

2023-11-16 22:29 UTC, alessandrojean commented
Also worth noting you might be better adding a visual indication to the paid chapters on the title (such as a lock emoji 🔒) and check if the user has bought the chapter before requesting its pages as well.

2023-11-17 19:52 UTC, buhbbl commented
> check if the user has bought the chapter before requesting its pages as well.

I am not entirely sure if its easy to check if the user has bought the chapter as for example in the new query endpoint (using omegascans as an example) the auth api endpoint has 2 entries (1 for patreon account and 1 for bought chapters) and without actually buying a chapter I am not sure how I can test this out. 

Any recommendations?

2023-11-17 20:02 UTC, bapeey commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/heancms/HeanCmsIntl.kt
> +    }
Spanish translations:
Title: `Mostrar capítulos de pago`
SummaryOn: `Se mostrarán capítulos de pago. Deberá iniciar sesión`
SummaryOff: `Solo se mostrarán los capítulos gratuitos`

2023-11-17 23:47 UTC, alessandrojean commented
What currently happens if you try to read a paid chapter in the extension?

2023-11-18 08:07 UTC, buhbbl commented
Currently when a paid chapter is requested, the images are scraped from the chapter url and in case of paid chapters, no images are found so a toast is generated by tachiyomi which says that no chapters are found. And automatically checking if pages of all paid chapters are accessible might slow down the app.

2023-11-18 13:01 UTC, alessandrojean commented
You can change the parsing to include a `#paid` in the paid chapter URLs and then in the pageListParse check if it's empty and `response.request.url.fragment == "paid"` and if yes throw a custom localized error mentioning it's paid. Seems the better approach.

2023-11-18 14:47 UTC, bapeey commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/heancms/HeanCmsIntl.kt
> +    }
`SPANISH -> "Capítulo no disponible. Debe iniciar sesión en Webview y tener el capítulo comprado."`

2023-11-18 17:34 UTC, bapeey commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/heancms/HeanCmsDto.kt
> +        val paidStatus = price?.let { "-paid" } ?: ""
If `price = 0`, it will be added anyway, check if it is different from 0

2023-11-18 17:41 UTC, bapeey commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/heancms/HeanCmsDto.kt
> +        val paidStatus = price?.let { "-paid" } ?: ""
Also in [line 467](https://github.com/tachiyomiorg/tachiyomi-extensions/pull/19006/files#diff-483955e5d02495f745a2cc49a874aac9a6bedea7131bf85c8384170451270e5cR467), change to:
```kotlin
val chapterId = url.substringAfterLast("#").substringBefore("-paid")
```

2023-11-18 17:47 UTC, buhbbl commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/heancms/HeanCmsDto.kt
> +        val paidStatus = price?.let { "-paid" } ?: ""
Yea missed that, had forgotten how the ternary operator was in kotlin. Thanks!

2023-11-18 17:57 UTC, bapeey commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/heancms/HeanCmsDto.kt
> +        val paidStatus = if (price != 0) "-paid" else ""
In this way `"-paid"` will be added if `price = null`. I would do
```kotlin
price?.takeIf{ it != 0 }?.let { "-paid" } ?: ""
```

2023-11-20 16:41 UTC, merged