Fix the problem that the GSON dependency brought by the JWT library causes the APP to crash
tachiyomiorg/tachiyomi-extensions pull request #19400
Opened 2023-12-23 09:51 UTC by YangHgRi

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

2023-12-23 14:12 UTC, TheKingTermux reviewed
You forget to bump extVersionCode

~~extVersionCode = 2~~
extVersionCode = 3

Then add this to your Checklist
> Closes #19394

Then check this
> [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")

You also forget to check this because you forget to bump extVersionCode
> [x] Updated `extVersionCode` value in `build.gradle` for individual extensions

You can uncheck this because the Name, Theme or Language didn't change
> [ ] Have explicitly kept the 'id' if a source's name or language were changed

You can uncheck this too because it aleardy on that extension 
> [ ] Added the `isNsfw = true` flag in `build.gradle` when appropriate

2023-12-23 14:36 UTC, YangHgRi commented
> You forget to bump extVersionCode
> 
> ~extVersionCode = 2~ extVersionCode = 3
> 
> Then add this to your Checklist
> 
> > Closes #19394
> 
> Then check this
> 
> > * [x]  Referenced all related issues in the PR body (e.g. "Closes #xyz")
> 
> You also forget to check this because you forget to bump extVersionCode
> 
> > * [x]  Updated `extVersionCode` value in `build.gradle` for individual extensions
> 
> You can uncheck this because the Name, Theme or Language didn't change
> 
> > * [ ]  Have explicitly kept the `id` if a source's name or language were changed
> 
> You can uncheck this too because it aleardy on that extension
> 
> > * [ ]  Added the `isNsfw = true` flag in `build.gradle` when appropriate

got it

2023-12-24 23:55 UTC, arkon requested changes

2023-12-24 23:55 UTC, arkon commented on src/zh/picacomic/src/eu/kanade/tachiyomi/extension/zh/picacomic/Picacomic.kt
> +    @RequiresApi(Build.VERSION_CODES.O)
Can't do this, this will crash on older versions. If you need `Base64`, use https://developer.android.com/reference/android/util/Base64

2023-12-25 03:20 UTC, YangHgRi commented on src/zh/picacomic/src/eu/kanade/tachiyomi/extension/zh/picacomic/Picacomic.kt
> +    @RequiresApi(Build.VERSION_CODES.O)
> Can't do this, this will crash on older versions. If you need `Base64`, use https://developer.android.com/reference/android/util/Base64

got fixed in latest commit, thank u, as u see, i'm a beginner for android development

2023-12-26 11:27 UTC, merged