[WIP] lib-themesources
tachiyomiorg/tachiyomi-extensions pull request #5154
Opened 2020-12-16 12:14 UTC by AriaMoradi

This is my attempt at continuing what @SnakeDoc83 did in [his library branch](https://github.com/SnakeDoc83/tachiyomi-extensions/tree/library) and relates to #4287

2020-12-16 13:16 UTC, AriaMoradi commented
Here are few problems and ideas with this solution:
1- each source must use the exact same code as the general implementation, This current implementation does not support source overrides, they must be added after sources are generated.
2- since sources are generated they should be gitignored and generated at build time.

2020-12-16 17:18 UTC, AriaMoradi commented
can be merged now.

2020-12-16 17:22 UTC, AriaMoradi commented
One idea that I explored(and works) is putting generated extensions in a directory other than `src` like `srcgen`.
the only thing that needs to be changed for it to work might be github actions.

It might make things cleaner considering how big madara(and other multisource extensions) are.
opinions?

2020-12-16 17:46 UTC, arkon commented
Yes, having a separate `generated-src` folder or something would be preferable, then we can gitignore it as well.

I'll review this at some point after that's changed so the PR doesn't include the generated contents' diffs too.

2020-12-16 17:58 UTC, AriaMoradi commented
> Yes, having a separate generated-src folder or something would be preferable, then we can gitignore it as well.

gitignoring it is not a good idea, if we want to generate on every build two things need to be done, 1- somekind of tool to get you autogen 2- a framework to handle overrides 3- somewhere to put icons

also a big bad point even after doing it is that it makes the library heavy and centralized for no good reason.
If we need to change `themesource`'s API it's going to need more changes(sometimes less)

2020-12-16 20:04 UTC, AriaMoradi commented
overrides done.

but for automatic builds I couldn't figure it out completely:

3 steps are needed:(I got stuck on step 3)
1- build the library: `./gradlew :lib-themesources:generateDebugSources :lib-themesources:generateDebugAndroidTestSources :lib-themesources:createMockableJar :lib-themesources:compileDebugAndroidTestSources :lib-themesources:compileDebugUnitTestSources :lib-themesources:compileDebugSources`
2- collect all Generator files: is not too hard
3- run Generator files: to do this 3 things are needed: 1- jre path 2- java classpath 3- Generator className

Also my research suggests that it should be possible to do with gradle, but I couldn't fine any resources describing a working solution.

2020-12-16 20:26 UTC, AriaMoradi commented
Can I get a github project/milestone for spiting multi-source extensions?

2020-12-16 21:41 UTC, arkon commented
> Can I get a github project/milestone for spiting multi-source extensions?

I think you should be able to have your own projects in your fork.

2020-12-17 10:42 UTC, AriaMoradi commented
> 2- collect all Generator files: is not too hard

`GeneratorMain` does this. Only running this file remains.

2020-12-17 12:03 UTC, AriaMoradi commented
ready for review

2020-12-17 22:48 UTC, AriaMoradi commented
so far trying to re-create the class path I've come with this gradle task:
```gradle
tasks.register("findjars") {
    doLast {
        "$androidSDK/platforms/android-29/android.jar"
        "$androidSDK/platforms/android-29/data/res"
        "$projectRoot/lib/themesources/build/intermediates/javac/debug/classes"
        "$projectRoot/lib/themesources/build/intermediates/compile_r_class_jar/debug/R.jar"
        "$projectRoot/lib/thzemesources/build/tmp/kotlin-classes/debug"
        "$projectRoot/lib/themesources/build/generated/res/resValues/debug"

        var classPath = ""

        configurations.debugCompileOnly.asFileTree.forEach { classPath = "$classPath$it:" }
```

to complete this I need to 1- find the path for android sdk(or where android platform we are building for is) 2- get the project root path(or this module path)

2020-12-17 23:29 UTC, AriaMoradi commented
I tried the installed jre(openjdk 8) on my system and it worked!

so this is the new gradle task:

```gradle
tasks.register("classpath") {
    doLast {
        // android sdk dir is not documented but this hidden api gets it
        // ref: https://stackoverflow.com/questions/20203787/access-sdk-dir-value-in-build-gradle-after-project-evaluation
        val androidSDK = "${android.sdkDirectory.absolutePath}"

        val projectRoot = rootProject.projectDir

        var classPath = ""
        classPath += "$androidSDK/platforms/android-29/android.jar:"
        classPath += "$androidSDK/platforms/android-29/data/res:"
        classPath += "$projectRoot/lib/themesources/build/intermediates/javac/debug/classes:"
        classPath += "$projectRoot/lib/themesources/build/intermediates/compile_r_class_jar/debug/R.jar:"
        classPath += "$projectRoot/lib/themesources/build/tmp/kotlin-classes/debug:"
        classPath += "$projectRoot/lib/themesources/build/generated/res/resValues/debug"

        configurations.debugCompileOnly.asFileTree.forEach { classPath = "$classPath:$it" }

        val javaPath = System.getProperty("java.home") + "/bin/java"

        val mainClass = "eu.kanade.tachiyomi.lib.themesources.GeneratorMain"

        println("$javaPath -classpath $classPath $mainClass")
}
```

2020-12-17 23:53 UTC, AriaMoradi commented
> now just running
> 
> ```shell
> $ $(./gradlew -q :lib-themesources:classpath)
> ```
> 
> works fine.

this is the final form

```gradle
tasks.register("runAllGenerators") {
    doLast {
        // android sdk dir is not documented but this hidden api gets it
        // ref: https://stackoverflow.com/questions/20203787/access-sdk-dir-value-in-build-gradle-after-project-evaluation
        val androidSDK = "${android.sdkDirectory.absolutePath}"

        val projectRoot = rootProject.projectDir

        var classPath = ""
        classPath += "$androidSDK/platforms/android-29/android.jar:"
        classPath += "$androidSDK/platforms/android-29/data/res:"
        classPath += "$projectRoot/lib/themesources/build/intermediates/javac/debug/classes:"
        classPath += "$projectRoot/lib/themesources/build/intermediates/compile_r_class_jar/debug/R.jar:"
        classPath += "$projectRoot/lib/themesources/build/tmp/kotlin-classes/debug:"
        classPath += "$projectRoot/lib/themesources/build/generated/res/resValues/debug"

        configurations.debugCompileOnly.asFileTree.forEach { classPath = "$classPath:$it" }

        val javaPath = System.getProperty("java.home") + "/bin/java"

        val mainClass = "eu.kanade.tachiyomi.lib.themesources.GeneratorMain"

        Runtime.getRuntime().exec("$javaPath -classpath $classPath $mainClass")
    }
}
```

2020-12-17 23:56 UTC, AriaMoradi commented
Now changing githib workflows to run `:lib-themesources:runAllGenerators`
@arkon can you do this part please?

2020-12-18 00:08 UTC, AbdullahM0hamed commented
> Now changing github workflows to run :lib-themesources:runAllGenerators the only thing left to be done.
arkon can you do this part please?

Why not just change the work flow as part of your PR?

2020-12-18 00:10 UTC, AriaMoradi commented
> Why not just change the work flow as part of your PR?

I don't have access to github secrets but I'll try

2020-12-18 00:17 UTC, AbdullahM0hamed commented
> I don't have access to github secrets and work flows are not transferable.

You can create secrets for your fork though, right? I think you should be able to do it that way

2020-12-18 00:18 UTC, AriaMoradi commented
> You can create secrets for your fork though, right? I think you should be able to do it that way

and I dont have access to travis.

2020-12-18 00:23 UTC, AbdullahM0hamed commented
> I don't have access to travis

This shouldn't be a problem either, since we migrated from building via Travis to building via github actions (should be automatic, your fork is doing some right now: https://github.com/AriaMoradi/tachiyomi-extensions/actions)

2020-12-18 00:24 UTC, AriaMoradi commented
> > I don't have access to travis
> 
> This shouldn't be a problem either, since we migrated from building via Travis to building via github actions (should be automatic, your fork is doing some right now: https://github.com/AriaMoradi/tachiyomi-extensions/actions)

Yes. My fork was old. I try to do it myself.

2020-12-18 01:38 UTC, AriaMoradi commented
github workflows done too.

2020-12-18 01:38 UTC, AriaMoradi commented
this is ready for merge

2020-12-20 17:34 UTC, arkon requested changes
This is my first pass at comments. I'll need to look at the actual generator part later when I have more time.

2020-12-20 17:34 UTC, arkon commented on .github/workflows/build.yml
> +
The default assemble tasks should invoke this automatically, i.e. we should be able to just run the existing `assembleDebug` or `assembleRelease` tasks like before and have everything be built.

2020-12-20 17:34 UTC, arkon commented on lib/themesources/build.gradle.kts
> +}
We shouldn't be duplicating all of these configs across "normal" and the theme source module.

Maybe it can be moved into the core module from #5214.

2020-12-20 17:34 UTC, arkon commented on lib/themesources/build.gradle.kts
> +tasks.register("runAllGenerators") {
Is this complicated because of the need for the Android SDK? I would've expected some normal `JavaExec` task or something, with maybe some classpath config.

2020-12-20 17:34 UTC, arkon commented on lib/themesources/src/main/java/eu/kanade/tachiyomi/lib/themesources/genkan/GenkanGenerator.kt
> +    }
Rather than having this for every generator, maybe you can just make a base Launcher class that accept the generator class as an argument?

e.g. https://stackoverflow.com/questions/2988334/inheriting-the-main-method

2020-12-20 17:34 UTC, arkon commented on settings.gradle.kts
> +project(":lib-themesources").projectDir = File("lib/themesources")
I'd put this in a separate module since it isn't really a library used by the extensions, per se.

Something like `/compiler/themesources`?

2020-12-20 17:52 UTC, AriaMoradi commented on lib/themesources/build.gradle.kts
> +}
everything is compile only mind you.

2020-12-20 17:53 UTC, AriaMoradi commented on .github/workflows/build.yml
> +
Well I copied this from android studio logs, but yes `assembleDebug` worked. guess simpler config is better.

2020-12-20 17:56 UTC, AriaMoradi commented on lib/themesources/build.gradle.kts
> +tasks.register("runAllGenerators") {
Nope it wont work. I tried `JavaExec` and it can't see the libraries(classpath)
If you can make a equivalent working  `JavaExec` I'll change it

2020-12-20 17:57 UTC, AriaMoradi commented on lib/themesources/src/main/java/eu/kanade/tachiyomi/lib/themesources/genkan/GenkanGenerator.kt
> +    }
Doing it this way makes debugging and focusing on one Extension much much eaiser.

2020-12-20 17:58 UTC, AriaMoradi commented on lib/themesources/src/main/java/eu/kanade/tachiyomi/lib/themesources/genkan/GenkanGenerator.kt
> +    }
It acts as a scaffolding and building tool at the same time

2020-12-20 17:59 UTC, AriaMoradi commented on settings.gradle.kts
> +project(":lib-themesources").projectDir = File("lib/themesources")
You mean move the module directory?

2020-12-20 18:16 UTC, AriaMoradi commented on lib/themesources/build.gradle.kts
> +}
9 common dependencies. I'll change it after #5214

2020-12-20 18:42 UTC, AriaMoradi commented on lib/themesources/src/main/java/eu/kanade/tachiyomi/lib/themesources/genkan/GenkanGenerator.kt
> +    }
sometimes I run something like this do bypass having to sync every time:
`/opt/android-studio/jre/bin/java -javaagent:/opt/android-studio/lib/idea_rt.jar=45393:/opt/android-studio/bin -Dfile.encoding=UTF-8 -classpath /opt/Android-SDK/platforms/android-29/android.jar:/opt/Android-SDK/platforms/android-29/data/res:/home/armor/programming/android/tachiyomi-extensions/src/all/boommanga/build/intermediates/javac/debug/classes:/home/armor/programming/android/tachiyomi-extensions/src/all/boommanga//build/tmp/kotlin-classes/debug:/home/armor/programming/android/tachiyomi-extensions/src/all/boommanga/build/intermediates/compile_and_runtime_not_namespaced_r_class_jar/debug/R.jar:/home/armor/programming/android/tachiyomi-extensions/src/all/boommanga/build/generated/res/resValues/debug:/home/armor/.gradle/caches/modules-2/files-2.1/com.github.tachiyomiorg/extensions-lib/a596412/eaa76a7d8891fc26a3839d591d067e9d71a4aa2/extensions-lib-a596412.jar:/home/armor/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk8/1.4.10/998caa30623f73223194a8b657abd2baec4880ea/kotlin-stdlib-jdk8-1.4.10.jar:/home/armor/.gradle/caches/modules-2/files-2.1/com.github.inorichi.injekt/injekt-core/65b0440/63b7078668b1d86c7675e65082c9f56c6f5edfa/injekt-core-65b0440.jar:/home/armor/.gradle/caches/modules-2/files-2.1/com.squareup.okhttp3/okhttp/3.10.0/7ef0f1d95bf4c0b3ba30bbae25e0e562b05cf75e/okhttp-3.10.0.jar:/home/armor/.gradle/caches/modules-2/files-2.1/io.reactivex/rxjava/1.3.6/f8596dcb885d65c86f96cf96fe12772c56d51d1d/rxjava-1.3.6.jar:/home/armor/.gradle/caches/modules-2/files-2.1/org.jsoup/jsoup/1.10.2/33ee82e324f4b1e40167f3dc5e01234a1c5cab61/jsoup-1.10.2.jar:/home/armor/.gradle/caches/modules-2/files-2.1/com.github.salomonbrys.kotson/kotson/2.5.0/40daf22108aa4436d46257e14cc48447cca542c3/kotson-2.5.0.jar:/home/armor/.gradle/caches/modules-2/files-2.1/com.google.code.gson/gson/2.8.2/3edcfe49d2c6053a70a2a47e4e1c2f94998a49cf/gson-2.8.2.jar:/home/armor/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-jdk7/1.4.10/30e46450b0bb3dbf43898d2f461be4a942784780/kotlin-stdlib-jdk7-1.4.10.jar:/home/armor/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4.10/ea29e063d2bbe695be13e9d044dcfb0c7add398e/kotlin-stdlib-1.4.10.jar:/home/armor/.gradle/caches/modules-2/files-2.1/com.github.inorichi.injekt/injekt-api/65b0440/ff489b6dd4c80b8ace3c703f1d443aea08749f23/injekt-api-65b0440.jar:/home/armor/.gradle/caches/modules-2/files-2.1/com.squareup.okio/okio/1.14.0/102d7be47241d781ef95f1581d414b0943053130/okio-1.14.0.jar:/home/armor/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.4.10/6229be3465805c99db1142ad75e6c6ddeac0b04c/kotlin-stdlib-common-1.4.10.jar:/home/armor/.gradle/caches/modules-2/files-2.1/org.jetbrains/annotations/13.0/919f0dfe192fb4e063e7dacadee7f8bb9a2672a9/annotations-13.0.jar:/home/armor/programming/android/tachiyomi-extensions/defaultRes/build/intermediates/compile_r_class_jar/debug/R.jar:/home/armor/programming/android/tachiyomi-extensions/defaultRes/build/generated/res/resValues/debug:/home/armor/programming/android/tachiyomi-extensions/lib/themesources/build/intermediates/javac/debug/classes:/home/armor/programming/android/tachiyomi-extensions/lib/themesources/build/intermediates/compile_r_class_jar/debug/R.jar:/home/armor/programming/android/tachiyomi-extensions/lib/themesources/build/tmp/kotlin-classes/debug:/home/armor/programming/android/tachiyomi-extensions/lib/themesources/build/generated/res/resValues/debug:/home/armor/programming/android/tachiyomi-extensions/annotations/build/classes/kotlin/main:/home/armor/programming/android/tachiyomi-extensions/annotations/build/libs/annotations.jar:/home/armor/programming/android/tachiyomi-extensions/lib/duktape-stub/build/classes/java/main:/home/armor/programming/android/tachiyomi-extensions/lib/duktape-stub/build/libs/duktape-stub.jar:/home/armor/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-reflect/1.4.21/748f681f4e3edbe9285ff46710c79049c70f4dfa/kotlin-reflect-1.4.21.jar eu.kanade.tachiyomi.extension.all.boommanga.Inspector`

2020-12-20 21:55 UTC, arkon commented on settings.gradle.kts
> +project(":lib-themesources").projectDir = File("lib/themesources")
> You mean move the module directory?

Only for this module, since it's not a library (all of the existing ones are dependencies/functionality that extensions actually use, rather than a build tool).

2020-12-20 21:56 UTC, arkon commented on lib/themesources/src/main/java/eu/kanade/tachiyomi/lib/themesources/genkan/GenkanGenerator.kt
> +    }
Assuming each generator module has a respective build task, can't you just invoke that from the list of tasks in the Gradle pane?

I'm fine with keeping these if there's no clean way though, the run icon argument is fair.

2020-12-21 00:53 UTC, AriaMoradi commented on lib/themesources/src/main/java/eu/kanade/tachiyomi/lib/themesources/genkan/GenkanGenerator.kt
> +    }
Also when the library is frozen in the future and a extension needs something special, i.e. gradle extra dependencies, they can customize the behavior completely this way.

2020-12-21 01:06 UTC, AriaMoradi commented on settings.gradle.kts
> +project(":lib-themesources").projectDir = File("lib/themesources")
How about moving it to project root?

and rename it to to `multisource` or `multisrc` than `themesource`?
`multisrc` looks the best.

2020-12-21 03:33 UTC, arkon commented on settings.gradle.kts
> +project(":lib-themesources").projectDir = File("lib/themesources")
`multisrc` sounds fine.

2020-12-21 12:36 UTC, AriaMoradi commented on settings.gradle.kts
> +project(":lib-themesources").projectDir = File("lib/themesources")
everything moved to `multisrc`

2020-12-21 13:51 UTC, AriaMoradi commented on lib/themesources/build.gradle.kts
> +tasks.register("runAllGenerators") {
the problem is finding out if there's a way to calculate the classpath automatically
I found this https://stackoverflow.com/questions/51810254/execute-javaexec-task-using-gradle-kotlin-dsl

but sourceAets are moved to `project.android.sourceSets` and no longer include the classpath

2020-12-21 13:54 UTC, AriaMoradi commented on lib/themesources/build.gradle.kts
> +tasks.register("runAllGenerators") {
also this, but again doesn't work: https://stackoverflow.com/questions/54082700/run-gradle-task-javaexec-in-android-gradle-plagin

2020-12-21 14:59 UTC, AriaMoradi commented on lib/themesources/build.gradle.kts
> +tasks.register("runAllGenerators") {
I cleaned it up as much as possible

2021-01-01 22:20 UTC, arkon requested changes

2021-01-01 22:20 UTC, arkon commented on .github/workflows/build.yml
> +          configuration-cache-enabled: true
I commented on this last time too, but I mentioned that all of the new tasks should be run as part of the main `assemble*` (e.g. `assembleRelease`) tasks. The end result is that this workflow shouldn't change.

2021-01-01 22:20 UTC, arkon commented on multisrc/build.gradle.kts
> +    compileOnly(project(":duktape-stub"))
Why aren't these just in `common-dependencies.gradle`?

2021-01-01 22:20 UTC, arkon commented on multisrc/build.gradle.kts
> +        configurations.debugCompileOnly.get().asFileTree.forEach { classPath = "$classPath:$it" } // every dependency we have
You can make a list of the various things and join them with `:` rather than this string concatenation.

2021-01-01 22:20 UTC, arkon commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/GeneratorMain.kt
> +class GeneratorMain {
Does this work if the file just has the main function? I vaguely recall not needing the class or object at all in Kotlin, although I'm not sure if that's just because it "just works" in IntelliJ, or if invoking it via `java` actually works normally too.

2021-01-01 22:20 UTC, arkon commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/GeneratorMain.kt
> +            }
You could probably clean this up a lot, e.g. something like

```kotlin
File(sourcesDirPath).list()!!
  .filter { File(sourcesDir, it).isDirectory }
  .flatMap { 
    File("$sourcesDirPath/$themeSource").list()!!.filter {
      it.endsWith("Generator.kt")   
    }
  }
  .map { 
    val generatorClassPath =  "eu/kanade/tachiyomi/multisrc/$themeSource/$it".replace("/", ".").substringBefore(".kt") 
    Class.forName(generatorClassPath).methods
  }
  .filter { it.name == "main" }
  .forEach { it.invoke(null, emptyArray<String>()) }
```

2021-01-01 22:20 UTC, arkon commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/ThemeSourceGenerator.kt
> +            var text = "apply plugin: 'com.android.application'\n" +
You can do multiline strings in Kotlin. Same comment goes for other parts of this generator too.

2021-01-01 22:20 UTC, arkon commented on common.gradle
> +    implementation project(':multisrc')
What's the impact of this on the APK outputs?

2021-01-01 22:20 UTC, arkon commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/ThemeSourceGenerator.kt
> +             * a previous existing source suddenly needs overrides, overrideVersionCode should be increased.
Overrides for what? This JavaDoc isn't clear.

2021-01-01 22:20 UTC, arkon commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/ThemeSourceGenerator.kt
> +        abstract class ThemeSourceData {
You should use a sealed class for these.

2021-01-01 22:20 UTC, arkon commented on settings.gradle.kts
> +    // Loads generated extensions from multisrc
Indentation is off.

2021-01-02 01:36 UTC, AriaMoradi commented on .github/workflows/build.yml
> +          configuration-cache-enabled: true
what about `runAllGenerators`?

2021-01-02 01:38 UTC, arkon commented on .github/workflows/build.yml
> +          configuration-cache-enabled: true
The name doesn't matter too much, but the original assemble tasks should depend on your new ones.

The idea is that the same old "simple" build will still build everything in an idempotent fashion.

2021-01-02 01:48 UTC, AriaMoradi commented on multisrc/build.gradle.kts
> +    compileOnly(project(":duktape-stub"))
`implementation` vs `compileOnly`?

2021-01-02 01:51 UTC, AriaMoradi commented on multisrc/build.gradle.kts
> +        configurations.debugCompileOnly.get().asFileTree.forEach { classPath = "$classPath:$it" } // every dependency we have
it's a special kind of collection, I'm not sure how to convert it to a list?

2021-01-02 01:55 UTC, arkon commented on multisrc/build.gradle.kts
> +    compileOnly(project(":duktape-stub"))
2 of them _are_ in the other file though. The annotations bytecode is required for them to work too.

2021-01-02 01:59 UTC, AriaMoradi commented on common.gradle
> +    implementation project(':multisrc')
All multitheme libraries will be included as they are in the package, i suggested running proguard  to fix this with tree shaking .

it's probably possible to split them inside different gradle modules and include the proper theme class in each respective extension; though i suggest doing this later. it's not big enough yet to account to much.

2021-01-02 02:01 UTC, AriaMoradi commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/ThemeSourceGenerator.kt
> +             * a previous existing source suddenly needs overrides, overrideVersionCode should be increased.
each extension either uses the default generated code or a code override, look at `multisrc/overrides/src`

2021-01-02 02:03 UTC, AriaMoradi commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/GeneratorMain.kt
> +class GeneratorMain {
it worked.

2021-01-02 02:15 UTC, AriaMoradi commented on multisrc/build.gradle.kts
> +    compileOnly(project(":duktape-stub"))
sorry, i missed them.

2021-01-02 02:15 UTC, AriaMoradi commented on multisrc/build.gradle.kts
> +    compileOnly(project(":duktape-stub"))
fixed

2021-01-02 02:16 UTC, AriaMoradi commented on .github/workflows/build.yml
> +          configuration-cache-enabled: true
this probably can be fixed by a `dependsOn`, but I'm not sure where and on what it should be applied

2021-01-02 02:31 UTC, AriaMoradi commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/ThemeSourceGenerator.kt
> +        abstract class ThemeSourceData {
done.

2021-01-02 09:24 UTC, AriaMoradi commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/GeneratorMain.kt
> +            }
done

2021-01-02 10:31 UTC, AriaMoradi commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/ThemeSourceGenerator.kt
> +            var text = "apply plugin: 'com.android.application'\n" +
done

2021-01-02 11:03 UTC, AriaMoradi commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/ThemeSourceGenerator.kt
> +             * a previous existing source suddenly needs overrides, overrideVersionCode should be increased.
I made it clearer?

2021-01-08 10:44 UTC, AriaMoradi commented on common.gradle
> +    implementation project(':multisrc')
It's possible to copy the theme class (i.e. `Genkan` and `GenkanOriginal`) to the generated module and bundle it this way.

what do you think?

2021-01-09 09:26 UTC, AriaMoradi commented on common.gradle
> +    implementation project(':multisrc')
fixed in 0a11e72

2021-01-09 15:51 UTC, arkon commented on multisrc/build.gradle.kts
> +        minSdkVersion(29)
Why 29?

2021-01-09 16:09 UTC, arkon commented on .github/workflows/build.yml
> +          configuration-cache-enabled: true
I think having this in the root `build.gradle` file works:

```
task assemble {
    dependsOn(":multisrc:assemble")
}
```

2021-01-09 16:16 UTC, arkon commented on multisrc/build.gradle.kts
> +        configurations.debugCompileOnly.get().asFileTree.forEach { classPath = "$classPath:$it" } // every dependency we have
Something like this should work:

```
val classPath =
    // every dependency we have 
    configurations.debugCompileOnly.get().asFileTree + 
    listOf(
        // android.jar path
        configurations.androidApis.get().asFileTree.first().absolutePath,
        // jar made from this module
        "$projectDir/build/intermediates/aar_main_jar/debug/classes.jar"
    )
    .joinToString(":")
```

2021-01-09 17:41 UTC, AriaMoradi commented on multisrc/build.gradle.kts
> +        minSdkVersion(29)
because `java.nio.file.Files.copy` and this is essentially only a command line app only, so It's not important which api level it uses.

2021-01-09 20:40 UTC, AriaMoradi commented on .github/workflows/build.yml
> +          configuration-cache-enabled: true
This kind of solution won't work because even if somehow we call `:multisrc:assemble` then `:multisrc:runAllGenerators`, we must restart gradle because it has to read `settings.gradle.kts` again and find the generated modules, looks like there is no way to include projects in the middle of tasks running.

2021-01-09 20:40 UTC, AriaMoradi commented on multisrc/build.gradle.kts
> +        configurations.debugCompileOnly.get().asFileTree.forEach { classPath = "$classPath:$it" } // every dependency we have
done

2021-02-06 18:17 UTC, arkon requested changes
You'll need to fix the conflicts before I can merge this.

2021-02-06 21:42 UTC, AriaMoradi commented
It should be fine now.

2021-02-06 22:32 UTC, merged