Update Gmanga.kt
tachiyomiorg/tachiyomi-extensions pull request #5497
Opened 2021-01-20 18:28 UTC by ellpatron

fixing when hitting latest ---> getting jsonNull

2021-01-20 18:46 UTC, CarlosEsco commented
you need to update the build.gradle version also

2021-01-21 09:03 UTC, ellpatron commented
> you need to update the build.gradle version also

Sorry i forget thinks

2021-01-21 11:41 UTC, CarlosEsco requested changes

2021-01-21 11:41 UTC, CarlosEsco commented on src/ar/gmanga/build.gradle
> +    extVersionCode = 21
only bump it by one.  So this should be 3 now

2021-01-21 16:36 UTC, merged