MangAdventure split
tachiyomiorg/tachiyomi-extensions pull request #5667
Opened 2021-02-07 14:07 UTC by ObserverOfTime

Do not merge until the source generator supports URL intents.

2021-02-07 15:38 UTC, arkon commented
Were you planning on making the change to the generator, or hoping that @AriaMoradi does it?

2021-02-07 15:46 UTC, ObserverOfTime commented
I can do it next weekend if no one else does it by then.

2021-02-07 21:22 UTC, AriaMoradi commented
> They can be implemented as a list of `Triple(host, pathPattern, scheme)` in `ThemeSourceData` so the generator can add them to the manifest. `ThemeSourceData` will also need another field that declares the name of the activity class.

This multi-source is maybe the only one that needs this kind of feature so I'm against adding it to the library. 

> Also, it would be nice if the generator could replace hyphens and other invalid identifier characters in the name.

The Source name can be any string of Unicode characters,  and adding this feature doesn't seem wise to me, you can already provide pakage name and file(class) name overrides manually. 
Also src override gives you all the power you need to pull off this split. 
The `ThemeSource` just acts as a definition tool for sources which essentially replaces the factory class and it does a minimal source generation for sources that don't need overrides.

2021-02-07 21:36 UTC, arkon commented
> This multi-source is maybe the only one that needs this kind of feature so I'm against adding it to the library.

Are you saying this can be achieved with the overrides rather than having to modify the generator code, or are you against multi-source modules having the ability to handle intents?

2021-02-07 21:44 UTC, AriaMoradi commented
> > This multi-source is maybe the only one that needs this kind of feature so I'm against adding it to the library.
> 
> Are you saying this can be achieved with the overrides rather than having to modify the generator code, or are you against multi-source modules having the ability to handle intents?

Any shared source file should be put in the `multisrc.multisrcname` package and any source-specific code should be in the src override.
If you take a look at the logic, it copies any class file that doesn't end with `Generator.kt` (`ThemeSourceGenerator.kt` line 114)

2021-02-07 21:50 UTC, arkon commented
Sure, but it doesn't handle overriding the manifest, does it?

2021-02-07 21:54 UTC, AriaMoradi commented
> Sure, but it doesn't handle overriding the manifest, does it?

Ah, I completely forgot that manifest needs overrides to handle intents, oops.
we can add a `manifest` directory to `overrides` and handle it that way or put it in the src override directory and have the generator look for a manifest file?

2021-02-07 22:22 UTC, ObserverOfTime commented
That should work but you also need to handle the activity class.

2021-02-07 22:33 UTC, AriaMoradi commented
> That should work but you also need to handle the activity class.

Put inside `multisource.themename`? what's special about he activity class?

2021-02-07 22:57 UTC, ObserverOfTime commented
It just accepts the intent and sends it to the main app.

2021-02-07 23:10 UTC, AriaMoradi commented
> It just accepts the intent and sends it to the main app but it needs to be declared in `build.gradle`.

Noting is delared in https://github.com/tachiyomiorg/tachiyomi-extensions/blob/81f9eede50758261f46b888a518c126221860d74/src/all/mangadventure/build.gradle ?

2021-02-07 23:29 UTC, ObserverOfTime commented
Oh, right, it's in the manifest.

2021-02-10 11:06 UTC, ObserverOfTime commented
It should be ready to merge now.

2021-02-10 16:22 UTC, AriaMoradi requested changes

2021-02-10 16:22 UTC, AriaMoradi commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangadventure/MangAdventureGenerator.kt
> +        SingleLang("Arc-Relight", "https://arc-relight.com", "en", className = "ArcRelight"),
Only one source?!
Why are you doing multisrc then?!

2021-02-10 16:55 UTC, ObserverOfTime commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangadventure/MangAdventureGenerator.kt
> +        SingleLang("Arc-Relight", "https://arc-relight.com", "en", className = "ArcRelight"),
Only one source *now*. There was another one that changed to Madara and there may be more in the future.

2021-02-11 15:48 UTC, merged