Split WPMangaStream
tachiyomiorg/tachiyomi-extensions pull request #5803
Opened 2021-02-12 15:15 UTC by Riztard

2021-02-12 20:42 UTC, arkon requested changes

2021-02-12 20:42 UTC, arkon commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStream.kt
> +//import eu.kanade.tachiyomi.lib.ratelimit.RateLimitInterceptor
I'd rather we hold off on merging this until this can be addressed.

2021-02-14 09:03 UTC, Riztard commented
hold on i think i need to overwrite some extension id

2021-02-15 08:58 UTC, Riztard commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStream.kt
> +//import eu.kanade.tachiyomi.lib.ratelimit.RateLimitInterceptor
i put it in override

2021-02-15 15:43 UTC, merged