Mango: Add first working version
tachiyomiorg/tachiyomi-extensions pull request #6034
Opened 2021-03-02 06:37 UTC by goldbattle

Has browse, chapters, and searching.
The API endpoint is just the whole entire library, so searching is done locally.
Requires login authentication, so will need to view the webview first to login, then everything works as expected.
https://github.com/hkalexling/Mango/

2021-03-03 13:58 UTC, CarlosEsco requested changes

2021-03-03 13:58 UTC, CarlosEsco commented on src/all/mango/build.gradle
> +    implementation 'io.reactivex:rxjava:1.3.6'
are these reactive libraries actually needed?

2021-03-03 13:58 UTC, CarlosEsco commented on src/all/mango/src/eu/kanade/tachiyomi/extension/all/mango/Mango.kt
> +        // https://github.com/CarlosEsco/Neko/blob/987d1485203a1ec1b5037dcf9b4bdea24f2cf8a3/app/src/main/java/eu/kanade/tachiyomi/source/online/MergeSource.kt
don't need this comment

2021-03-03 13:58 UTC, CarlosEsco commented on src/all/mango/src/eu/kanade/tachiyomi/extension/all/mango/Mango.kt
> +                // chapter_number = obj["mtime"].asLong.toFloat()
remove comments

2021-03-06 02:57 UTC, goldbattle commented on src/all/mango/build.gradle
> +    implementation 'io.reactivex:rxjava:1.3.6'
Nope :)

2021-03-06 03:02 UTC, merged