LANraragi: Random item, clear new status
tachiyomiorg/tachiyomi-extensions pull request #6091
Opened 2021-03-08 01:17 UTC by RePod

- Adds a "Random" entry to popular's MangasPage, assuming nothing else prevents it.
 - Clears an archive's new status on the server similar to two versions ago before moving to API endpoints.
   - The web reader happened to be taking care of it

2021-03-08 10:48 UTC, CarlosEsco requested changes

2021-03-08 10:48 UTC, CarlosEsco commented on src/all/lanraragi/src/eu/kanade/tachiyomi/extension/all/lanraragi/LANraragi.kt
> +        if (tachiAZ == 0) tachiAZ = 2
find another way to do this, or PR az.  Extensions aren't having fork specific stuff

2021-03-08 21:30 UTC, RePod commented on src/all/lanraragi/src/eu/kanade/tachiyomi/extension/all/lanraragi/LANraragi.kt
> +        if (tachiAZ == 0) tachiAZ = 2
I'd be fine with reverting it. The PR and AZ will function without it just the AZ experience will be slightly off compared to the rest.

2021-03-09 22:48 UTC, arkon commented on src/all/lanraragi/src/eu/kanade/tachiyomi/extension/all/lanraragi/LANraragi.kt
> +        if (tachiAZ == 0) tachiAZ = 2
Should revert that, not worth the technical debt of dealing specifically with AZ.

2021-03-10 11:57 UTC, merged