Madara: add series type to genre, filter author & artist name
tachiyomiorg/tachiyomi-extensions pull request #6431
Opened 2021-04-05 14:24 UTC by Riztard

add series type(manga/manhwa/manhua/other)  thinggy to genre for some source
remove author & artist name if the name is "Updating"

2021-04-05 14:38 UTC, arkon commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> +    override val baseVersionCode: Int = 3
Please no

2021-04-05 14:46 UTC, Riztard commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> +    override val baseVersionCode: Int = 3
just putting it here until update all

2021-04-07 02:06 UTC, AriaMoradi requested changes

2021-04-07 02:06 UTC, AriaMoradi commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +            else if (!type.isNullOrEmpty() && !manga.genre.isNullOrEmpty()) ", $type" else if (!type.isNullOrEmpty() && manga.genre.isNullOrEmpty()) "$type" else ""
Maybe rewrite this with `when`?

2021-04-07 15:13 UTC, Riztard commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +            else if (!type.isNullOrEmpty() && !manga.genre.isNullOrEmpty()) ", $type" else if (!type.isNullOrEmpty() && manga.genre.isNullOrEmpty()) "$type" else ""
doesnt it take more space?

2021-04-07 15:18 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +            else if (!type.isNullOrEmpty() && !manga.genre.isNullOrEmpty()) ", $type" else if (!type.isNullOrEmpty() && manga.genre.isNullOrEmpty()) "$type" else ""
i would prefer something more readable

2021-04-08 11:10 UTC, CarlosEsco requested changes

2021-04-08 11:10 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +            if (!type.isNullOrEmpty() && !type.contains("Updating", true) && type == "-") {
my code above copied this and I was wondering why are you adding if the `type == "-"`

2021-04-08 11:10 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +            }
this also can be cleaned a little (I dont know why there is a ending else -> "")
```
 document.select(altNameSelector).firstOrNull()?.ownText()?.let{
     if(this.isEmpty().not() && this.notUpdating()){
         val altNameString = altName + altNameString
         manga.description = when {
             mangaDescription.isNullOrEmpty -> altNameString
             else -> "${manga.description}\n\n${altNameString}"
         }
     }
 }
```

2021-04-08 11:10 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +    open val altName = "Alternative Name: "
Is this open for foreign language versions to override?

2021-04-08 11:20 UTC, Riztard commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +            if (!type.isNullOrEmpty() && !type.contains("Updating", true) && type == "-") {
i think i saw some source fill it with `-`, or i remember it wrong

2021-04-08 11:22 UTC, Riztard commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +            }
just in case if there will be a case i cant predict 🤔

2021-04-08 11:22 UTC, Riztard commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +    open val altName = "Alternative Name: "
yes

2021-04-08 11:24 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +            }
but if description is null or empty,   or it has stuff are the only conditions on the description lol

2021-04-08 11:25 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +            if (!type.isNullOrEmpty() && !type.contains("Updating", true) && type == "-") {
shouldn't be type != "-" then?

2021-04-08 11:30 UTC, Riztard commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +            }
hmm true

2021-04-08 11:32 UTC, Riztard commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +            }
for cleaning, im not too familiar with let lol

2021-04-08 11:33 UTC, Riztard commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +            if (!type.isNullOrEmpty() && !type.contains("Updating", true) && type == "-") {
ah right

2021-04-08 14:51 UTC, CarlosEsco requested changes

2021-04-08 14:51 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +            manga.genre = genres.toList().joinToString(", ")
So if you need the contains check below.  then no reason to make this a mutableSet.  Or add them to the manga.genres here.   just do 
`val genres = select("div.genres-content a")
                .map { element -> element.text() }.toMutableList()`

2021-04-08 14:51 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +                if (!manga.genre!!.contains(element.text(), true)) {
`if(genres.contains(element.text(), true).not()){
    genres.add(element.text()
}`

2021-04-08 14:51 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +            manga.genre = genres.toList().joinToString(", ")
dont need

2021-04-08 14:51 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +            manga.genre = genres.toList().joinToString(", ")
this is the one you need.  No reason to keep setting manga.genres everytime
`manga.genre = genres.joinToString(", ")`

2021-04-08 14:51 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +                if (it.isEmpty().not() && it.notUpdating() && !manga.genre!!.contains(it, true) && it != "-") {
change order as its slightly less expensive
`if (it.isEmpty().not() && it.notUpdating() && it != "-" &&  !genres.contains(it, true))`

2021-04-08 14:51 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +            }
So problem with what you changed 
```
manga.description += when {
                        manga.description.isNullOrEmpty() -> altNameString
                        else -> "\n\n$altNameString"
                    }
```
this is going to add null + altname.  Which is why i wrote it how i did

2021-04-08 14:54 UTC, Riztard commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +            manga.genre = genres.toList().joinToString(", ")
just dont know how to check the mutable lol

2021-04-08 14:56 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +            manga.genre = genres.toList().joinToString(", ")
The above comment makes it mutable.
`val genres = select("div.genres-content a") .map { element -> element.text() }.toMutableList()`

after that point just keep checking and adding to that list.  Then when you are done join it the the manga.genre

2021-04-08 16:15 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +                if (it.isEmpty().not() && it.notUpdating() && it != "-" && genres.toString().contains(it, true).not()) {
same question as above

2021-04-08 16:17 UTC, Riztard commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/Madara.kt
> +                if (genres.toString().contains(element.text(), true).not()) {
if its a list, .contains cant use ignoreCase

2021-04-11 06:43 UTC, Riztard commented
now merge mwahaha

2021-04-11 12:52 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> +    override val baseVersionCode: Int = 3
Does this still need to update all them?

2021-04-11 13:18 UTC, Riztard commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/madara/MadaraGenerator.kt
> +    override val baseVersionCode: Int = 3
yes

2021-04-11 13:51 UTC, merged