removed void scans and helvetica scans
tachiyomiorg/tachiyomi-extensions pull request #6446
Opened 2021-04-06 21:21 UTC by OncePunchedMan

2021-04-06 22:09 UTC, arkon requested changes

2021-04-06 22:09 UTC, arkon commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/foolslide/FoolSlideGenerator.kt
> -        SingleLang("Helvetica Scans", "https://helveticascans.com", "en"),
Remove the override files too.

2021-04-07 02:16 UTC, jopejoe1 commented
Did i remove wrong void scan in #6421 ?

2021-04-07 02:27 UTC, arkon commented
> Did i remove wrong void scan in #6421 ?

@CrepeTF would need to confirm that since the removal issue didn't specify. Looks like this site is dead anyway though.

2021-04-07 07:47 UTC, OncePunchedMan commented
hm both voidscans and ntsvoidscans are non-reachable

2021-04-07 09:48 UTC, CrepeTF commented
> > Did i remove wrong void scan in #6421 ?
> 
> @CrepeTF would need to confirm that since the removal issue didn't specify. Looks like this site is dead anyway though.

Yep it's correct @arkon

2021-04-07 17:48 UTC, merged