add alternative name, cleaning some code
tachiyomiorg/tachiyomi-extensions pull request #6484
Opened 2021-04-09 09:34 UTC by Riztard

- add alternative name to manga description
- cleaning series type code

WPMangaReader: add alt name, cleaning
FMReader: add alt name
MangaPark: add alt name
WPMangaStream: add alt name, cleaning
MangaBox: add alt name
MaidManga: add alt name, cleaning
Komiku: cleaning code
ManhuaID: cleaning code

2021-04-09 11:47 UTC, CarlosEsco requested changes
So i do have 1 concern in addition.  I feel you are just copypasting the conditions, or your JSOUP selectors need tweaked, I find it weird all these unrelated sites would need to check for != "-" and they all would possibly already have the type in the genre

2021-04-09 11:47 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/fmreader/FMReader.kt
> +    open val altName = "Alternative Name"
there is no space here.  So its gonna concatenate  wrong `Alternative NameMy alt name`

2021-04-09 11:47 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangabox/MangaBox.kt
> +                        description.isNullOrEmpty() -> altName + it
same as above

2021-04-09 11:47 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/fmreader/FMReader.kt
> +                        else -> "\n\n$altName" + it
same as above

2021-04-09 11:47 UTC, CarlosEsco commented on multisrc/overrides/wpmangastream/westmanga/src/WestManga.kt
> +                        genre += if (genre.isNullOrEmpty()) it else ", $it"
same as above

2021-04-09 11:47 UTC, CarlosEsco commented on multisrc/overrides/wpmangastream/silencescan/src/SilenceScan.kt
> +                genre += if (genre.isNullOrEmpty()) it else ", $it"
Can genre even be null? If so then this just going to produce an edge case of
`nullManhua`

which is why i said on discord not to just add suspect code on suspect code :laughing: 

if it can't be null then just use isEmpty

genre += if(genre.isEmpty()) it else ", $it"

2021-04-09 11:47 UTC, CarlosEsco commented on multisrc/overrides/wpmangastream/silencescan/src/SilenceScan.kt
> +                }
same thing as above but for description

2021-04-09 11:47 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/nepnep/NepNep.kt
> +                        genre += if (genre.isNullOrEmpty()) it else ", $it"
same

2021-04-09 11:47 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/nepnep/NepNep.kt
> +                            else -> "\n\n$altName" + it
same as above

2021-04-09 11:47 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReader.kt
> +            }
same as above

2021-04-09 11:47 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReader.kt
> +                    else -> "\n\n$altName" + it
same as above

2021-04-09 11:47 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStream.kt
> +                    }
same as above for both these also

2021-04-09 11:47 UTC, CarlosEsco commented on src/en/mangapark/src/eu/kanade/tachiyomi/extension/en/mangapark/MangaPark.kt
> +                }
same

2021-04-09 11:47 UTC, CarlosEsco commented on src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt
> +                genre += if (genre.isNullOrEmpty()) it else ", $it"
same

2021-04-09 11:47 UTC, CarlosEsco commented on src/id/maidmanga/src/eu/kanade/tachiyomi/extension/id/maidmanga/MaidManga.kt
> +                    }
same for these

2021-04-09 11:47 UTC, CarlosEsco commented on src/id/manhuaid/src/eu/kanade/tachiyomi/extension/id/manhuaid/ManhuaID.kt
> +                genre += if (genre.isNullOrEmpty()) it else ", $it"
and finally this

2021-04-09 11:49 UTC, Riztard commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/fmreader/FMReader.kt
> +    open val altName = "Alternative Name"
well their alt name string is ": alt name"

2021-04-09 11:50 UTC, Riztard commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangabox/MangaBox.kt
> +                        description.isNullOrEmpty() -> altName + it
already add space in altName

2021-04-09 11:51 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/fmreader/FMReader.kt
> +    open val altName = "Alternative Name"
maybe comment that here then in code

2021-04-09 11:52 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangabox/MangaBox.kt
> +                        description.isNullOrEmpty() -> altName + it
i meant the null thing

2021-04-09 11:54 UTC, Riztard commented on multisrc/overrides/wpmangastream/silencescan/src/SilenceScan.kt
> +                genre += if (genre.isNullOrEmpty()) it else ", $it"
what is the default value for genre is it null or empty?

2021-04-09 11:55 UTC, Riztard commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangabox/MangaBox.kt
> +                        description.isNullOrEmpty() -> altName + it
should i just separate the space?to something like this? altname + " " + it

2021-04-09 11:58 UTC, CarlosEsco commented on multisrc/overrides/wpmangastream/silencescan/src/SilenceScan.kt
> +                genre += if (genre.isNullOrEmpty()) it else ", $it"
your the one who coded it, i assume you would know, i only reviewed what you changed.  Looking at the code
```
        genre = infoEl.select("b:contains(Gêneros) + span a").joinToString { it.text() }
        thumbnail_url = infoEl.select("div.thumb img").imgAttr()

        // add series type(manga/manhwa/manhua/other) thinggy to genre
        val seriesTypeSelector = ".imptdt:contains(Tipo) a, a[href*=type\\=]"
        document.select(seriesTypeSelector).firstOrNull()?.ownText()?.let {
            if (it.isEmpty().not() && it != "-" && genre!!.contains(it, true).not()) {
                genre += if (genre.isNullOrEmpty()) it else ", $it"
            }
        }

        // add alternative name to manga description
        document.select(altNameSelector).firstOrNull()?.ownText()?.let {
            if (it.isEmpty().not() && it !="N/A" && it != "-") {
                description += when {
                    description.isNullOrEmpty() -> altName + it
                    else -> "\n\n$altName" + it
                }
            }
        }
    }
```
It's empty

2021-04-09 12:03 UTC, Riztard commented
> So i do have 1 concern in addition. I feel you are just copypasting the conditions, or your JSOUP selectors need tweaked, I find it weird all these unrelated sites would need to check for != "-" and they all would possibly already have the type in the genre

ah for got to remove that, should be only for some source

2021-04-09 12:06 UTC, CarlosEsco commented on multisrc/overrides/wpmangastream/silencescan/src/SilenceScan.kt
> +                genre += if (genre.isNullOrEmpty()) it else ", $it"
`val seriesTypeSelector = ".imptdt:contains(Tipo) a, a[href*=type\\=]"` move out to a val outside of function

really should rewrite this though and add them all to a list 
`val genres = infoEl.select("b:contains(Gêneros) + span a")
document.select(seriesTypeSelector).firstOrNull()?.ownText()?.let {
            if (it.isEmpty().not()) {
                genres.add(it)
            }
        }
`

also this is why i question your selectors. 
![image](https://user-images.githubusercontent.com/2092019/114177361-5170c600-990a-11eb-9619-fb975ca15531.png)

2021-04-09 12:07 UTC, CarlosEsco commented
![image](https://user-images.githubusercontent.com/2092019/114177564-9137ad80-990a-11eb-8c27-f80c95674994.png)
Image again so its not lost. Also cursory glance, type isnt also in the genres field.  So its another check that not needed at least on this one

2021-04-09 12:13 UTC, Riztard commented on multisrc/overrides/wpmangastream/silencescan/src/SilenceScan.kt
> +                genre += if (genre.isNullOrEmpty()) it else ", $it"
> It's empty

ah right null only happen if select something

> also this is why i question your selectors

what? 🤔

2021-04-09 12:15 UTC, Riztard commented
> ![image](https://user-images.githubusercontent.com/2092019/114177564-9137ad80-990a-11eb-8c27-f80c95674994.png)
> Image again so its not lost. Also cursory glance, type isnt also in the genres field. So its another check that not needed at least on this one

some source have it in genre and type

2021-04-09 12:18 UTC, CarlosEsco commented on multisrc/overrides/wpmangastream/silencescan/src/SilenceScan.kt
> +                genre += if (genre.isNullOrEmpty()) it else ", $it"
basically for example in this scenario.  Why does the selector have , a[href*=type\\=]
why is it checking for -
why is it checking if the genre String already has it already.

2021-04-09 12:18 UTC, CarlosEsco commented
> 
> 
> > ![image](https://user-images.githubusercontent.com/2092019/114177564-9137ad80-990a-11eb-8c27-f80c95674994.png)
> > Image again so its not lost. Also cursory glance, type isnt also in the genres field. So its another check that not needed at least on this one
> 
> some source have it in genre and type
> *oh wait nvm, "on this one"

if some sources have it on both, why do you need to even add the type, if it will be in the genre already

2021-04-09 12:25 UTC, Riztard commented
> if some sources have it on both, why do you need to even add the type, if it will be in the genre already

pretty sure thats a human error
because that only happen to some manga but not the other 
and i think only happen to 2 - 3 source

2021-04-09 13:44 UTC, CarlosEsco requested changes

2021-04-09 13:44 UTC, CarlosEsco commented on multisrc/overrides/wpmangastream/komikcast/src/KomikCast.kt
> +                        genre += if (genre!!.isEmpty()) it else ", $it"
why !!?

2021-04-09 13:44 UTC, CarlosEsco commented on multisrc/overrides/wpmangastream/komikcast/src/KomikCast.kt
> +                            description!!.isEmpty() -> altName + it
why !!?   also the alt name has change of being "-"?

2021-04-09 13:44 UTC, CarlosEsco commented on multisrc/overrides/wpmangastream/silencescan/src/SilenceScan.kt
> +                    description!!.isEmpty() -> altName + it
why !!

2021-04-09 13:44 UTC, CarlosEsco commented on multisrc/overrides/wpmangastream/westmanga/src/WestManga.kt
> +                        genre += if (genre!!.isEmpty()) it else ", $it"
why !!

2021-04-09 13:44 UTC, CarlosEsco commented on multisrc/overrides/wpmangastream/westmanga/src/WestManga.kt
> +                            description!!.isEmpty() -> altName + it
why !!

2021-04-09 13:44 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangabox/MangaBox.kt
> +                        description!!.isEmpty() -> altName + it
why !!

2021-04-09 13:44 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mangabox/MangaBox.kt
> +    open val altName = "Alternative Name" + ": "
Why concat?

2021-04-09 13:44 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/nepnep/NepNep.kt
> +                            description!!.isEmpty() -> altName + it
why !!

2021-04-09 13:44 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReader.kt
> +                genre += if (genre!!.isEmpty()) it else ", $it"
why !!

2021-04-09 13:44 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReader.kt
> +                    description!!.isEmpty() -> altName + it
why !!

2021-04-09 13:44 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReader.kt
> +    open val altName = "Alternative Name" + ": "
why concat?

2021-04-09 13:44 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStream.kt
> +                            description!!.isEmpty() -> altName + it
why !!

2021-04-09 13:44 UTC, CarlosEsco commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangastream/WPMangaStream.kt
> +    open val altName = "Alternative Name" + ": "
why concat

2021-04-09 13:44 UTC, CarlosEsco commented on src/en/mangapark/src/eu/kanade/tachiyomi/extension/en/mangapark/MangaPark.kt
> +                    description!!.isEmpty() -> altName + it
why !!

2021-04-09 13:44 UTC, CarlosEsco commented on src/id/komiku/src/eu/kanade/tachiyomi/extension/id/komiku/Komiku.kt
> +                genre += if (genre!!.isEmpty()) it else ", $it"
why !!

2021-04-09 13:44 UTC, CarlosEsco commented on src/id/maidmanga/src/eu/kanade/tachiyomi/extension/id/maidmanga/MaidManga.kt
> +                    genre += if (genre!!.isEmpty()) it else ", $it"
why !!

2021-04-09 13:44 UTC, CarlosEsco commented on src/id/maidmanga/src/eu/kanade/tachiyomi/extension/id/maidmanga/MaidManga.kt
> +                        description!!.isEmpty() -> altName + it
why !!

2021-04-09 13:44 UTC, CarlosEsco commented on src/id/manhuaid/src/eu/kanade/tachiyomi/extension/id/manhuaid/ManhuaID.kt
> +                genre += if (genre!!.isEmpty()) it else ", $it"
why !!

2021-04-11 10:59 UTC, as280093 commented
@Riztard One more MultiSource Icons
https://github.com/as280093/tachiyomi-extensions/issues/4

2021-04-13 09:37 UTC, Riztard commented
can be merged i think

2021-04-13 12:10 UTC, CarlosEsco approved these changes

2021-04-13 12:10 UTC, merged