[WIP] mmrcms split
tachiyomiorg/tachiyomi-extensions pull request #6569
Opened 2021-04-15 19:30 UTC by jopejoe1

To-Do:

- [ ] Implement Old generator / or some other way to make it easier to add sources
- [ ] add icons
- [ ] test all sources
- [ ] Improve Hentai Shark language selection

Closes #6466

2021-04-16 12:01 UTC, jopejoe1 commented
Removed:
- **Mangas Yuri** (Sells Manga now)
- **frscan** (Is offline from what I see)

2021-04-18 07:26 UTC, AriaMoradi requested changes

2021-04-18 07:26 UTC, AriaMoradi commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mmrcms/MMRCMSGenerator.kt
> +        SingleLang("مانجا اون لاين", "https://onma.me", "ar", className = "onma"),
Capitalize class name?

2021-04-21 18:03 UTC, jopejoe1 commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/mmrcms/MMRCMSGenerator.kt
> +        SingleLang("مانجا اون لاين", "https://onma.me", "ar", className = "onma"),
Yeah, seems right didn't think about that.

2021-04-26 06:43 UTC, papjul commented
> Removed:
> 
>     * **[frscan](https://www.frscan.me/)** (Is offline from what I see)

I don't know what the old website looked like, but I believe it's frscan.cc now?

2021-04-26 10:37 UTC, jopejoe1 commented
> > Removed:
> > ```
> > * **[frscan](https://www.frscan.me/)** (Is offline from what I see)
> > ```
> 
> I don't know what the old website looked like, but I believe it's frscan.cc now?

Added frscan.cc

2021-04-26 23:28 UTC, jopejoe1 commented
Should be ready for merge

2021-04-28 14:12 UTC, CarlosEsco commented
Unmark it draft?  How does this source work now?  Run MMRCMSJsonGen and thats it?

2021-04-28 19:45 UTC, jopejoe1 commented
Found a major bug that i need to fix first thats why i put it back into draft.

2021-04-29 06:34 UTC, jopejoe1 commented
Also need to change stuff to work with #6742

2021-04-29 07:07 UTC, jopejoe1 commented
> Unmark it draft?

See comments above

> How does this source work now? Run MMRCMSJsonGen and thats it?

That was the intended way, not sure if its still gone be like that after i fixe the bug.

2021-05-01 20:52 UTC, closed without merging