MangaDex Cover Qulity Setting
tachiyomiorg/tachiyomi-extensions pull request #8268
Opened 2021-07-25 12:53 UTC by FourTOne5

Closes #8262

2021-07-25 14:11 UTC, CarlosEsco requested changes

2021-07-25 14:11 UTC, CarlosEsco commented on src/all/mangadex/src/eu/kanade/tachiyomi/extension/all/mangadex/MDConstants.kt
> +        return arrayOf("Orginal", "512px Wide", "256px Wide")
Just say original, medium, low

2021-07-26 10:40 UTC, CarlosEsco approved these changes

2021-07-26 10:40 UTC, merged

2021-07-26 18:01 UTC, asl97 commented
Didn't seem to apply retroactively to covers that hasn't been downloaded but added to database (covers are only loaded when scroll into view),

I guess there is some kind of cache, clearing everything seem to get it to properly load the smaller images.