add Tachidesk extension
tachiyomiorg/tachiyomi-extensions pull request #8361
Opened 2021-08-01 21:48 UTC by AriaMoradi

This is the most basic possible implementation.

2021-08-02 09:55 UTC, ObserverOfTime commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Dto.kt
> +enum class MangaStatus(val status: Int) {
You can use the [`ordinal`](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-enum/ordinal.html) property instead of a custom status property and replace `MangaStatus.valueOf(value)` with `MangaStatus.values()[value]`.

2021-08-02 13:29 UTC, AriaMoradi commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Dto.kt
> +enum class MangaStatus(val status: Int) {
It conforms to Tachidesk's internal data classes, I have to convert Strings like "UNKNOWN" to it's ordinal value defined in Tachiyomi's manga status, do you have a better way?

2021-08-02 13:40 UTC, ObserverOfTime commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Dto.kt
> +enum class MangaStatus(val status: Int) {
I just realised that you're not actually using your `valueOf(Int)`, but the built-in `valueOf(String)`.

In that case, you can just remove your custom method, along with the `status` property, and use `MangaStatus.valueOf(status).ordinal` instead.

2021-08-02 13:51 UTC, ObserverOfTime commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +        }
```suggestion
        return List(chapter.pageCount) {
            Page(it + 1, "", "$baseUrl/api/v1/manga/$mangaId/chapter/$chapterIndex/page/$it/")
        }
```

2021-08-02 15:05 UTC, CarlosEsco commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Dto.kt
> +enum class MangaStatus(val status: Int) {
To add to the above.
"ONGOING" -> SManga.Ongoing

2021-08-02 21:06 UTC, alessandrojean requested changes

2021-08-02 21:06 UTC, alessandrojean commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +            "UNKNOWN" -> 0
```suggestion
            "UNKNOWN" -> SManga.UNKNOWN
```

Same with the other ones below this line.

2021-08-02 21:52 UTC, AriaMoradi commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +            "UNKNOWN" -> 0
Tachidesk supports the same exact 4 possible status, else can only represent an impossible error

2021-08-02 21:53 UTC, AriaMoradi commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +            "UNKNOWN" -> 0
Using `SManga` constants makes sense, I'll change that bit.

2021-08-02 22:02 UTC, CarlosEsco commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +            "UNKNOWN" -> 0
I think what he means is remove the 0 branch.  And make it just else at the end. So if tachidesk ever adds different statuses it will fall back to unknown besides going to else when 0

2021-08-03 11:36 UTC, AriaMoradi commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +            "UNKNOWN" -> 0
I another one is ever added, it'll be mirroring the same thing in Tachiyomi

2021-08-03 11:56 UTC, CarlosEsco requested changes

2021-08-03 11:56 UTC, CarlosEsco commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +                    e.printStackTrace()
Show log the exception here not print stacktrace

2021-08-03 11:59 UTC, CarlosEsco commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +            "UNKNOWN" -> 0
Defensive programming. The manga shouldn't fail to load, just because it doesn't know the status.  Just because you plan at this time to only match Tachiyomi status, doesn't mean someone else who forks tachi desk will, or you won't change your mind down the line.  There is no reason to throw an exception here.

2021-08-03 12:29 UTC, AriaMoradi commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +            "UNKNOWN" -> 0
alright, makes sense

2021-08-03 12:31 UTC, AriaMoradi commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +                    e.printStackTrace()
Hmm, took it from Komga btw

2021-08-03 12:32 UTC, CarlosEsco commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +                    e.printStackTrace()
Must have missed that.  But Log.e will print to the android console

2021-08-03 12:38 UTC, AriaMoradi commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +                    e.printStackTrace()
done

2021-08-03 12:49 UTC, CarlosEsco commented on src/all/tachidesk/src/eu/kanade/tachiyomi/extension/all/tachidesk/Tachidesk.kt
> +            "UNKNOWN" -> SManga.UNKNOWN
now that you have else -> SManga.UNKNOWN  you dont need this check

2021-08-03 12:57 UTC, CarlosEsco approved these changes

2021-08-03 14:13 UTC, merged