Add MangaSkanlacje.PL to tachiyomi extensions
tachiyomiorg/tachiyomi-extensions pull request #8422
Opened 2021-08-06 17:07 UTC by tomekatomek123456789

*Add MangaSkanlacje.PL Extension

2021-08-06 17:16 UTC, alessandrojean requested changes

2021-08-06 17:16 UTC, alessandrojean commented on src/pl/mangaskanlacje/build.gradle
> +    compileOnly 'com.google.code.gson:gson:2.8.6'
We're in the process of moving from Gson to Kotlinx.serialization.

Please read #7392.

2021-08-06 17:16 UTC, alessandrojean commented on src/pl/mangaskanlacje/src/eu/kanade/tachiyomi/extension/pl/mangaskanlacje/Generator.kt
> +class Generator {
Why there's a generator if it's not a multi source?

2021-08-06 17:16 UTC, alessandrojean commented on build.gradle
> +        classpath 'com.android.tools.build:gradle:7.0.0'
Better to undo this change and keep the same Gradle version.

2021-08-06 17:16 UTC, alessandrojean commented on gradle/wrapper/gradle-wrapper.properties
> +distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-bin.zip
Same here.

2021-08-06 17:16 UTC, alessandrojean commented on src/all/batoto/release/output-metadata.json
> +{
Can remove this file.

2021-08-06 17:18 UTC, alessandrojean commented
Also, this website uses MMRCMS, so you should only edit the MMRCMS multisrc stuff instead of creating an separated extension manually.

You can look at the mmrcms folder inside multisrc to get a better reference of how to do it.

2021-09-09 02:51 UTC, arkon commented
Seems like an abandoned PR, so I'm going to close this. Please open another PR if you decide to return to this.

2021-09-09 02:51 UTC, closed without merging