Add support to Order Of The Stick web comic.
tachiyomiorg/tachiyomi-extensions pull request #8519
Opened 2021-08-11 13:20 UTC by mifurlanetto

Hi everyone.
I wish to help, adding a new extension for a web comic I like.
I copied the structure from another extension, making the necessary adjustments, feel free to point out any mistake.
Hope you like it.

2021-08-11 13:39 UTC, CarlosEsco requested changes
closes #2885

2021-08-11 13:39 UTC, CarlosEsco commented on src/en/oots/local.properties
> +sdk.dir=C\:\\Users\\Maik\\AppData\\Local\\Android\\Sdk
delete this file

2021-08-11 13:48 UTC, mifurlanetto commented on src/en/oots/src/eu/kanade/tachiyomi/extension/en/oots/oots.kt
> +        chapter.date_upload = System.currentTimeMillis()
The issue here is the whole block or just the last line? if the latter, I wasn't sure to add it, but it said so in the contributing.md file

> SChapter.date_upload is the UNIX Epoch time expressed in miliseconds.
If you don't pass SChapter.date_upload, the user won't get notifications for new chapters. refer to this issue for more info. System.currentTimeMillis() works as a substitute when real data is not available.

2021-08-11 13:55 UTC, CarlosEsco commented on src/en/oots/src/eu/kanade/tachiyomi/extension/en/oots/oots.kt
> +        chapter.date_upload = System.currentTimeMillis()
@curche thoughts?

2021-08-11 14:17 UTC, curche commented on src/en/oots/src/eu/kanade/tachiyomi/extension/en/oots/oots.kt
> +        chapter.date_upload = System.currentTimeMillis()
Checking the source website, it doesn't seem to provide dates. 
Having no date would cause other issues (refer https://github.com/tachiyomiorg/tachiyomi/issues/4938)

Best method would be to follow what Ivan did for the CatManga ext and have new chapters assigned the date it was first fetched (check https://github.com/tachiyomiorg/tachiyomi-extensions/commit/50859e76aa06a889017831c9c12461d8790fd4b4)

2021-08-11 15:22 UTC, mifurlanetto commented on src/en/oots/src/eu/kanade/tachiyomi/extension/en/oots/oots.kt
> +        chapter.date_upload = System.currentTimeMillis()
Thanks! I'll do it in the next few days.

2021-08-12 15:08 UTC, CarlosEsco approved these changes

2021-08-12 15:08 UTC, merged