Update WPMangaReaderGenerator.kt
tachiyomiorg/tachiyomi-extensions pull request #9293
Opened 2021-09-30 19:44 UTC by brewokpanjang

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [ ] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [ ] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [ ] Annotated `Source` or `SourceFactory` classes with `@Nsfw` when appropriate
- [ ] Added the `containsNsfw = true` flag in `build.gradle` when appropriate
- [ ] Have not changed source names
- [ ] Have explicitly kept the `id` if a source's name or language were changed
- [ ] Have tested the modifications by compiling and running the extension through Android Studio

2021-09-30 19:47 UTC, alessandrojean requested changes

2021-09-30 19:47 UTC, alessandrojean commented on multisrc/src/main/java/eu/kanade/tachiyomi/multisrc/wpmangareader/WPMangaReaderGenerator.kt
> +        SingleLang("Sekaikomik", "https://www.sekaikomik.site", "id", isNsfw = true, overrideVersionCode = 7),
```suggestion
        SingleLang("Sekaikomik", "https://www.sekaikomik.site", "id", isNsfw = true, overrideVersionCode = 8),
```

Need to bump the `overrideVersionCode`.

2021-09-30 19:51 UTC, alessandrojean commented
You also need to update the `baseUrl` in `multisrc/overrides/wpmangareader/sekaikomik/src/Sekaikomik.kt`

2021-10-01 09:35 UTC, closed without merging

2021-10-01 09:35 UTC, CarlosEsco commented
Make the changes in 1 PR.