Mangaworld changed domain
tachiyomiorg/tachiyomi-extensions pull request #9294
Opened 2021-09-30 20:35 UTC by ildallo

.io to .in

closes #9291

Checklist:

- [ ] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Annotated `Source` or `SourceFactory` classes with `@Nsfw` when appropriate
- [x] Added the `containsNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2021-09-30 20:41 UTC, alessandrojean commented
Follow the checklist:

> Updated `extVersionCode` value in build.gradle for individual extensions

2021-09-30 21:16 UTC, alessandrojean commented
Did you compiled the extension and tested it?

2021-09-30 21:49 UTC, SmashBanana approved these changes

2021-09-30 22:33 UTC, ildallo commented
> Did you compiled the extension and tested it through Android Studio?
Yes

2021-09-30 22:44 UTC, arkon requested changes

2021-09-30 22:44 UTC, arkon commented on src/it/mangaworld/src/eu/kanade/tachiyomi/extension/it/mangaworld/Mangaworld.kt
> +        manga.author = infoElement.select("a[href^=https://www.mangaworld.in/archive?author=]").first()?.text()
Can you update these to refer to `baseUrl` instead?

2021-10-01 08:54 UTC, Gyro7 commented
Thanks god, I was going to work on it but you already did it!

2021-10-01 09:01 UTC, Riztard commented on src/it/mangaworld/src/eu/kanade/tachiyomi/extension/it/mangaworld/Mangaworld.kt
> +        manga.artist = infoElement.select("a[href^=https://www.mangaworld.in/archive?artist=]")?.text()
this too and the other better to refer to `baseurl` as arkon said

2021-10-01 13:15 UTC, ildallo commented
the code works perfectly, just approve it

2021-10-01 13:16 UTC, arkon commented on src/it/mangaworld/src/eu/kanade/tachiyomi/extension/it/mangaworld/Mangaworld.kt
> +        manga.author = infoElement.select("a[href^=https://www.mangaworld.in/archive?author=]").first()?.text()
You didn't actually resolve this.

2021-10-01 13:17 UTC, CarlosEsco commented
> 
> 
> the code works perfectly, just approve it

fix the requested changes

2021-10-01 13:20 UTC, closed without merging

2021-10-01 13:26 UTC, Gyro7 commented
So? Why did you close it?

2021-10-01 13:29 UTC, CarlosEsco commented
he obviously didn't want to actually test his code, or make the suggested changes