Tails Gets Trolled: add extension for the webcomic
tachiyomiorg/tachiyomi-extensions pull request #9854
Opened 2021-11-19 23:22 UTC by JerryWester

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2021-11-19 23:49 UTC, alessandrojean requested changes

2021-11-19 23:49 UTC, alessandrojean commented on src/all/tailsgetstrolled/src/eu/kanade/tachiyomi/extension/all/tailsgetstrolled/TailsGetsTrolled.kt
> +                date_upload = System.currentTimeMillis()
This will change the date of the chapters every time the chapter list is updated. If the website doesn't provide it, it's better to use [this workaround](https://github.com/tachiyomiorg/tachiyomi-extensions/blob/ef6654f072cf3e5749fdd1c4a9d09b13c18eea06/src/en/oots/src/eu/kanade/tachiyomi/extension/en/oots/oots.kt#L68-L78).

2021-11-19 23:49 UTC, alessandrojean commented on src/all/tailsgetstrolled/src/eu/kanade/tachiyomi/extension/all/tailsgetstrolled/TailsGetsTrolledFactory.kt
> +        TailsGetsTrolled("http://www.tailsgetstrolled.org/", "en")
Does it have other languages on the website? If it's not the case, there's no need to make it a SourceFactory.

2021-11-19 23:49 UTC, alessandrojean commented on src/all/tailsgetstrolled/src/eu/kanade/tachiyomi/extension/all/tailsgetstrolled/TailsGetsTrolled.kt
> +                    pages.add(Page(pages.size, "", image))
You don't need to call every page URL in this case, just fill the `url` attribute of `Page` and make usage of the `imageUrlParse`.

2021-11-20 00:40 UTC, JerryWester commented
Thanks for the review! I won't be able to work on this for a couple days, so I'll draft the PR until I can resolve those changes

2021-11-20 00:41 UTC, JerryWester commented on src/all/tailsgetstrolled/src/eu/kanade/tachiyomi/extension/all/tailsgetstrolled/TailsGetsTrolledFactory.kt
> +        TailsGetsTrolled("http://www.tailsgetstrolled.org/", "en")
There are translations available on the website, I just have yet to implement them into the extension

2022-06-01 02:36 UTC, closed without merging