Fix YugenMangas
tachiyomiorg/tachiyomi-extensions pull request #9968
Opened 2021-12-01 15:27 UTC by wolfghost9898

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

2021-12-01 15:35 UTC, alessandrojean requested changes

2021-12-01 15:47 UTC, wolfghost9898 commented on .run/MadaraGenerator.run.xml
>  <component name="ProjectRunConfigurationManager">
sorry fixed

2021-12-01 16:02 UTC, alessandrojean requested changes

2021-12-01 16:02 UTC, alessandrojean commented on .run/MadaraGenerator.run.xml
> +</component>g
```suggestion
</component>
```

2021-12-03 03:55 UTC, arkon commented on multisrc/overrides/madara/yugenmangas/src/YugenMangas.kt
> +class YugenMangas : Madara("YugenMangas", "https://yugenmangas.com/", "es")
I don't think this file is actually needed if it's not overriding anything special.

2021-12-04 01:02 UTC, Clouddark75 commented on multisrc/overrides/madara/yugenmangas/src/YugenMangas.kt
> +class YugenMangas : Madara("YugenMangas", "https://yugenmangas.com/", "es")
Just adding the source to Madara won't do, the site is using a heavily modified version of it, like Reaper kinda mod. That will need more work to have a working extension for that site.

2021-12-08 13:25 UTC, CarlosEsco commented
So is this good?

2021-12-19 15:01 UTC, arkon commented
@wolfghost9898 Was this tested?

2021-12-19 16:03 UTC, wolfghost9898 commented
> @wolfghost9898 Was this tested?
yes, I've been using it since I did the PR

![image](https://user-images.githubusercontent.com/20384738/146681780-72d0eb00-273f-4ba3-b330-a45b67cd79db.png)

2021-12-19 19:24 UTC, merged