added source: Aurora to fulfill #9985
tachiyomiorg/tachiyomi-extensions pull request #9986
Opened 2021-12-03 04:37 UTC by THE-ORONCO

This adds the source Aurora as a working extension to fulfill / close #9985.
The commited build was tested on a virtual Pixel 4a and a physical Huawei P20 light

Checklist:

- [x] Updated `extVersionCode` value in `build.gradle` for individual extensions
- [x] Updated `overrideVersionCode` or `baseVersionCode` as needed for all multisrc extensions
- [x] Referenced all related issues in the PR body (e.g. "Closes #xyz")
- [x] Added the `isNsfw = true` flag in `build.gradle` when appropriate
- [x] Have not changed source names
- [x] Have explicitly kept the `id` if a source's name or language were changed
- [x] Have tested the modifications by compiling and running the extension through Android Studio

This should be ready for a merge

2021-12-03 15:54 UTC, ObserverOfTime requested changes
The source only has a single series, each chapter has its own cover, and each page is a new release.
Therefore, this could be improved by promoting chapters to series and pages to chapters.

2021-12-03 15:54 UTC, ObserverOfTime commented on src/en/aurora/src/eu/kanade/tachiyomi/extension/en/aurora/Aurora.kt
> +        return GET(chapterListUrl)
```suggestion
        return GET(chapterListUrl, headers)
```

2021-12-03 15:54 UTC, ObserverOfTime commented on src/en/aurora/src/eu/kanade/tachiyomi/extension/en/aurora/Aurora.kt
> +                }
The filter seems unnecessary.
```suggestion
            doc.select(".blocks-gallery-item")
```

2021-12-03 15:54 UTC, ObserverOfTime commented on src/en/aurora/src/eu/kanade/tachiyomi/extension/en/aurora/Aurora.kt
> +            val currentPage = Jsoup.connect(currentUrl).get()
Use `client.newCall ...` instead of `Jsoup.connect`.

2021-12-03 15:54 UTC, ObserverOfTime commented on src/en/aurora/src/eu/kanade/tachiyomi/extension/en/aurora/Aurora.kt
> +                }
Again, unnecessary.
```suggestion
            val pageAndImageUrls = currentPage.select(".post-content")
```

2021-12-03 15:59 UTC, ObserverOfTime commented on src/en/aurora/src/eu/kanade/tachiyomi/extension/en/aurora/Aurora.kt
> +            val currentPage = Jsoup.connect(currentUrl).get()
Use `client.newCall ...` instead of `Jsoup.connect`.

2021-12-03 16:31 UTC, THE-ORONCO commented on src/en/aurora/src/eu/kanade/tachiyomi/extension/en/aurora/Aurora.kt
> +            val currentPage = Jsoup.connect(currentUrl).get()
I can do that.
Mind me asking why? I'm new to this whole extension thing and don't exactly know the current structure of Tachiyomi and why using the client instead of Jsoup is better.

2021-12-03 16:32 UTC, THE-ORONCO commented
> The source only has a single series, each chapter has its own cover, and each page is a new release. Therefore, this could be improved by promoting chapters to series and pages to chapters.

Doing this would cause new chapters to appear as new series, forcing the user to check this extension regularly after the end of the current chapter. It also breaks reading flow, forcing the reader to jump to a new series when they are finished with the current one.
The only problem I see with the current approach is potential problems when new comic pages get released. I couldn't test this yet.

2021-12-03 17:32 UTC, ObserverOfTime commented
> The only problem I see with the current approach is potential problems when new comic pages get released.

I believe the chapters wouldn't be considered new because they would still have the original date.
And even if they were, the user would probably have to go through all the previous pages first.

2021-12-03 18:05 UTC, THE-ORONCO commented
If it's ok, we could wait until a new page is released (next monday).
In the case the chapter won't be updated, I'll implement the structure you proposed where chapters are series and pages are chapters.

2021-12-07 17:50 UTC, THE-ORONCO commented
@ObserverOfTime You were right. Tachiyomi didn't update the chapters. Even when the chapter release date was changed when a new page was released. 
Now the Chapters have become different Mangas and the actual Pages are chapters of those.
This Extention can be built without errors and runs on a virtual Pixel 4a.

2021-12-07 22:19 UTC, ObserverOfTime requested changes
I'm mostly nitpicking but the URL changes are important.

2021-12-07 22:19 UTC, ObserverOfTime commented on src/en/aurora/src/eu/kanade/tachiyomi/extension/en/aurora/Aurora.kt
> +    }
You could just hardcode this.

```suggestion
    private val auroraDescription = """
    Aurora is a fantasy webcomic (updates M/W/F) written and illustrated by Red, better known for her work on the YouTube channel “Overly Sarcastic Productions.” It’s been in the works for over a decade, and she’s finally decided to stop putting it off.

    If you’d like to discuss the comic, it now has a subreddit, as well as a dedicated twitter and a tumblr where you can ask questions. There’s also a dedicated room on the channel discord for conversations about it!

    Find Red’s general ramblings on Twitter, alongside her cohost Blue, at OSPYouTube.
    """.trimIndent()
```

2021-12-07 22:19 UTC, ObserverOfTime commented on src/en/aurora/src/eu/kanade/tachiyomi/extension/en/aurora/Aurora.kt
> +            description = getAuroraDescription()
```suggestion
            description = auroraDescription
```
See below.

2021-12-07 22:19 UTC, ObserverOfTime commented on src/en/aurora/src/eu/kanade/tachiyomi/extension/en/aurora/Aurora.kt
> +            url = manga.url
```suggestion
            setUrlWithoutDomain(manga.url)
```

2021-12-07 22:19 UTC, ObserverOfTime commented on src/en/aurora/src/eu/kanade/tachiyomi/extension/en/aurora/Aurora.kt
> +        return Observable.just(fetchChapterListTR(manga.url, mutableListOf()))
```suggestion
        return Observable.just(fetchChapterListTR(baseUrl + manga.url, mutableListOf()))
```

2021-12-07 22:19 UTC, ObserverOfTime commented on src/en/aurora/src/eu/kanade/tachiyomi/extension/en/aurora/Aurora.kt
> +            return if (nextPageNavUrl.isEmpty()) {
```suggestion
            val nextPageNavUrl = currentPage.selectFirst(".paginav-next a")?.attr("href")
            // check if a next page actually exits and if not exit
            return if (nextPageNavUrl == null) {
```

2021-12-07 22:19 UTC, ObserverOfTime commented on src/en/aurora/src/eu/kanade/tachiyomi/extension/en/aurora/Aurora.kt
> +        val postTitle = newestPage.select(".post-title").text()
```suggestion
        val postTitle = newestPage.selectFirst(".post-title").text()
```

2021-12-07 22:19 UTC, ObserverOfTime commented on src/en/aurora/src/eu/kanade/tachiyomi/extension/en/aurora/Aurora.kt
> +                val chapterOverviewLink = chapter.select(".blocks-gallery-item__caption a")
```suggestion
                val chapterOverviewLink = chapter.selectFirst(".blocks-gallery-item__caption a")
```

2021-12-07 22:19 UTC, ObserverOfTime commented on src/en/aurora/src/eu/kanade/tachiyomi/extension/en/aurora/Aurora.kt
> +                val chapterThumbnail = chapter.select("figure img").attr("src")
```suggestion
                val chapterThumbnail = chapter.selectFirst("figure img").attr("src")
```

2021-12-07 22:19 UTC, ObserverOfTime commented on src/en/aurora/src/eu/kanade/tachiyomi/extension/en/aurora/Aurora.kt
> +                    val dateString = postContent.select(".post-date").text()
```suggestion
                    val chapterUrl = postContent.selectFirst(".webcomic-link").attr("href")
                    val title = postContent.selectFirst(".post-title a").text()
                    val chapterNr = title.substringAfter('.').toFloat()
                    val dateString = postContent.selectFirst(".post-date").text()
```
With this, chapter `1.2.3` will be chapter `2.3`, rather than just `3`.
If you don't want that, you can use `substringAfterLast` instead.

2021-12-07 22:19 UTC, ObserverOfTime commented on src/en/aurora/src/eu/kanade/tachiyomi/extension/en/aurora/Aurora.kt
> +import android.util.Log
Remove debug logs.
```suggestion
```

2021-12-07 22:19 UTC, ObserverOfTime commented on src/en/aurora/src/eu/kanade/tachiyomi/extension/en/aurora/Aurora.kt
> +        Log.d("uff", "${chapterBlockElements.size} chapters found")
```suggestion
```

2021-12-07 22:19 UTC, ObserverOfTime commented on src/en/aurora/src/eu/kanade/tachiyomi/extension/en/aurora/Aurora.kt
> +                Log.d("uff", chapterOverviewLink.toString())
```suggestion
```

2021-12-08 00:13 UTC, THE-ORONCO commented
Now everything that was suggested should be implemented. The extension is still working as intended (probably even better than before because of an unnecessary  request that could be removed)
I also tested it on a real phone just in case.

2021-12-08 08:23 UTC, ObserverOfTime commented on src/en/aurora/src/eu/kanade/tachiyomi/extension/en/aurora/Aurora.kt
> +                    url = chapterUrl
Not sure if I missed this one or you did. :thinking: 
```suggestion
                    setUrlWithoutDomain(chapterUrl)
```

2021-12-08 08:23 UTC, ObserverOfTime commented on src/en/aurora/src/eu/kanade/tachiyomi/extension/en/aurora/Aurora.kt
> +            GET(chapter.url, headers)
```suggestion
            GET(baseUrl + chapter.url, headers)
```

2021-12-08 12:22 UTC, ObserverOfTime approved these changes

2021-12-08 13:24 UTC, merged